language: go
jobs:
  include:
    - stage: test
      name: "Go 1.13"
      go:
        - 1.13.x
      install: skip
      script:
        - GO111MODULE=on go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
    - stage: test
      name: "Go 1.14"
      go:
        - 1.14.x
      install: skip
      script:
        - GO111MODULE=on go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
      after_success:
        - bash <(curl -s https://codecov.io/bash)
