#
# Makefile for optimizer
#
# src/spq_optimizer/libspqos/src/memory/Makefile
#
subdir = src/spq_optimizer/libspqos/src/memory
top_builddir = ../../../../../../..
include $(top_builddir)/src/Makefile.global
include ../../../spqorca.mk

OBJS = CAutoMemoryPool.o \
       CCacheFactory.o \
       CMemoryPool.o \
       CMemoryPoolManager.o \
       CMemoryPoolTracker.o \
       CMemoryVisitorPrint.o

include $(top_srcdir)/src/gausskernel/common.mk