//---------------------------------------------------------------------------
//	Greenplum Database
//	Copyright (C) 2009 Greenplum, Inc.
//
//	@filename:
//		ops.h
//
//	@doc:
//		collective include file for all operators
//---------------------------------------------------------------------------
#ifndef SPQOPT_ops_H
#define SPQOPT_ops_H

#include "spqopt/operators/CExpression.h"
#include "spqopt/operators/COperator.h"

// scalar ops
#include "spqopt/operators/CScalar.h"
#include "spqopt/operators/CScalarAggFunc.h"
#include "spqopt/operators/CScalarArray.h"
#include "spqopt/operators/CScalarArrayCmp.h"
#include "spqopt/operators/CScalarArrayCoerceExpr.h"
#include "spqopt/operators/CScalarArrayRef.h"
#include "spqopt/operators/CScalarArrayRefIndexList.h"
#include "spqopt/operators/CScalarAssertConstraint.h"
#include "spqopt/operators/CScalarAssertConstraintList.h"
#include "spqopt/operators/CScalarBitmapBoolOp.h"
#include "spqopt/operators/CScalarBitmapIndexProbe.h"
#include "spqopt/operators/CScalarBoolOp.h"
#include "spqopt/operators/CScalarBooleanTest.h"
#include "spqopt/operators/CScalarCaseTest.h"
#include "spqopt/operators/CScalarCast.h"
#include "spqopt/operators/CScalarCmp.h"
#include "spqopt/operators/CScalarCoalesce.h"
#include "spqopt/operators/CScalarCoerceToDomain.h"
#include "spqopt/operators/CScalarCoerceViaIO.h"
#include "spqopt/operators/CScalarConst.h"
#include "spqopt/operators/CScalarDMLAction.h"
#include "spqopt/operators/CScalarFunc.h"
#include "spqopt/operators/CScalarIdent.h"
#include "spqopt/operators/CScalarIf.h"
#include "spqopt/operators/CScalarIsDistinctFrom.h"
#include "spqopt/operators/CScalarMinMax.h"
#include "spqopt/operators/CScalarNullIf.h"
#include "spqopt/operators/CScalarNullTest.h"
#include "spqopt/operators/CScalarOp.h"
#include "spqopt/operators/CScalarProjectElement.h"
#include "spqopt/operators/CScalarProjectList.h"
#include "spqopt/operators/CScalarSubquery.h"
#include "spqopt/operators/CScalarSubqueryAll.h"
#include "spqopt/operators/CScalarSubqueryAny.h"
#include "spqopt/operators/CScalarSubqueryExists.h"
#include "spqopt/operators/CScalarSubqueryNotExists.h"
#include "spqopt/operators/CScalarSwitch.h"
#include "spqopt/operators/CScalarSwitchCase.h"
#include "spqopt/operators/CScalarValuesList.h"
#include "spqopt/operators/CScalarWindowFunc.h"

// logical ops
#include "spqopt/operators/CLogical.h"
#include "spqopt/operators/CLogicalApply.h"
#include "spqopt/operators/CLogicalAssert.h"
#include "spqopt/operators/CLogicalBitmapTableGet.h"
#include "spqopt/operators/CLogicalCTEAnchor.h"
#include "spqopt/operators/CLogicalCTEConsumer.h"
#include "spqopt/operators/CLogicalCTEProducer.h"
#include "spqopt/operators/CLogicalConstTableGet.h"
#include "spqopt/operators/CLogicalDML.h"
#include "spqopt/operators/CLogicalDelete.h"
#include "spqopt/operators/CLogicalDifference.h"
#include "spqopt/operators/CLogicalDifferenceAll.h"
#include "spqopt/operators/CLogicalDynamicBitmapTableGet.h"
#include "spqopt/operators/CLogicalDynamicGet.h"
#include "spqopt/operators/CLogicalDynamicIndexGet.h"
#include "spqopt/operators/CLogicalExternalGet.h"
#include "spqopt/operators/CLogicalFullOuterJoin.h"
#include "spqopt/operators/CLogicalGbAgg.h"
#include "spqopt/operators/CLogicalGbAggDeduplicate.h"
#include "spqopt/operators/CLogicalGet.h"
#include "spqopt/operators/CLogicalIndexApply.h"
#include "spqopt/operators/CLogicalIndexGet.h"
#include "spqopt/operators/CLogicalInnerApply.h"
#include "spqopt/operators/CLogicalInnerCorrelatedApply.h"
#include "spqopt/operators/CLogicalInnerJoin.h"
#include "spqopt/operators/CLogicalInsert.h"
#include "spqopt/operators/CLogicalIntersect.h"
#include "spqopt/operators/CLogicalIntersectAll.h"
#include "spqopt/operators/CLogicalJoin.h"
#include "spqopt/operators/CLogicalLeftAntiSemiApply.h"
#include "spqopt/operators/CLogicalLeftAntiSemiApplyNotIn.h"
#include "spqopt/operators/CLogicalLeftAntiSemiCorrelatedApply.h"
#include "spqopt/operators/CLogicalLeftAntiSemiCorrelatedApplyNotIn.h"
#include "spqopt/operators/CLogicalLeftAntiSemiJoin.h"
#include "spqopt/operators/CLogicalLeftAntiSemiJoinNotIn.h"
#include "spqopt/operators/CLogicalLeftOuterApply.h"
#include "spqopt/operators/CLogicalLeftOuterCorrelatedApply.h"
#include "spqopt/operators/CLogicalLeftOuterJoin.h"
#include "spqopt/operators/CLogicalLeftSemiApply.h"
#include "spqopt/operators/CLogicalLeftSemiApplyIn.h"
#include "spqopt/operators/CLogicalLeftSemiCorrelatedApply.h"
#include "spqopt/operators/CLogicalLeftSemiCorrelatedApplyIn.h"
#include "spqopt/operators/CLogicalLeftSemiJoin.h"
#include "spqopt/operators/CLogicalLimit.h"
#include "spqopt/operators/CLogicalMaxOneRow.h"
#include "spqopt/operators/CLogicalMultiExternalGet.h"
#include "spqopt/operators/CLogicalNAryJoin.h"
#include "spqopt/operators/CLogicalPartitionSelector.h"
#include "spqopt/operators/CLogicalProject.h"
#include "spqopt/operators/CLogicalRightOuterJoin.h"
#include "spqopt/operators/CLogicalRowTrigger.h"
#include "spqopt/operators/CLogicalSelect.h"
#include "spqopt/operators/CLogicalSequence.h"
#include "spqopt/operators/CLogicalSequenceProject.h"
#include "spqopt/operators/CLogicalSplit.h"
#include "spqopt/operators/CLogicalTVF.h"
#include "spqopt/operators/CLogicalUnion.h"
#include "spqopt/operators/CLogicalUnionAll.h"
#include "spqopt/operators/CLogicalUpdate.h"

// physical ops
#include "spqopt/operators/CPhysicalAssert.h"
#include "spqopt/operators/CPhysicalBitmapTableScan.h"
#include "spqopt/operators/CPhysicalCTEConsumer.h"
#include "spqopt/operators/CPhysicalCTEProducer.h"
#include "spqopt/operators/CPhysicalComputeScalar.h"
#include "spqopt/operators/CPhysicalConstTableGet.h"
#include "spqopt/operators/CPhysicalCorrelatedInLeftSemiNLJoin.h"
#include "spqopt/operators/CPhysicalCorrelatedInnerNLJoin.h"
#include "spqopt/operators/CPhysicalCorrelatedLeftAntiSemiNLJoin.h"
#include "spqopt/operators/CPhysicalCorrelatedLeftOuterNLJoin.h"
#include "spqopt/operators/CPhysicalCorrelatedLeftSemiNLJoin.h"
#include "spqopt/operators/CPhysicalCorrelatedNotInLeftAntiSemiNLJoin.h"
#include "spqopt/operators/CPhysicalDML.h"
#include "spqopt/operators/CPhysicalDynamicBitmapTableScan.h"
#include "spqopt/operators/CPhysicalDynamicIndexScan.h"
#include "spqopt/operators/CPhysicalDynamicTableScan.h"
#include "spqopt/operators/CPhysicalExternalScan.h"
#include "spqopt/operators/CPhysicalFilter.h"
#include "spqopt/operators/CPhysicalHashAgg.h"
#include "spqopt/operators/CPhysicalHashAggDeduplicate.h"
#include "spqopt/operators/CPhysicalHashJoin.h"
#include "spqopt/operators/CPhysicalIndexScan.h"
#include "spqopt/operators/CPhysicalInnerHashJoin.h"
#include "spqopt/operators/CPhysicalInnerIndexNLJoin.h"
#include "spqopt/operators/CPhysicalInnerNLJoin.h"
#include "spqopt/operators/CPhysicalLeftAntiSemiHashJoin.h"
#include "spqopt/operators/CPhysicalLeftAntiSemiHashJoinNotIn.h"
#include "spqopt/operators/CPhysicalLeftAntiSemiNLJoin.h"
#include "spqopt/operators/CPhysicalLeftAntiSemiNLJoinNotIn.h"
#include "spqopt/operators/CPhysicalLeftOuterHashJoin.h"
#include "spqopt/operators/CPhysicalLeftOuterIndexNLJoin.h"
#include "spqopt/operators/CPhysicalLeftOuterNLJoin.h"
#include "spqopt/operators/CPhysicalLeftSemiHashJoin.h"
#include "spqopt/operators/CPhysicalLeftSemiNLJoin.h"
#include "spqopt/operators/CPhysicalLimit.h"
#include "spqopt/operators/CPhysicalMotionBroadcast.h"
#include "spqopt/operators/CPhysicalMotionGather.h"
#include "spqopt/operators/CPhysicalMotionHashDistribute.h"
#include "spqopt/operators/CPhysicalMotionRoutedDistribute.h"
#include "spqopt/operators/CPhysicalMultiExternalScan.h"
#include "spqopt/operators/CPhysicalPartitionSelector.h"
#include "spqopt/operators/CPhysicalPartitionSelectorDML.h"
#include "spqopt/operators/CPhysicalRightOuterHashJoin.h"
#include "spqopt/operators/CPhysicalRowTrigger.h"
#include "spqopt/operators/CPhysicalScalarAgg.h"
#include "spqopt/operators/CPhysicalSequence.h"
#include "spqopt/operators/CPhysicalSequenceProject.h"
#include "spqopt/operators/CPhysicalSort.h"
#include "spqopt/operators/CPhysicalSplit.h"
#include "spqopt/operators/CPhysicalSpool.h"
#include "spqopt/operators/CPhysicalStreamAgg.h"
#include "spqopt/operators/CPhysicalStreamAggDeduplicate.h"
#include "spqopt/operators/CPhysicalTVF.h"
#include "spqopt/operators/CPhysicalTableScan.h"
#include "spqopt/operators/CPhysicalUnionAll.h"

// pattern ops
#include "spqopt/operators/CPatternLeaf.h"
#include "spqopt/operators/CPatternMultiLeaf.h"
#include "spqopt/operators/CPatternMultiTree.h"
#include "spqopt/operators/CPatternTree.h"

// helpers
#include "spqopt/operators/CPredicateUtils.h"

#endif	// !SPQOPT_ops_H

// EOF
