#
# Makefile for optimizer
#
# src/spq_optimizer/libspqopt/src/mdcache/Makefile
#
subdir = src/spq_optimizer/libspqopt/src/mdcache
top_builddir = ../../../../../../..
include $(top_builddir)/src/Makefile.global
include ../../../spqorca.mk

OBJS = CMDAccessor.o \
       CMDAccessorUtils.o \
       CMDCache.o \
       CMDKey.o

include $(top_srcdir)/src/gausskernel/common.mk