#
# Makefile for optimizer
#
# src/spq_optimizer/libspqopt/src/engine/Makefile
#
subdir = src/spq_optimizer/libspqopt/src/engine
top_builddir = ../../../../../../..
include $(top_builddir)/src/Makefile.global
include ../../../spqorca.mk

OBJS = CEngine.o \
       CEnumeratorConfig.o \
       CPartialPlan.o \
       CStatisticsConfig.o

include $(top_srcdir)/src/gausskernel/common.mk