create schema test_substring_index;
set current_schema to 'test_substring_index';
SELECT SUBSTRING_INDEX('www.opengauss.com','.',0);
SELECT SUBSTRING_INDEX('www.opengauss.com','',2);
SELECT SUBSTRING_INDEX('','.',2);
SELECT SUBSTRING_INDEX('','',2);
SELECT SUBSTRING_INDEX('www.opengauss.com','.',2);
SELECT SUBSTRING_INDEX('www.opengauss.com','.',-2);
SELECT SUBSTRING_INDEX('www.opengauss.com','.',3);
SELECT SUBSTRING_INDEX('www.opengauss.com','.',-3);
SELECT SUBSTRING_INDEX('www.opengauss.com','w',3);
SELECT SUBSTRING_INDEX('www.opengauss.com','W',3);
SELECT SUBSTRING_INDEX('www.opengauss.com','.',2.1);
SELECT SUBSTRING_INDEX('www.opengauss.com','.',-2.1);
SELECT SUBSTRING_INDEX('www.opengauss.com','.','2');
SELECT SUBSTRING_INDEX('www.opengauss.com','.','-2');
SELECT SUBSTRING_INDEX('www.opengauss.com','.','2.1');
SELECT SUBSTRING_INDEX('www.opengauss.com','.','-2.1');
SELECT SUBSTRING_INDEX('www.opengauss.com','.','abc');
SELECT SUBSTRING_INDEX('www.opengauss.com','.',2147483647);
SELECT SUBSTRING_INDEX('www.opengauss.com','.',-2147483648);
SELECT SUBSTRING_INDEX('www.opengauss.com','.',9223372036854775807);
SELECT SUBSTRING_INDEX('www.opengauss.com','.',-9223372036854775808);
SELECT SUBSTRING_INDEX('www.opengauss.com','.',10000000000000000000);
SELECT SUBSTRING_INDEX('www.opengauss.com','.',-10000000000000000000);
SELECT SUBSTRING_INDEX(123132,1,2);
SELECT SUBSTRING_INDEX(-123132,1,2);
SELECT SUBSTRING_INDEX(123132,-1,1);
SELECT SUBSTRING_INDEX(-123132,-1,1);
SELECT SUBSTRING_INDEX('123132',1,2);
SELECT SUBSTRING_INDEX(123132,'1',2);
SELECT SUBSTRING_INDEX(1.23,'.',1);
SELECT SUBSTRING_INDEX(1.23,1.2,1);
SELECT SUBSTRING_INDEX(True,'1',1);
SELECT SUBSTRING_INDEX(False,'0',1);
SELECT SUBSTRING_INDEX('0101',True,2);
SELECT SUBSTRING_INDEX('0101',False,2);
create table myTable(myText text, myInt int, myFloat float, myBool boolean, myDate date);
insert into myTable values ('www.opengauss.com',123321,1.123,True,'2022-10-11');
SELECT SUBSTRING_INDEX(myText,'.',2) FROM myTable;
SELECT SUBSTRING_INDEX(myInt,'1',2) FROM myTable;
SELECT SUBSTRING_INDEX(myFloat,'.',1) FROM myTable;
SELECT SUBSTRING_INDEX(myBool,'1',1) FROM myTable;
SELECT SUBSTRING_INDEX(myDate,'-',1) FROM myTable;
drop table myTable;
drop schema test_substring_index cascade;
reset current_schema;