#
# Makefile for optimizer
#
# src/spq_optimizer/libspqdbcost/src/Makefile
#
subdir = src/spq_optimizer/libspqdbcost/src
top_builddir = ../../../../../..
include $(top_builddir)/src/Makefile.global
include ../../spqorca.mk

OBJS = CCostModelParamsSPQDB.o \
	   CCostModelParamsSPQDBLegacy.o \
	   CCostModelSPQDB.o \
	   CCostModelSPQDBLegacy.o \
	   ICostModel.o

include $(top_srcdir)/src/gausskernel/common.mk