#
# Makefile for optimizer
#
# src/spq_optimizer/libnaucrates/src/md/Makefile
#
subdir = src/spq_optimizer/libnaucrates/src/md
top_builddir = ../../../../../../..
include $(top_builddir)/src/Makefile.global
include ../../../spqorca.mk

OBJS = CDXLBucket.o \
       CDXLColStats.o \
       CDXLRelStats.o \
       CDXLStatsDerivedColumn.o \
       CDXLStatsDerivedRelation.o \
       CMDAggregateSPQDB.o \
       CMDArrayCoerceCastSPQDB.o \
       CMDCastSPQDB.o \
       CMDCheckConstraintSPQDB.o \
       CMDColumn.o \
       CMDFunctionSPQDB.o \
       CMDIdCast.o \
       CMDIdColStats.o \
       CMDIdRelStats.o \
       CMDIdScCmp.o \
       CMDIdSPQDB.o \
       CMDIdSPQDBCtas.o \
       CMDIndexInfo.o \
       CMDIndexSPQDB.o \
       CMDName.o \
       CMDPartConstraintSPQDB.o \
       CMDProviderGeneric.o \
       CMDProviderMemory.o \
       CMDRelationCtasSPQDB.o \
       CMDRelationExternalSPQDB.o \
       CMDRelationSPQDB.o \
       CMDRequest.o \
       CMDScalarOpSPQDB.o \
       CMDScCmpSPQDB.o \
       CMDTriggerSPQDB.o \
       CMDTypeBoolSPQDB.o \
       CMDTypeGenericSPQDB.o \
       CMDTypeInt2SPQDB.o \
       CMDTypeInt4SPQDB.o \
       CMDTypeInt8SPQDB.o \
       CMDTypeOidSPQDB.o \
       CSystemId.o \
       IMDCacheObject.o \
       IMDIndex.o \
       IMDProvider.o \
       IMDRelation.o \
       IMDType.o

include $(top_srcdir)/src/gausskernel/common.mk