#
# Makefile for optimizer
#
# src/spq_optimizer/libspqos/src/test/Makefile
#
subdir = src/spq_optimizer/libspqos/src/test
top_builddir = ../../../../../..
include $(top_builddir)/src/Makefile.global

include $(top_builddir)/src/backend/gporca/gporca.mk

include $(top_srcdir)/src/backend/common.mk


