#
# Makefile for optimizer
#
# src/spq_optimizer/libspqopt/src/optimizer/Makefile
#
subdir = src/spq_optimizer/libspqopt/src/optimizer
top_builddir = ../../../../../../..
include $(top_builddir)/src/Makefile.global
include ../../../spqorca.mk

OBJS = COptimizer.o COptimizerConfig.o

include $(top_srcdir)/src/gausskernel/common.mk