drop database if exists b_databaselock;
create database b_databaselock dbcompatibility 'b';
\c b_databaselock

select get_lock('aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',1);
select get_lock('aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',1);

select get_lock('获取一个锁2022',1);

select get_lock('1234567890',1);
select get_lock(1,1);
select get_lock(1234567890,1);

select get_lock('`',1);
select get_lock('~',1);
select get_lock('!',1);
select get_lock('@',1);
select get_lock('#',1);
select get_lock('$',1);
select get_lock('%',1);
select get_lock('^',1);
select get_lock('&',1);
select get_lock('*',1);
select get_lock('(',1);
select get_lock(')',1);
select get_lock('[',1);
select get_lock(']',1);
select get_lock('{',1);
select get_lock('}',1);
select get_lock('-',1);
select get_lock('_',1);
select get_lock('=',1);
select get_lock('+',1);
select get_lock('\',1);
select get_lock('|',1);
select get_lock(';',1);
select get_lock(':',1);
select get_lock('""""',1);
select get_lock(',',1);
select get_lock('.',1);
select get_lock('/',1);
select get_lock('<',1);
select get_lock('>',1);
select get_lock('?',1);

select get_lock('·',1);
select get_lock('~',1);
select get_lock('！',1);
select get_lock('@',1);
select get_lock('#',1);
select get_lock('￥',1);
select get_lock('%',1);
select get_lock('……',1);
select get_lock('&',1);
select get_lock('*',1);
select get_lock('（',1);
select get_lock('）',1);
select get_lock('-',1);
select get_lock('——',1);
select get_lock('=',1);
select get_lock('+',1);
select get_lock('【',1);
select get_lock('】',1);
select get_lock('{',1);
select get_lock('}',1);
select get_lock('、',1);
select get_lock('|',1);
select get_lock('；',1);
select get_lock('：',1);
select get_lock('‘',1);
select get_lock('“',1);
select get_lock('”',1);
select get_lock('，',1);
select get_lock('《',1);
select get_lock('。',1);
select get_lock('》',1);
select get_lock('/',1);
select get_lock('？',1);

select get_lock('a                                                             a');
select get_lock('a                                                              a');
select get_lock('1                                                              1');
select get_lock('a                                                              1');
select get_lock(' ');


select release_lock('aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa');
select release_lock('aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa');
select release_lock('获取一个锁2022');

select release_lock('1234567890');
select release_lock(1);
select release_lock(1234567890);

select release_lock('`');
select release_lock('~');
select release_lock('!');
select release_lock('@');
select release_lock('#');
select release_lock('$');
select release_lock('%');
select release_lock('^');
select release_lock('&');
select release_lock('*');
select release_lock('(');
select release_lock(')');
select release_lock('[');
select release_lock(']');
select release_lock('{');
select release_lock('}');
select release_lock('-');
select release_lock('_');
select release_lock('=');
select release_lock('+');
select release_lock('\');
select release_lock('|');
select release_lock(';');
select release_lock(':');
select release_lock('""""');
select release_lock(',');
select release_lock('.');
select release_lock('/');
select release_lock('<');
select release_lock('>');
select release_lock('?');

select release_lock('·');
select release_lock('~');
select release_lock('！');
select release_lock('@');
select release_lock('#');
select release_lock('￥');
select release_lock('%');
select release_lock('……');
select release_lock('&');
select release_lock('*');
select release_lock('（');
select release_lock('）');
select release_lock('-');
select release_lock('——');
select release_lock('=');
select release_lock('+');
select release_lock('【');
select release_lock('】');
select release_lock('{');
select release_lock('}');
select release_lock('、');
select release_lock('|');
select release_lock('；');
select release_lock('：');
select release_lock('‘');
select release_lock('“');
select release_lock('”');
select release_lock('，');
select release_lock('《');
select release_lock('。');
select release_lock('》');
select release_lock('/');
select release_lock('？');

select release_lock('a                                                             a');
select release_lock('a                                                              a');
select release_lock('1                                                              1');
select release_lock('a                                                              1');
select release_lock(' ');
\c postgres
drop database if exists b_databaselock;
