#
# Makefile for optimizer
#
# src/spq_optimizer/libspqos/Makefile
#
subdir = src/spq_optimizer/libspqos
top_builddir = ../../../../..
include $(top_builddir)/src/Makefile.global

SUBDIRS = src

include $(top_srcdir)/src/gausskernel/common.mk