#---------------------------------------------------------------------------------------
#
#  IDENTIFICATION
#        src/gausskernel/optimizer/Makefile
#
# ---------------------------------------------------------------------------------------

subdir = contrib/dolphin/plugin_optimizer
top_builddir = ../../..
base_dir = contrib/dolphin
include $(top_builddir)/src/Makefile.global
include $(top_builddir)/$(base_dir)/configure.mk
SUBDIRS     = commands

include $(top_srcdir)/src/gausskernel/common.mk
