# Makefile for optimizer
#
# src/spq_optimizer/Makefile
#
subdir = src/spq_optimizer
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global
include $(top_builddir)/contrib/spq_plugin/spqplugin.mk

SUBDIRS = libspqos \
		  libspqdbcost \
		  libnaucrates \
		  libspqopt

include $(top_srcdir)/src/gausskernel/common.mk