#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for gpopt
#
#-------------------------------------------------------------------------
subdir = src/spq_optimizer_util/relcache
top_builddir = ../../../../..
include $(top_builddir)/src/Makefile.global
include ../spq_optimizer_util.mk

OBJS = CMDProviderRelcache.o

include $(top_srcdir)/src/gausskernel/common.mk