#
# Makefile for optimizer
#
# src/spq_optimizer/libspqos/src/error/Makefile
#
subdir = src/spq_optimizer/libspqos/src/error
top_builddir = ../../../../../../..
include $(top_builddir)/src/Makefile.global
include ../../../spqorca.mk

OBJS = CAutoExceptionStack.o \
       CAutoTrace.o \
       CErrorContext.o \
       CErrorHandlerStandard.o \
       CException.o \
       CFSimulator.o \
       CLogger.o \
       CLoggerStream.o \
       CLoggerSyslog.o \
       CMessage.o \
       CMessageRepository.o \
       CMessageTable.o \
       CMiniDumper.o \
       CSerializable.o \
       ILogger.o

include $(top_srcdir)/src/gausskernel/common.mk