create schema get_db;
set current_schema to 'get_db';
select database();
create schema testdb;
use testdb;
select database();
create schema testdb1;
select database();
use testdb1;
select database();
drop schema get_db cascade;
reset current_schema;
