SET DOLPHIN.B_COMPATIBILITY_MODE TO ON;
CREATE SCHEMA NULLS_GET_PARTITION;
SET SEARCH_PATH TO NULLS_GET_PARTITION;
CREATE TABLE T_CREATE_TABLE_PARTITION_002
(
    COL1 INT,
    COL2 INT

)
    PARTITION BY RANGE (COL1) SUBPARTITION BY RANGE(COL2)
(
        PARTITION P0 VALUES LESS THAN (18)
        (
                SUBPARTITION P0_0 VALUES LESS THAN (1000),
                SUBPARTITION P0_1 VALUES LESS THAN (2000),
                SUBPARTITION P0_2 VALUES LESS THAN (4000)
        ),
        PARTITION P1 VALUES LESS THAN (35)
        (
                SUBPARTITION P1_0 VALUES LESS THAN (5000),
                SUBPARTITION P1_1 VALUES LESS THAN (6000),
                SUBPARTITION P1_2 VALUES LESS THAN (8000)
        ),
        PARTITION P2 VALUES LESS THAN MAXVALUE
        (
                SUBPARTITION P2_0 VALUES LESS THAN (10000),
                SUBPARTITION P2_1 VALUES LESS THAN (20000),
                SUBPARTITION P2_2 VALUES LESS THAN MAXVALUE
        )
);


CREATE TABLE TABLE_LIST1
(
    ID  INT,
    ID2 INT
)
    PARTITION BY LIST (ID) SUBPARTITION BY LIST(ID2)
(
    PARTITION TABLE_LIST1_P1 VALUES (1, 2, 3, 4)
    (
        SUBPARTITION TABLE_LIST1_P1_0 VALUES(1,2,3,4),
        SUBPARTITION TABLE_LIST1_P1_4 VALUES(DEFAULT)
    ),
    PARTITION TABLE_LIST1_P2 VALUES (5, 6, 7, 8)
    (
        SUBPARTITION TABLE_LIST1_P2_0 VALUES(1,2,3,4),
        SUBPARTITION TABLE_LIST1_P2_4 VALUES(DEFAULT)
    ),
    PARTITION TABLE_LIST1_P3 VALUES (9, 10, 11, 12)
        (
        SUBPARTITION TABLE_LIST1_P3_0 VALUES(1,2,3,4),
        SUBPARTITION TABLE_LIST1_P3_4 VALUES(DEFAULT)
    ),
    PARTITION TABLE_LIST1_P4 VALUES (DEFAULT)
        (
        SUBPARTITION TABLE_LIST1_P4_0 VALUES(1,2,3,4),
        SUBPARTITION TABLE_LIST1_P4_4 VALUES(DEFAULT)
    )
);


CREATE TABLE MULTI_KEYS_LIST
(
    F1 INT,
    F2 INT,
    F3 INT
)
    PARTITION BY LIST (F1, F2)
( PARTITION MULTI_KEYS_LIST_P0 VALUES ((0, NULL)),
    PARTITION MULTI_KEYS_LIST_P1 VALUES ((15, 0)),
    PARTITION MULTI_KEYS_LIST_P2 VALUES (DEFAULT));

SHOW CREATE TABLE T_CREATE_TABLE_PARTITION_002;
SHOW CREATE TABLE TABLE_LIST1;
SHOW CREATE TABLE MULTI_KEYS_LIST;