create schema show_variables;
set current_schema to 'show_variables';
SET datestyle TO postgres, dmy;
show variables like 'DateSty%';
show variables where variable_name like 'DateSty%';
show variables where variable_name = 'DateStyle';
show session variables like 'DateSty%';
show session variables where variable_name like 'DateSty%';
show session variables where variable_name = 'DateStyle';
show global variables like 'DateSty%';
show global variables where variable_name like 'DateSty%';
show global variables where variable_name = 'DateStyle';
SET datestyle TO ISO, MDY;
show session variables where variable_name = 'DateStyle';
show global variables where variable_name = 'DateStyle';
RESET datestyle;
drop schema show_variables cascade;
reset current_schema;