create schema db_charset;
set current_schema to 'db_charset';
show client_encoding;
set charset gbk;
show client_encoding;
set charset default;
show client_encoding;
set character set 'gbk';
show client_encoding;
set character set default;
show client_encoding;

set names gbk;
show client_encoding;
set names default;
show client_encoding;
set names 'gbk';
show client_encoding;
set names default;
show client_encoding;
set names binary;
show client_encoding;
drop schema db_charset cascade;
reset current_schema;
