drop database if exists test_bool_float;
create database test_bool_float dbcompatibility 'b';
\c test_bool_float
set dolphin.b_compatibility_mode = true;

select 1::bool ^ 2::int1;
select 1::bool ^ 2::int2;
select 1::bool ^ 2::int4;
select 1::bool ^ 2::int8;
select 1::bool ^ 2::uint1;
select 1::bool ^ 2::uint2;
select 1::bool ^ 2::uint4;
select 1::bool ^ 2::uint8;
select 1::bool ^ 2.0;
select 1::bool ^ 2::float;
select 1::bool ^ 2::float8;
select 1::bool ^ 2::numeric;
select 1::bool ^ 2::bool;

select (-1)::bool ^ 2::int2;
select (-1)::bool ^ 2::int4;
select (-1)::bool ^ 2::int8;
select (-1)::bool ^ 2::uint1;
select (-1)::bool ^ 2::uint2;
select (-1)::bool ^ 2::uint4;
select (-1)::bool ^ 2::uint8;
select (-1)::bool ^ 2.0;
select (-1)::bool ^ 2::float;
select (-1)::bool ^ 2::float8;
select (-1)::bool ^ 2::numeric;
select (-1)::bool ^ 2::bool;

select (-1)::bool ^ (-2)::int2;
select (-1)::bool ^ (-2)::int4;
select (-1)::bool ^ (-2)::int8;
select (-1)::bool ^ (-2)::uint1;
select (-1)::bool ^ (-2)::uint2;
select (-1)::bool ^ (-2)::uint4;
select (-1)::bool ^ (-2)::uint8;
select (-1)::bool ^ -2.0;
select (-1)::bool ^ (-2)::float;
select (-1)::bool ^ (-2)::float8;
select (-1)::bool ^ (-2)::numeric;
select (-1)::bool ^ (-2)::bool;

select 1::float ^ 2::int1;
select 1::float ^ 2::int2;
select 1::float ^ 2::int4;
select 1::float ^ 2::int8;
select 1::float ^ 2::uint1;
select 1::float ^ 2::uint2;
select 1::float ^ 2::uint4;
select 1::float ^ 2::uint8;
select 1::float ^ 2.0;
select 1::float ^ 2::bool;
select 1::float ^ 2::float8;
select 1::float ^ 2::numeric;
select 1::float ^ 2::float;

select (-1)::float ^ 2::int2;
select (-1)::float ^ 2::int4;
select (-1)::float ^ 2::int8;
select (-1)::float ^ 2::uint2;
select (-1)::float ^ 2::uint4;
select (-1)::float ^ 2::uint8;
select (-1)::float ^ 2.0;
select (-1)::float ^ 2::bool;
select (-1)::float ^ 2::float8;
select (-1)::float ^ 2::numeric;
select (-1)::float ^ 2::float;

select (-1)::float ^ (-2)::int2;
select (-1)::float ^ (-2)::int4;
select (-1)::float ^ (-2)::int8;
select (-1)::float ^ (-2)::uint2;
select (-1)::float ^ (-2)::uint4;
select (-1)::float ^ (-2)::uint8;
select (-1)::float ^ -2.0;
select (-1)::float ^ (-2)::bool;
select (-1)::float ^ (-2)::float8;
select (-1)::float ^ (-2)::numeric;
select (-1)::float ^ (-2)::float;

select 1::float8 ^ 2::int1;
select 1::float8 ^ 2::int2;
select 1::float8 ^ 2::int4;
select 1::float8 ^ 2::int8;
select 1::float8 ^ 2::uint1;
select 1::float8 ^ 2::uint2;
select 1::float8 ^ 2::uint4;
select 1::float8 ^ 2::uint8;
select 1::float8 ^ 2.0;
select 1::float8 ^ 2::float;
select 1::float8 ^ 2::float8;
select 1::float8 ^ 2::numeric;
select 1::float8 ^ 2::float8;

select (-1)::float8 ^ 2::int2;
select (-1)::float8 ^ 2::int4;
select (-1)::float8 ^ 2::int8;
select (-1)::float8 ^ 2::uint1;
select (-1)::float8 ^ 2::uint2;
select (-1)::float8 ^ 2::uint4;
select (-1)::float8 ^ 2::uint8;
select (-1)::float8 ^ 2.0;
select (-1)::float8 ^ 2::float;
select (-1)::float8 ^ 2::float8;
select (-1)::float8 ^ 2::numeric;
select (-1)::float8 ^ 2::float8;

select (-1)::float8 ^ (-2)::int2;
select (-1)::float8 ^ (-2)::int4;
select (-1)::float8 ^ (-2)::int8;
select (-1)::float8 ^ (-2)::uint1;
select (-1)::float8 ^ (-2)::uint2;
select (-1)::float8 ^ -2.0;
select (-1)::float8 ^ (-2)::float;
select (-1)::float8 ^ (-2)::float8;
select (-1)::float8 ^ (-2)::numeric;
select (-1)::float8 ^ (-2)::float8;

select 1::numeric ^ 2::int1;
select 1::numeric ^ 2::int2;
select 1::numeric ^ 2::int4;
select 1::numeric ^ 2::int8;
select 1::numeric ^ 2::uint1;
select 1::numeric ^ 2::uint2;
select 1::numeric ^ 2::uint4;
select 1::numeric ^ 2::uint8;
select 1::numeric ^ 2.0;
select 1::numeric ^ 2::bool;
select 1::numeric ^ 2::float;
select 1::numeric ^ 2::float8;
select 1::numeric ^ 2::numeric;

select (-1)::numeric ^ 2::int2;
select (-1)::numeric ^ 2::int4;
select (-1)::numeric ^ 2::int8;
select (-1)::numeric ^ 2::uint1;
select (-1)::numeric ^ 2::uint2;
select (-1)::numeric ^ 2::uint4;
select (-1)::numeric ^ 2::uint8;
select (-1)::numeric ^ 2.0;
select (-1)::numeric ^ 2::bool;
select (-1)::numeric ^ 2::float;
select (-1)::numeric ^ 2::float8;
select (-1)::numeric ^ 2::numeric;

select (-1)::numeric ^ (-2)::int2;
select (-1)::numeric ^ (-2)::int4;
select (-1)::numeric ^ (-2)::int8;
select (-1)::numeric ^ (-2)::uint1;
select (-1)::numeric ^ (-2)::uint2;
select (-1)::numeric ^ (-2)::uint4;
select (-1)::numeric ^ -2.0;
select (-1)::numeric ^ (-2)::bool;
select (-1)::numeric ^ (-2)::float;
select (-1)::numeric ^ (-2)::float8;
select (-1)::numeric ^ (-2)::numeric;

set dolphin.b_compatibility_mode = false;
\c postgres
drop database test_bool_float;
