create schema test_view_table_depend;
set current_schema to 'test_view_table_depend';
create table t1 (c1 int);
create view v1 as select * from t1;
drop table t1;
\d v1;
\d+ v1;
select * from v1;
create table t2 (c1 int);
select * from v1;
drop table t2;
create table t1 (c2 int);
select * from v1;
drop table t1;
create table t1 (c1 int);
insert into t1 values(1);
select * from v1;
\d v1;
\d+ v1;
drop table t1;
create table t1 (c1 varchar);
insert into t1 values('a');
select * from v1;
\d v1;
\d+ v1;

drop table t1 cascade;
create table t1 (c1 int);
create view v1 as select * from t1;
insert into t1 values(1);
select * from v1;
\d v1;
\d+ v1;
drop table t1;
create table t1 (c2 int, c3 int, c1 int);
insert into t1 values(2, 3, 1);
select * from v1;
\d v1;
\d+ v1;

drop table t1 cascade;
create table t1 (c1 int, c2 int, c3 int);
create view v1 as select * from t1;
insert into t1 values(1, 2, 3);
select * from v1;
\d v1;
\d+ v1;
drop table t1;
create table t1 (c2 int);
insert into t1 values(2);
select * from v1;
\d v1;
\d+ v1;

drop view v1;
drop table t1 cascade;
create table t1 (c1 int);
create view v1 as select * from t1;
create view v2 as select * from v1;
insert into t1 values(1);
select * from v1;
select * from v2;
\d v1;
\d v2;
\d+ v1;
\d+ v2;
drop table t1;
\d v1;
\d v2;
\d+ v1;
\d+ v2;
select * from v1;
select * from v2;
create table t1 (c1 varchar);
insert into t1 values('a');
select * from v1;
select * from v2;
\d v1;
\d v2;
\d+ v1;
\d+ v2;

drop table t1 cascade;
create table t1 (c1 int);
create view v1 as select c1 from t1;
create view v2 as select c1 + 1 from v1;
insert into t1 values(1);
select * from v1;
select * from v2;
\d v1;
\d v2;
\d+ v1;
\d+ v2;
drop table t1;
\d v1;
\d v2;
\d+ v1;
\d+ v2;
select * from v1;
select * from v2;
create table t1 (c1 int);
insert into t1 values(1);
select * from v1;
select * from v2;
\d v1;
\d v2;
\d+ v1;
\d+ v2;

drop table t1 cascade;
create table t1 (c1 int);
create view v1 as select c1 + 1 from t1;
insert into t1 values(1);
select * from v1;
\d v1;
\d+ v1;
drop table t1;
\d v1;
\d+ v1;
select * from v1;
create table t1 (c1 int);
insert into t1 values(1);
select * from v1;
\d v1;
\d+ v1;

drop table t1 cascade;
create table t1 (c1 int);
create table t2 (c2 int);
create view v1 as select c1 + c2 from t1 join t2;
insert into t1 values(1);
insert into t2 values(2);
select * from v1;
\d v1;
\d+ v1;
drop table t1;
\d v1;
\d+ v1;
select * from v1;
create table t1 (c1 int);
insert into t1 values(1);
select * from v1;
\d v1;
\d+ v1;

drop table t1 cascade;
drop schema test_view_table_depend cascade;
reset current_schema;
