#
# Makefile for optimizer
#
# src/spq_optimizer/libspqos/src/string/Makefile
#
subdir = src/spq_optimizer/libspqos/src/string
top_builddir = ../../../../../../..
include $(top_builddir)/src/Makefile.global
include ../../../spqorca.mk

OBJS = CStringStatic.o \
       CWString.o \
       CWStringBase.o \
       CWStringConst.o \
       CWStringDynamic.o \
       CWStringStatic.o

include $(top_srcdir)/src/gausskernel/common.mk