#
# Makefile for optimizer
#
# src/spq_optimizer/libspqopt/src/search/Makefile
#
subdir = src/spq_optimizer/libspqopt/src/search
top_builddir = ../../../../../../..
include $(top_builddir)/src/Makefile.global
include ../../../spqorca.mk

OBJS = CBinding.o \
       CGroup.o \
       CGroupExpression.o \
       CGroupProxy.o \
       CJob.o \
       CJobFactory.o \
       CJobGroup.o \
       CJobGroupExploration.o \
       CJobGroupExpression.o \
       CJobGroupExpressionExploration.o \
       CJobGroupExpressionImplementation.o \
       CJobGroupExpressionOptimization.o \
       CJobGroupImplementation.o \
       CJobGroupOptimization.o \
       CJobQueue.o \
       CJobTest.o \
       CJobTransformation.o \
       CMemo.o \
       CScheduler.o \
       CSchedulerContext.o \
       CSearchStage.o

include $(top_srcdir)/src/gausskernel/common.mk