#
# Makefile for optimizer
#
# contrib/spq_plugin/src/spq_optimizer/libnaucrates/Makefile
#
subdir = src/spq_optimizer/libnaucrates
top_builddir = ../../../../..
include $(top_builddir)/src/Makefile.global

SUBDIRS = src

include $(top_srcdir)/src/gausskernel/common.mk