#
# Makefile for optimizer
#
# src/spq_optimizer/libspqos/src/io/Makefile
#
subdir = src/spq_optimizer/libspqos/src/io
top_builddir = ../../../../../../..
include $(top_builddir)/src/Makefile.global
include ../../../spqorca.mk

OBJS = CFileDescriptor.o \
       CFileReader.o \
       CFileWriter.o \
       COstream.o \
       COstreamBasic.o \
       COstreamFile.o \
       COstreamStdString.o \
       COstreamString.o \
       ioutils.o

include $(top_srcdir)/src/gausskernel/common.mk