#---------------------------------------------------------------------------------------
#
#  IDENTIFICATION
#        src/gausskernel/optimizer/Makefile
#
# ---------------------------------------------------------------------------------------

subdir = contrib/whale/plugin_optimizer
top_builddir = ../../..
base_dir = contrib/whale
include $(top_builddir)/src/Makefile.global
include $(top_builddir)/$(base_dir)/configure.mk

SUBDIRS     = plan

include $(top_srcdir)/src/gausskernel/common.mk
