// This is a generated file

#ifndef _EXECUTER_GSTRACE_H
#define _EXECUTER_GSTRACE_H

#include "comps.h"
#include "gstrace_infra.h"

#define GS_TRC_ID_execTuplesMatch GS_TRC_ID_PACK(COMP_EXECUTER, 1)
#define GS_TRC_ID_execTuplesUnequal GS_TRC_ID_PACK(COMP_EXECUTER, 2)
#define GS_TRC_ID_execTuplesMatchPrepare GS_TRC_ID_PACK(COMP_EXECUTER, 3)
#define GS_TRC_ID_execTuplesHashPrepare GS_TRC_ID_PACK(COMP_EXECUTER, 4)
#define GS_TRC_ID_BuildTupleHashTable GS_TRC_ID_PACK(COMP_EXECUTER, 5)
#define GS_TRC_ID_LookupTupleHashEntry GS_TRC_ID_PACK(COMP_EXECUTER, 6)
#define GS_TRC_ID_FindTupleHashEntry GS_TRC_ID_PACK(COMP_EXECUTER, 7)
#define GS_TRC_ID_ExecInitJunkFilter GS_TRC_ID_PACK(COMP_EXECUTER, 8)
#define GS_TRC_ID_ExecInitJunkFilterConversion GS_TRC_ID_PACK(COMP_EXECUTER, 9)
#define GS_TRC_ID_ExecFindJunkAttribute GS_TRC_ID_PACK(COMP_EXECUTER, 10)
#define GS_TRC_ID_ExecFindJunkAttributeInTlist GS_TRC_ID_PACK(COMP_EXECUTER, 11)
#define GS_TRC_ID_ExecGetJunkAttribute GS_TRC_ID_PACK(COMP_EXECUTER, 12)
#define GS_TRC_ID_ExecFilterJunk GS_TRC_ID_PACK(COMP_EXECUTER, 13)
#define GS_TRC_ID_ExecSetjunkFilteDescriptor GS_TRC_ID_PACK(COMP_EXECUTER, 14)
#define GS_TRC_ID_ExecFindJunkPrimaryKeys GS_TRC_ID_PACK(COMP_EXECUTER, 15)
#define GS_TRC_ID_BatchExecFilterJunk GS_TRC_ID_PACK(COMP_EXECUTER, 16)
#define GS_TRC_ID_BatchCheckNodeIdentifier GS_TRC_ID_PACK(COMP_EXECUTER, 17)
#define GS_TRC_ID_ExecGetPlanNodeid GS_TRC_ID_PACK(COMP_EXECUTER, 18)
#define GS_TRC_ID_ExecutorStart GS_TRC_ID_PACK(COMP_EXECUTER, 19)
#define GS_TRC_ID_standard_ExecutorStart GS_TRC_ID_PACK(COMP_EXECUTER, 20)
#define GS_TRC_ID_ExecutorRun GS_TRC_ID_PACK(COMP_EXECUTER, 21)
#define GS_TRC_ID_standard_ExecutorRun GS_TRC_ID_PACK(COMP_EXECUTER, 22)
#define GS_TRC_ID_ExecutorFinish GS_TRC_ID_PACK(COMP_EXECUTER, 23)
#define GS_TRC_ID_standard_ExecutorFinish GS_TRC_ID_PACK(COMP_EXECUTER, 24)
#define GS_TRC_ID_ExecutorEnd GS_TRC_ID_PACK(COMP_EXECUTER, 25)
#define GS_TRC_ID_standard_ExecutorEnd GS_TRC_ID_PACK(COMP_EXECUTER, 26)
#define GS_TRC_ID_ExecutorRewind GS_TRC_ID_PACK(COMP_EXECUTER, 27)
#define GS_TRC_ID_ExecCheckRTPerms GS_TRC_ID_PACK(COMP_EXECUTER, 28)
#define GS_TRC_ID_CheckValidResultRel GS_TRC_ID_PACK(COMP_EXECUTER, 29)
#define GS_TRC_ID_InitResultRelInfo GS_TRC_ID_PACK(COMP_EXECUTER, 30)
#define GS_TRC_ID_ExecGetTriggerResultRel GS_TRC_ID_PACK(COMP_EXECUTER, 31)
#define GS_TRC_ID_ExecContextForcesOids GS_TRC_ID_PACK(COMP_EXECUTER, 32)
#define GS_TRC_ID_ExecConstraints GS_TRC_ID_PACK(COMP_EXECUTER, 33)
#define GS_TRC_ID_ExecFindRowMark GS_TRC_ID_PACK(COMP_EXECUTER, 34)
#define GS_TRC_ID_ExecBuildAuxRowMark GS_TRC_ID_PACK(COMP_EXECUTER, 35)
#define GS_TRC_ID_EvalPlanQual GS_TRC_ID_PACK(COMP_EXECUTER, 36)
#define GS_TRC_ID_EvalPlanQualFetch GS_TRC_ID_PACK(COMP_EXECUTER, 37)
#define GS_TRC_ID_EvalPlanQualInit GS_TRC_ID_PACK(COMP_EXECUTER, 38)
#define GS_TRC_ID_EvalPlanQualSetPlan GS_TRC_ID_PACK(COMP_EXECUTER, 39)
#define GS_TRC_ID_EvalPlanQualSetTuple GS_TRC_ID_PACK(COMP_EXECUTER, 40)
#define GS_TRC_ID_EvalPlanQualGetTuple GS_TRC_ID_PACK(COMP_EXECUTER, 41)
#define GS_TRC_ID_EvalPlanQualFetchRowMarks GS_TRC_ID_PACK(COMP_EXECUTER, 42)
#define GS_TRC_ID_EvalPlanQualNext GS_TRC_ID_PACK(COMP_EXECUTER, 43)
#define GS_TRC_ID_EvalPlanQualBegin GS_TRC_ID_PACK(COMP_EXECUTER, 44)
#define GS_TRC_ID_EvalPlanQualEnd GS_TRC_ID_PACK(COMP_EXECUTER, 45)
#define GS_TRC_ID_ExecInitNode GS_TRC_ID_PACK(COMP_EXECUTER, 46)
#define GS_TRC_ID_ExecProcNode GS_TRC_ID_PACK(COMP_EXECUTER, 47)
#define GS_TRC_ID_MultiExecProcNode GS_TRC_ID_PACK(COMP_EXECUTER, 48)
#define GS_TRC_ID_ExecEndNode GS_TRC_ID_PACK(COMP_EXECUTER, 49)
#define GS_TRC_ID_ExecGetPlanMemCost GS_TRC_ID_PACK(COMP_EXECUTER, 50)
#define GS_TRC_ID_GetAttributeByNum GS_TRC_ID_PACK(COMP_EXECUTER, 51)
#define GS_TRC_ID_GetAttributeByName GS_TRC_ID_PACK(COMP_EXECUTER, 52)
#define GS_TRC_ID_ExecMakeTableFunctionResult GS_TRC_ID_PACK(COMP_EXECUTER, 53)
#define GS_TRC_ID_ExecEvalExprSwitchContext GS_TRC_ID_PACK(COMP_EXECUTER, 54)
#define GS_TRC_ID_ExecInitExpr GS_TRC_ID_PACK(COMP_EXECUTER, 55)
#define GS_TRC_ID_ExecPrepareExpr GS_TRC_ID_PACK(COMP_EXECUTER, 56)
#define GS_TRC_ID_ExecQual GS_TRC_ID_PACK(COMP_EXECUTER, 57)
#define GS_TRC_ID_ExecTargetListLength GS_TRC_ID_PACK(COMP_EXECUTER, 58)
#define GS_TRC_ID_ExecCleanTargetListLength GS_TRC_ID_PACK(COMP_EXECUTER, 59)
#define GS_TRC_ID_ExecProject GS_TRC_ID_PACK(COMP_EXECUTER, 60)
#define GS_TRC_ID_ExecScan GS_TRC_ID_PACK(COMP_EXECUTER, 61)
#define GS_TRC_ID_ExecAssignScanProjectionInfo GS_TRC_ID_PACK(COMP_EXECUTER, 62)
#define GS_TRC_ID_ExecScanReScan GS_TRC_ID_PACK(COMP_EXECUTER, 63)
#define GS_TRC_ID_ExecInitResultTupleSlot GS_TRC_ID_PACK(COMP_EXECUTER, 64)
#define GS_TRC_ID_ExecInitScanTupleSlot GS_TRC_ID_PACK(COMP_EXECUTER, 65)
#define GS_TRC_ID_ExecInitExtraTupleSlot GS_TRC_ID_PACK(COMP_EXECUTER, 66)
#define GS_TRC_ID_ExecInitNullTupleSlot GS_TRC_ID_PACK(COMP_EXECUTER, 67)
#define GS_TRC_ID_ExecTypeFromTL GS_TRC_ID_PACK(COMP_EXECUTER, 68)
#define GS_TRC_ID_ExecCleanTypeFromTL GS_TRC_ID_PACK(COMP_EXECUTER, 69)
#define GS_TRC_ID_ExecTypeFromExprList GS_TRC_ID_PACK(COMP_EXECUTER, 70)
#define GS_TRC_ID_UpdateChangedParamSet GS_TRC_ID_PACK(COMP_EXECUTER, 71)
#define GS_TRC_ID_begin_tup_output_tupdesc GS_TRC_ID_PACK(COMP_EXECUTER, 72)
#define GS_TRC_ID_do_tup_output GS_TRC_ID_PACK(COMP_EXECUTER, 73)
#define GS_TRC_ID_do_text_output_multiline GS_TRC_ID_PACK(COMP_EXECUTER, 74)
#define GS_TRC_ID_end_tup_output GS_TRC_ID_PACK(COMP_EXECUTER, 75)
#define GS_TRC_ID_InitPlan GS_TRC_ID_PACK(COMP_EXECUTER, 76)
#define GS_TRC_ID_ExecCheckRTEPerms GS_TRC_ID_PACK(COMP_EXECUTER, 77)
#define GS_TRC_ID_ExecInitIndexScan GS_TRC_ID_PACK(COMP_EXECUTER, 78)
#define GS_TRC_ID_BypassExecutor GS_TRC_ID_PACK(COMP_EXECUTER, 79)
#define GS_TRC_ID_UheapgettupPagemode GS_TRC_ID_PACK(COMP_EXECUTER, 80)
#define GS_TRC_ID_Uheapgetpage GS_TRC_ID_PACK(COMP_EXECUTER, 81)

#endif