// This is a generated file

#ifndef _OPTIMIZER_GSTRACE_H
#define _OPTIMIZER_GSTRACE_H

#include "comps.h"
#include "gstrace_infra.h"

#define GS_TRC_ID_clauselist_selectivity GS_TRC_ID_PACK(COMP_OPTIMIZER, 1)
#define GS_TRC_ID_clause_selectivity GS_TRC_ID_PACK(COMP_OPTIMIZER, 2)
#define GS_TRC_ID_set_rel_width GS_TRC_ID_PACK(COMP_OPTIMIZER, 3)
#define GS_TRC_ID_restore_hashjoin_cost GS_TRC_ID_PACK(COMP_OPTIMIZER, 4)
#define GS_TRC_ID_finalize_dml_cost GS_TRC_ID_PACK(COMP_OPTIMIZER, 5)
#define GS_TRC_ID_copy_mem_info GS_TRC_ID_PACK(COMP_OPTIMIZER, 6)
#define GS_TRC_ID_columnar_get_col_width GS_TRC_ID_PACK(COMP_OPTIMIZER, 7)
#define GS_TRC_ID_get_path_actual_total_width GS_TRC_ID_PACK(COMP_OPTIMIZER, 8)
#define GS_TRC_ID_query_planner GS_TRC_ID_PACK(COMP_OPTIMIZER, 9)
#define GS_TRC_ID_preprocess_minmax_aggregates GS_TRC_ID_PACK(COMP_OPTIMIZER, 10)
#define GS_TRC_ID_optimize_minmax_aggregates GS_TRC_ID_PACK(COMP_OPTIMIZER, 11)
#define GS_TRC_ID_set_plan_rows GS_TRC_ID_PACK(COMP_OPTIMIZER, 12)
#define GS_TRC_ID_create_plan GS_TRC_ID_PACK(COMP_OPTIMIZER, 13)
#define GS_TRC_ID_disuse_physical_tlist GS_TRC_ID_PACK(COMP_OPTIMIZER, 14)
#define GS_TRC_ID_copy_plan_costsize GS_TRC_ID_PACK(COMP_OPTIMIZER, 15)
#define GS_TRC_ID_make_subqueryscan GS_TRC_ID_PACK(COMP_OPTIMIZER, 16)
#define GS_TRC_ID_make_foreignscan GS_TRC_ID_PACK(COMP_OPTIMIZER, 17)
#define GS_TRC_ID_make_append GS_TRC_ID_PACK(COMP_OPTIMIZER, 18)
#define GS_TRC_ID_make_recursive_union GS_TRC_ID_PACK(COMP_OPTIMIZER, 19)
#define GS_TRC_ID_make_sort_from_pathkeys GS_TRC_ID_PACK(COMP_OPTIMIZER, 20)
#define GS_TRC_ID_make_sort_from_sortclauses GS_TRC_ID_PACK(COMP_OPTIMIZER, 21)
#define GS_TRC_ID_make_sort_from_groupcols GS_TRC_ID_PACK(COMP_OPTIMIZER, 22)
#define GS_TRC_ID_make_sort_from_targetlist GS_TRC_ID_PACK(COMP_OPTIMIZER, 23)
#define GS_TRC_ID_make_sort GS_TRC_ID_PACK(COMP_OPTIMIZER, 24)
#define GS_TRC_ID_make_agg GS_TRC_ID_PACK(COMP_OPTIMIZER, 25)
#define GS_TRC_ID_make_windowagg GS_TRC_ID_PACK(COMP_OPTIMIZER, 26)
#define GS_TRC_ID_make_group GS_TRC_ID_PACK(COMP_OPTIMIZER, 27)
#define GS_TRC_ID_materialize_finished_plan GS_TRC_ID_PACK(COMP_OPTIMIZER, 28)
#define GS_TRC_ID_make_unique GS_TRC_ID_PACK(COMP_OPTIMIZER, 29)
#define GS_TRC_ID_make_lockrows GS_TRC_ID_PACK(COMP_OPTIMIZER, 30)
#define GS_TRC_ID_make_limit GS_TRC_ID_PACK(COMP_OPTIMIZER, 31)
#define GS_TRC_ID_make_stream_limit GS_TRC_ID_PACK(COMP_OPTIMIZER, 32)
#define GS_TRC_ID_compare_path_costs GS_TRC_ID_PACK(COMP_OPTIMIZER, 33)
#define GS_TRC_ID_compare_fractional_path_costs GS_TRC_ID_PACK(COMP_OPTIMIZER, 34)
#define GS_TRC_ID_set_cheapest GS_TRC_ID_PACK(COMP_OPTIMIZER, 35)
#define GS_TRC_ID_get_cheapest_path GS_TRC_ID_PACK(COMP_OPTIMIZER, 36)
#define GS_TRC_ID_find_hinted_path GS_TRC_ID_PACK(COMP_OPTIMIZER, 37)
#define GS_TRC_ID_add_path GS_TRC_ID_PACK(COMP_OPTIMIZER, 38)
#define GS_TRC_ID_add_path_precheck GS_TRC_ID_PACK(COMP_OPTIMIZER, 39)
#define GS_TRC_ID_create_seqscan_path GS_TRC_ID_PACK(COMP_OPTIMIZER, 40)
#define GS_TRC_ID_create_cstorescan_path GS_TRC_ID_PACK(COMP_OPTIMIZER, 41)
#define GS_TRC_ID_create_index_path GS_TRC_ID_PACK(COMP_OPTIMIZER, 42)
#define GS_TRC_ID_build_seqScanPath_by_indexScanPath GS_TRC_ID_PACK(COMP_OPTIMIZER, 43)
#define GS_TRC_ID_check_bitmap_heap_path_index_unusable GS_TRC_ID_PACK(COMP_OPTIMIZER, 44)
#define GS_TRC_ID_is_partitionIndex_Subpath GS_TRC_ID_PACK(COMP_OPTIMIZER, 45)
#define GS_TRC_ID_is_pwj_path GS_TRC_ID_PACK(COMP_OPTIMIZER, 46)
#define GS_TRC_ID_create_bitmap_heap_path GS_TRC_ID_PACK(COMP_OPTIMIZER, 47)

#endif