// This is a generated file

#ifndef _POSTMASTER_GSTRACE_H
#define _POSTMASTER_GSTRACE_H

#include "comps.h"
#include "gstrace_infra.h"

#define GS_TRC_ID_PostmasterMain GS_TRC_ID_PACK(COMP_POSTMASTER, 1)
#define GS_TRC_ID_ClosePostmasterPorts GS_TRC_ID_PACK(COMP_POSTMASTER, 2)
#define GS_TRC_ID_MaxLivePostmasterChildren GS_TRC_ID_PACK(COMP_POSTMASTER, 3)
#define GS_TRC_ID_HaShmemSize GS_TRC_ID_PACK(COMP_POSTMASTER, 4)
#define GS_TRC_ID_HaShmemInit GS_TRC_ID_PACK(COMP_POSTMASTER, 5)
#define GS_TRC_ID_postmaster_forkexec GS_TRC_ID_PACK(COMP_POSTMASTER, 6)
#define GS_TRC_ID_stream_forkexec GS_TRC_ID_PACK(COMP_POSTMASTER, 7)
#define GS_TRC_ID_WLMProcessForkExec GS_TRC_ID_PACK(COMP_POSTMASTER, 8)
#define GS_TRC_ID_SubPostmasterMain GS_TRC_ID_PACK(COMP_POSTMASTER, 9)
#define GS_TRC_ID_ShmemBackendArraySize GS_TRC_ID_PACK(COMP_POSTMASTER, 10)
#define GS_TRC_ID_ShmemBackendArrayAllocation GS_TRC_ID_PACK(COMP_POSTMASTER, 11)
#define GS_TRC_ID_SysLogger_Start GS_TRC_ID_PACK(COMP_POSTMASTER, 12)
#define GS_TRC_ID_SysLoggerClose GS_TRC_ID_PACK(COMP_POSTMASTER, 13)
#define GS_TRC_ID_write_syslogger_file GS_TRC_ID_PACK(COMP_POSTMASTER, 14)
#define GS_TRC_ID_AioCompltrMain GS_TRC_ID_PACK(COMP_POSTMASTER, 15)
#define GS_TRC_ID_AioCompltrStop GS_TRC_ID_PACK(COMP_POSTMASTER, 16)
#define GS_TRC_ID_AioCompltrStart GS_TRC_ID_PACK(COMP_POSTMASTER, 17)
#define GS_TRC_ID_AioCompltrIsReady GS_TRC_ID_PACK(COMP_POSTMASTER, 18)
#define GS_TRC_ID_CompltrContext GS_TRC_ID_PACK(COMP_POSTMASTER, 19)
#define GS_TRC_ID_CompltrPriority GS_TRC_ID_PACK(COMP_POSTMASTER, 20)
#define GS_TRC_ID_AutoVacuumingActive GS_TRC_ID_PACK(COMP_POSTMASTER, 21)
#define GS_TRC_ID_IsAutoVacuumLauncherProcess GS_TRC_ID_PACK(COMP_POSTMASTER, 22)
#define GS_TRC_ID_IsAutoVacuumWorkerProcess GS_TRC_ID_PACK(COMP_POSTMASTER, 23)
#define GS_TRC_ID_autovac_init GS_TRC_ID_PACK(COMP_POSTMASTER, 24)
#define GS_TRC_ID_StartAutoVacLauncher GS_TRC_ID_PACK(COMP_POSTMASTER, 25)
#define GS_TRC_ID_StartAutoVacWorker GS_TRC_ID_PACK(COMP_POSTMASTER, 26)
#define GS_TRC_ID_AutoVacWorkerFailed GS_TRC_ID_PACK(COMP_POSTMASTER, 27)
#define GS_TRC_ID_AutoVacuumUpdateDelay GS_TRC_ID_PACK(COMP_POSTMASTER, 28)
#define GS_TRC_ID_AutoVacLauncherMain GS_TRC_ID_PACK(COMP_POSTMASTER, 29)
#define GS_TRC_ID_AutoVacWorkerMain GS_TRC_ID_PACK(COMP_POSTMASTER, 30)
#define GS_TRC_ID_AutovacuumWorkerIAm GS_TRC_ID_PACK(COMP_POSTMASTER, 31)
#define GS_TRC_ID_AutovacuumLauncherIAm GS_TRC_ID_PACK(COMP_POSTMASTER, 32)
#define GS_TRC_ID_HandleStartupProcInterrupts GS_TRC_ID_PACK(COMP_POSTMASTER, 33)
#define GS_TRC_ID_StartupProcessMain GS_TRC_ID_PACK(COMP_POSTMASTER, 34)
#define GS_TRC_ID_PreRestoreCommand GS_TRC_ID_PACK(COMP_POSTMASTER, 35)
#define GS_TRC_ID_PostRestoreCommand GS_TRC_ID_PACK(COMP_POSTMASTER, 36)
#define GS_TRC_ID_IsFailoverTriggered GS_TRC_ID_PACK(COMP_POSTMASTER, 37)
#define GS_TRC_ID_IsSwitchoverTriggered GS_TRC_ID_PACK(COMP_POSTMASTER, 38)
#define GS_TRC_ID_IsPrimaryTriggered GS_TRC_ID_PACK(COMP_POSTMASTER, 39)
#define GS_TRC_ID_ResetSwitchoverTriggered GS_TRC_ID_PACK(COMP_POSTMASTER, 40)
#define GS_TRC_ID_ResetFailoverTriggered GS_TRC_ID_PACK(COMP_POSTMASTER, 41)
#define GS_TRC_ID_ResetPrimaryTriggered GS_TRC_ID_PACK(COMP_POSTMASTER, 42)
#define GS_TRC_ID_NotifySignalShmemSize GS_TRC_ID_PACK(COMP_POSTMASTER, 43)
#define GS_TRC_ID_NotifySignalShmemInit GS_TRC_ID_PACK(COMP_POSTMASTER, 44)
#define GS_TRC_ID_SendNotifySignal GS_TRC_ID_PACK(COMP_POSTMASTER, 45)
#define GS_TRC_ID_CheckNotifySignal GS_TRC_ID_PACK(COMP_POSTMASTER, 46)
#define GS_TRC_ID_BackgroundWriterMain GS_TRC_ID_PACK(COMP_POSTMASTER, 47)
#define GS_TRC_ID_CheckpointerMain GS_TRC_ID_PACK(COMP_POSTMASTER, 48)
#define GS_TRC_ID_RequestCheckpoint GS_TRC_ID_PACK(COMP_POSTMASTER, 49)
#define GS_TRC_ID_CheckpointWriteDelay GS_TRC_ID_PACK(COMP_POSTMASTER, 50)
#define GS_TRC_ID_ForwardFsyncRequest GS_TRC_ID_PACK(COMP_POSTMASTER, 51)
#define GS_TRC_ID_AbsorbFsyncRequests GS_TRC_ID_PACK(COMP_POSTMASTER, 52)
#define GS_TRC_ID_CheckpointerShmemSize GS_TRC_ID_PACK(COMP_POSTMASTER, 53)
#define GS_TRC_ID_CheckpointerShmemInit GS_TRC_ID_PACK(COMP_POSTMASTER, 54)
#define GS_TRC_ID_FirstCallSinceLastCheckpoint GS_TRC_ID_PACK(COMP_POSTMASTER, 55)
#define GS_TRC_ID_IsBgwriterProcess GS_TRC_ID_PACK(COMP_POSTMASTER, 56)
#define GS_TRC_ID_isDirExist GS_TRC_ID_PACK(COMP_POSTMASTER, 57)
#define GS_TRC_ID_startAlarmChecker GS_TRC_ID_PACK(COMP_POSTMASTER, 58)
#define GS_TRC_ID_AlarmCheckerMain GS_TRC_ID_PACK(COMP_POSTMASTER, 59)
#define GS_TRC_ID_fork_process GS_TRC_ID_PACK(COMP_POSTMASTER, 60)
#define GS_TRC_ID_WalWriterMain GS_TRC_ID_PACK(COMP_POSTMASTER, 61)
#define GS_TRC_ID_ckpt_try_prune_dirty_page_queue GS_TRC_ID_PACK(COMP_POSTMASTER, 62)

#endif