// This is a generated file

#ifndef _TCOP_GSTRACE_H
#define _TCOP_GSTRACE_H

#include "comps.h"
#include "gstrace_infra.h"

#define GS_TRC_ID_BeginCommand GS_TRC_ID_PACK(COMP_TCOP, 1)
#define GS_TRC_ID_CreateDestReceiver GS_TRC_ID_PACK(COMP_TCOP, 2)
#define GS_TRC_ID_CreateReceiverForMerge GS_TRC_ID_PACK(COMP_TCOP, 3)
#define GS_TRC_ID_EndCommand GS_TRC_ID_PACK(COMP_TCOP, 4)
#define GS_TRC_ID_EndCommand_noblock GS_TRC_ID_PACK(COMP_TCOP, 5)
#define GS_TRC_ID_ProcessUtility GS_TRC_ID_PACK(COMP_TCOP, 6)
#define GS_TRC_ID_standard_ProcessUtility GS_TRC_ID_PACK(COMP_TCOP, 7)
#define GS_TRC_ID_UtilityReturnsTuples GS_TRC_ID_PACK(COMP_TCOP, 8)
#define GS_TRC_ID_UtilityTupleDescriptor GS_TRC_ID_PACK(COMP_TCOP, 9)
#define GS_TRC_ID_UtilityContainsQuery GS_TRC_ID_PACK(COMP_TCOP, 10)
#define GS_TRC_ID_CreateCommandTag GS_TRC_ID_PACK(COMP_TCOP, 11)
#define GS_TRC_ID_GetCommandLogLevel GS_TRC_ID_PACK(COMP_TCOP, 12)
#define GS_TRC_ID_CommandIsReadOnly GS_TRC_ID_PACK(COMP_TCOP, 13)
#define GS_TRC_ID_CheckRelationOwnership GS_TRC_ID_PACK(COMP_TCOP, 14)
#define GS_TRC_ID_pg_parse_query GS_TRC_ID_PACK(COMP_TCOP, 15)
#define GS_TRC_ID_pg_analyze_and_rewrite GS_TRC_ID_PACK(COMP_TCOP, 16)
#define GS_TRC_ID_pg_analyze_and_rewrite_params GS_TRC_ID_PACK(COMP_TCOP, 17)
#define GS_TRC_ID_pg_plan_query GS_TRC_ID_PACK(COMP_TCOP, 18)
#define GS_TRC_ID_pg_plan_queries GS_TRC_ID_PACK(COMP_TCOP, 19)
#define GS_TRC_ID_check_max_stack_depth GS_TRC_ID_PACK(COMP_TCOP, 20)
#define GS_TRC_ID_assign_max_stack_depth GS_TRC_ID_PACK(COMP_TCOP, 21)
#define GS_TRC_ID_die GS_TRC_ID_PACK(COMP_TCOP, 22)
#define GS_TRC_ID_quickdie GS_TRC_ID_PACK(COMP_TCOP, 23)
#define GS_TRC_ID_StatementCancelHandler GS_TRC_ID_PACK(COMP_TCOP, 24)
#define GS_TRC_ID_FloatExceptionHandler GS_TRC_ID_PACK(COMP_TCOP, 25)
#define GS_TRC_ID_RecoveryConflictInterrupt GS_TRC_ID_PACK(COMP_TCOP, 26)
#define GS_TRC_ID_prepare_for_client_read GS_TRC_ID_PACK(COMP_TCOP, 27)
#define GS_TRC_ID_client_read_ended GS_TRC_ID_PACK(COMP_TCOP, 28)
#define GS_TRC_ID_prepare_for_logic_conn_read GS_TRC_ID_PACK(COMP_TCOP, 29)
#define GS_TRC_ID_logic_conn_read_check_ended GS_TRC_ID_PACK(COMP_TCOP, 30)
#define GS_TRC_ID_process_postgres_switches GS_TRC_ID_PACK(COMP_TCOP, 31)
#define GS_TRC_ID_PostgresMain GS_TRC_ID_PACK(COMP_TCOP, 32)
#define GS_TRC_ID_StreamMain GS_TRC_ID_PACK(COMP_TCOP, 33)
#define GS_TRC_ID_get_stack_depth_rlimit GS_TRC_ID_PACK(COMP_TCOP, 34)
#define GS_TRC_ID_ResetUsage GS_TRC_ID_PACK(COMP_TCOP, 35)
#define GS_TRC_ID_ShowUsage GS_TRC_ID_PACK(COMP_TCOP, 36)
#define GS_TRC_ID_check_log_duration GS_TRC_ID_PACK(COMP_TCOP, 37)
#define GS_TRC_ID_set_debug_options GS_TRC_ID_PACK(COMP_TCOP, 38)
#define GS_TRC_ID_set_plan_disabling_options GS_TRC_ID_PACK(COMP_TCOP, 39)
#define GS_TRC_ID_get_stats_option_name GS_TRC_ID_PACK(COMP_TCOP, 40)
#define GS_TRC_ID_exec_parse_message GS_TRC_ID_PACK(COMP_TCOP, 41)
#define GS_TRC_ID_exec_bind_message GS_TRC_ID_PACK(COMP_TCOP, 42)
#define GS_TRC_ID_exec_execute_message GS_TRC_ID_PACK(COMP_TCOP, 43)
#define GS_TRC_ID_PortalStart GS_TRC_ID_PACK(COMP_TCOP, 44)
#define GS_TRC_ID_PortalRun GS_TRC_ID_PACK(COMP_TCOP, 45)

#endif