#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for gpopt
#
#-------------------------------------------------------------------------
subdir = src/spq_optimizer_util/utils
top_builddir = ../../../../..
include $(top_builddir)/src/Makefile.global
include ../spq_optimizer_util.mk

OBJS = COptTasks.o CConstExprEvaluatorProxy.o CMemoryPoolPalloc.o CMemoryPoolPallocManager.o funcs.o

include $(top_srcdir)/src/gausskernel/common.mk