drop database if exists mysqllock;
create database mysqllock dbcompatibility 'b';
\c mysqllock
create extension dolphin;
select get_lock('aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',1);
select get_lock('aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',1);

select get_lock('获取一个锁2022',1);

select get_lock('1234567890',1);
select get_lock(1,1);
select get_lock(1234567890,1);

select get_lock('`',1);
select get_lock('~',1);
select get_lock('!',1);
select get_lock('@',1);
select get_lock('#',1);
select get_lock('$',1);
select get_lock('%',1);
select get_lock('^',1);
select get_lock('&',1);
select get_lock('*',1);
select get_lock('(',1);
select get_lock(')',1);
select get_lock('[',1);
select get_lock(']',1);
select get_lock('{',1);
select get_lock('}',1);
select get_lock('-',1);
select get_lock('_',1);
select get_lock('=',1);
select get_lock('+',1);
select get_lock('\',1);
select get_lock('|',1);
select get_lock(';',1);
select get_lock(':',1);
select get_lock('""""',1);
select get_lock(',',1);
select get_lock('.',1);
select get_lock('/',1);
select get_lock('<',1);
select get_lock('>',1);
select get_lock('?',1);

select get_lock('·',1);
select get_lock('~',1);
select get_lock('！',1);
select get_lock('@',1);
select get_lock('#',1);
select get_lock('￥',1);
select get_lock('%',1);
select get_lock('……',1);
select get_lock('&',1);
select get_lock('*',1);
select get_lock('（',1);
select get_lock('）',1);
select get_lock('-',1);
select get_lock('——',1);
select get_lock('=',1);
select get_lock('+',1);
select get_lock('【',1);
select get_lock('】',1);
select get_lock('{',1);
select get_lock('}',1);
select get_lock('、',1);
select get_lock('|',1);
select get_lock('；',1);
select get_lock('：',1);
select get_lock('‘',1);
select get_lock('“',1);
select get_lock('”',1);
select get_lock('，',1);
select get_lock('《',1);
select get_lock('。',1);
select get_lock('》',1);
select get_lock('/',1);
select get_lock('？',1);

select get_lock('a                                                             a');
select get_lock('a                                                              a');
select get_lock('1                                                              1');
select get_lock('a                                                              1');
select get_lock(' ');

select is_free_lock('aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa');
select is_free_lock('aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa');
select is_free_lock('获取一个锁2022');

select is_free_lock('1234567890');
select is_free_lock(1);
select is_free_lock(1234567890);

select is_free_lock('`');
select is_free_lock('~');
select is_free_lock('!');
select is_free_lock('@');
select is_free_lock('#');
select is_free_lock('$');
select is_free_lock('%');
select is_free_lock('^');
select is_free_lock('&');
select is_free_lock('*');
select is_free_lock('(');
select is_free_lock(')');
select is_free_lock('[');
select is_free_lock(']');
select is_free_lock('{');
select is_free_lock('}');
select is_free_lock('-');
select is_free_lock('_');
select is_free_lock('=');
select is_free_lock('+');
select is_free_lock('\');
select is_free_lock('|');
select is_free_lock(';');
select is_free_lock(':');
select is_free_lock('""""');
select is_free_lock(',');
select is_free_lock('.');
select is_free_lock('/');
select is_free_lock('<');
select is_free_lock('>');
select is_free_lock('?');

select is_free_lock('·');
select is_free_lock('~');
select is_free_lock('！');
select is_free_lock('@');
select is_free_lock('#');
select is_free_lock('￥');
select is_free_lock('%');
select is_free_lock('……');
select is_free_lock('&');
select is_free_lock('*');
select is_free_lock('（');
select is_free_lock('）');
select is_free_lock('-');
select is_free_lock('——');
select is_free_lock('=');
select is_free_lock('+');
select is_free_lock('【');
select is_free_lock('】');
select is_free_lock('{');
select is_free_lock('}');
select is_free_lock('、');
select is_free_lock('|');
select is_free_lock('；');
select is_free_lock('：');
select is_free_lock('‘');
select is_free_lock('“');
select is_free_lock('”');
select is_free_lock('，');
select is_free_lock('《');
select is_free_lock('。');
select is_free_lock('》');
select is_free_lock('/');
select is_free_lock('？');

select is_free_lock('a                                                             a');
select is_free_lock('a                                                              a');
select is_free_lock('1                                                              1');
select is_free_lock('a                                                              1');
select is_free_lock(' ');
\c postgres
drop database if exists mysqllock;
