#
# Makefile for optimizer
#
# src/spq_optimizer/libspqopt/src/translate/Makefile
#
subdir = src/spq_optimizer/libspqopt/src/translate
top_builddir = ../../../../../../..
include $(top_builddir)/src/Makefile.global
include ../../../spqorca.mk

OBJS = CTranslatorDXLToExpr.o \
       CTranslatorDXLToExprUtils.o \
       CTranslatorExprToDXL.o \
       CTranslatorExprToDXLUtils.o

include $(top_srcdir)/src/gausskernel/common.mk