language: c
os: linux
dist: bionic
arch: amd64
jobs:
  include:
  - name: PostgreSQL 11
    compiler: gcc
    addons:
      apt:
        packages:
        - postgresql-11
        - postgresql-server-dev-11
    script:
    - sudo make install -j$(nproc)
    - make installcheck
    after_failure: cat regress/regression.diffs
