#
# Makefile for optimizer
#
# src/spq_optimizer/libspqopt/src/minidump/Makefile
#
subdir = src/spq_optimizer/libspqopt/src/minidump
top_builddir = ../../../../../../..
include $(top_builddir)/src/Makefile.global
include ../../../spqorca.mk

OBJS = CDXLMinidump.o \
       CMetadataAccessorFactory.o \
       CMiniDumperDXL.o \
       CMinidumperUtils.o \
       CSerializableMDAccessor.o \
       CSerializableOptimizerConfig.o \
       CSerializablePlan.o \
       CSerializableQuery.o \
       CSerializableStackTrace.o

include $(top_srcdir)/src/gausskernel/common.mk