DROP OPERATOR CLASS IF EXISTS pg_catalog.enumtext_ops USING hash;

DROP FUNCTION IF EXISTS pg_catalog.nvarchar2_cast_int8(nvarchar2);
DROP FUNCTION IF EXISTS pg_catalog.nvarchar2_enum(nvarchar2, int4, anyelement);
DROP FUNCTION IF EXISTS pg_catalog.nvarchar2_cast_ui8(nvarchar2);
DROP FUNCTION IF EXISTS pg_catalog.nvarchar2_cast_ui4(nvarchar2);
DROP FUNCTION IF EXISTS pg_catalog.nvarchar2_cast_ui2(nvarchar2);
DROP FUNCTION IF EXISTS pg_catalog.nvarchar2_cast_ui1(nvarchar2);

DROP FUNCTION IF EXISTS pg_catalog.dolphin_invoke();
CREATE FUNCTION pg_catalog.dolphin_invoke()
    RETURNS VOID AS '$libdir/dolphin','dolphin_invoke' LANGUAGE C STRICT;

DROP FUNCTION IF EXISTS pg_catalog.rand(int16);
DROP FUNCTION IF EXISTS pg_catalog.rand(uint4);
DROP FUNCTION IF EXISTS pg_catalog.rand(timestamp with time zone);
DROP FUNCTION IF EXISTS pg_catalog.rand(date);
DROP FUNCTION IF EXISTS pg_catalog.rand(year);
DROP FUNCTION IF EXISTS pg_catalog.rand(binary);
DROP FUNCTION IF EXISTS pg_catalog.rand(blob);
DROP FUNCTION IF EXISTS pg_catalog.rand(anyenum);
DROP FUNCTION IF EXISTS pg_catalog.rand(anyset);
DROP FUNCTION IF EXISTS pg_catalog.rand(json);

DROP FUNCTION IF EXISTS pg_catalog.random_bytes(int4);
DROP FUNCTION IF EXISTS pg_catalog.random_bytes(bit);
DROP FUNCTION IF EXISTS pg_catalog.random_bytes(timestamp with time zone);
DROP FUNCTION IF EXISTS pg_catalog.random_bytes(date);
DROP FUNCTION IF EXISTS pg_catalog.random_bytes(year);
DROP FUNCTION IF EXISTS pg_catalog.random_bytes(binary);
DROP FUNCTION IF EXISTS pg_catalog.random_bytes(blob);
DROP FUNCTION IF EXISTS pg_catalog.random_bytes(anyenum);
DROP FUNCTION IF EXISTS pg_catalog.random_bytes(anyset);
DROP FUNCTION IF EXISTS pg_catalog.random_bytes(json);

DROP FUNCTION IF EXISTS pg_catalog.dayofmonth(text);
DROP FUNCTION IF EXISTS pg_catalog.dayofmonth(numeric);

drop function IF EXISTS pg_catalog."user"();

DROP FUNCTION IF EXISTS pg_catalog.log2(uint1);
DROP FUNCTION IF EXISTS pg_catalog.log2(uint2);
DROP FUNCTION IF EXISTS pg_catalog.log2(uint4);
DROP FUNCTION IF EXISTS pg_catalog.log2(uint8);
DROP FUNCTION IF EXISTS pg_catalog.log2(numeric);
CREATE OR REPLACE FUNCTION pg_catalog.log2(numeric)
RETURNS numeric
AS
$$
BEGIN
    IF $1 <= 0 THEN
        RETURN NULL;
    end if;
    RETURN (SELECT log(2, $1));
END;
$$
LANGUAGE plpgsql;
DROP FUNCTION IF EXISTS pg_catalog.log2(bit);
DROP FUNCTION IF EXISTS pg_catalog.log2(boolean);
DROP FUNCTION IF EXISTS pg_catalog.log2(text);
DROP FUNCTION IF EXISTS pg_catalog.log2(char);
DROP FUNCTION IF EXISTS pg_catalog.log2(varchar);

DROP FUNCTION IF EXISTS pg_catalog.log10(uint1);
DROP FUNCTION IF EXISTS pg_catalog.log10(uint2);
DROP FUNCTION IF EXISTS pg_catalog.log10(uint4);
DROP FUNCTION IF EXISTS pg_catalog.log10(uint8);
DROP FUNCTION IF EXISTS pg_catalog.log10(numeric);
CREATE OR REPLACE FUNCTION pg_catalog.log10(numeric)
RETURNS numeric
AS
$$
BEGIN
    IF $1 <= 0 THEN
        RETURN NULL;
    end if;
    RETURN (SELECT log(10, $1));
END;
$$
LANGUAGE plpgsql;
DROP FUNCTION IF EXISTS pg_catalog.log10(bit);
DROP FUNCTION IF EXISTS pg_catalog.log10(boolean);
DROP FUNCTION IF EXISTS pg_catalog.log10(text);
DROP FUNCTION IF EXISTS pg_catalog.log10(char);
DROP FUNCTION IF EXISTS pg_catalog.log10(varchar);

DROP FUNCTION IF EXISTS pg_catalog.varlena_cast_int1(anyelement) CASCADE;
DROP FUNCTION IF EXISTS pg_catalog.varlena_cast_int2(anyelement) CASCADE;
DROP FUNCTION IF EXISTS pg_catalog.varlena_cast_int4(anyelement) CASCADE;

DROP CAST IF EXISTS (blob AS boolean);
DROP CAST IF EXISTS (tinyblob AS boolean);
DROP CAST IF EXISTS (mediumblob AS boolean);
DROP CAST IF EXISTS (longblob AS boolean);
DROP CAST IF EXISTS (anyset AS boolean);
DROP FUNCTION IF EXISTS pg_catalog.any2boolean(anyelement) CASCADE;
DROP FUNCTION IF EXISTS pg_catalog.enum_boolean(anyenum) CASCADE;
DROP FUNCTION IF EXISTS pg_catalog.set_boolean(anyset) CASCADE;

DROP OPERATOR IF EXISTS pg_catalog.=(year, tinyblob);
DROP OPERATOR IF EXISTS pg_catalog.=(tinyblob, year);
DROP OPERATOR IF EXISTS pg_catalog.<>(year, tinyblob);
DROP OPERATOR IF EXISTS pg_catalog.<>(tinyblob, year);
DROP OPERATOR IF EXISTS pg_catalog.>(year, tinyblob);
DROP OPERATOR IF EXISTS pg_catalog.>(tinyblob, year);
DROP OPERATOR IF EXISTS pg_catalog.<(year, tinyblob);
DROP OPERATOR IF EXISTS pg_catalog.<(tinyblob, year);
DROP OPERATOR IF EXISTS pg_catalog.>=(year, tinyblob);
DROP OPERATOR IF EXISTS pg_catalog.>=(tinyblob, year);
DROP OPERATOR IF EXISTS pg_catalog.<=(year, tinyblob);
DROP OPERATOR IF EXISTS pg_catalog.<=(tinyblob, year);
DROP FUNCTION IF EXISTS pg_catalog.year_tinyblob_eq(year, tinyblob);
DROP FUNCTION IF EXISTS pg_catalog.tinyblob_year_eq(tinyblob, year);
DROP FUNCTION IF EXISTS pg_catalog.year_tinyblob_ne(year, tinyblob);
DROP FUNCTION IF EXISTS pg_catalog.tinyblob_year_ne(tinyblob, year);
DROP FUNCTION IF EXISTS pg_catalog.year_tinyblob_gt(year, tinyblob);
DROP FUNCTION IF EXISTS pg_catalog.tinyblob_year_gt(tinyblob, year);
DROP FUNCTION IF EXISTS pg_catalog.year_tinyblob_lt(year, tinyblob);
DROP FUNCTION IF EXISTS pg_catalog.tinyblob_year_lt(tinyblob, year);
DROP FUNCTION IF EXISTS pg_catalog.year_tinyblob_ge(year, tinyblob);
DROP FUNCTION IF EXISTS pg_catalog.tinyblob_year_ge(tinyblob, year);
DROP FUNCTION IF EXISTS pg_catalog.year_tinyblob_le(year, tinyblob);
DROP FUNCTION IF EXISTS pg_catalog.tinyblob_year_le(tinyblob, year);

DROP OPERATOR IF EXISTS pg_catalog.=(year, mediumblob);
DROP OPERATOR IF EXISTS pg_catalog.=(mediumblob, year);
DROP OPERATOR IF EXISTS pg_catalog.<>(year, mediumblob);
DROP OPERATOR IF EXISTS pg_catalog.<>(mediumblob, year);
DROP OPERATOR IF EXISTS pg_catalog.>(year, mediumblob);
DROP OPERATOR IF EXISTS pg_catalog.>(mediumblob, year);
DROP OPERATOR IF EXISTS pg_catalog.<(year, mediumblob);
DROP OPERATOR IF EXISTS pg_catalog.<(mediumblob, year);
DROP OPERATOR IF EXISTS pg_catalog.>=(year, mediumblob);
DROP OPERATOR IF EXISTS pg_catalog.>=(mediumblob, year);
DROP OPERATOR IF EXISTS pg_catalog.<=(year, mediumblob);
DROP OPERATOR IF EXISTS pg_catalog.<=(mediumblob, year);
DROP FUNCTION IF EXISTS pg_catalog.year_mediumblob_eq(year, mediumblob);
DROP FUNCTION IF EXISTS pg_catalog.mediumblob_year_eq(mediumblob, year);
DROP FUNCTION IF EXISTS pg_catalog.year_mediumblob_ne(year, mediumblob);
DROP FUNCTION IF EXISTS pg_catalog.mediumblob_year_ne(mediumblob, year);
DROP FUNCTION IF EXISTS pg_catalog.year_mediumblob_gt(year, mediumblob);
DROP FUNCTION IF EXISTS pg_catalog.mediumblob_year_gt(mediumblob, year);
DROP FUNCTION IF EXISTS pg_catalog.year_mediumblob_lt(year, mediumblob);
DROP FUNCTION IF EXISTS pg_catalog.mediumblob_year_lt(mediumblob, year);
DROP FUNCTION IF EXISTS pg_catalog.year_mediumblob_ge(year, mediumblob);
DROP FUNCTION IF EXISTS pg_catalog.mediumblob_year_ge(mediumblob, year);
DROP FUNCTION IF EXISTS pg_catalog.year_mediumblob_le(year, mediumblob);
DROP FUNCTION IF EXISTS pg_catalog.mediumblob_year_le(mediumblob, year);

DROP OPERATOR IF EXISTS pg_catalog.=(year, blob);
DROP OPERATOR IF EXISTS pg_catalog.=(blob, year);
DROP OPERATOR IF EXISTS pg_catalog.<>(year, blob);
DROP OPERATOR IF EXISTS pg_catalog.<>(blob, year);
DROP OPERATOR IF EXISTS pg_catalog.>(year, blob);
DROP OPERATOR IF EXISTS pg_catalog.>(blob, year);
DROP OPERATOR IF EXISTS pg_catalog.<(year, blob);
DROP OPERATOR IF EXISTS pg_catalog.<(blob, year);
DROP OPERATOR IF EXISTS pg_catalog.>=(year, blob);
DROP OPERATOR IF EXISTS pg_catalog.>=(blob, year);
DROP OPERATOR IF EXISTS pg_catalog.<=(year, blob);
DROP OPERATOR IF EXISTS pg_catalog.<=(blob, year);
DROP FUNCTION IF EXISTS pg_catalog.year_blob_eq(year, blob);
DROP FUNCTION IF EXISTS pg_catalog.blob_year_eq(blob, year);
DROP FUNCTION IF EXISTS pg_catalog.year_blob_ne(year, blob);
DROP FUNCTION IF EXISTS pg_catalog.blob_year_ne(blob, year);
DROP FUNCTION IF EXISTS pg_catalog.year_blob_gt(year, blob);
DROP FUNCTION IF EXISTS pg_catalog.blob_year_gt(blob, year);
DROP FUNCTION IF EXISTS pg_catalog.year_blob_lt(year, blob);
DROP FUNCTION IF EXISTS pg_catalog.blob_year_lt(blob, year);
DROP FUNCTION IF EXISTS pg_catalog.year_blob_ge(year, blob);
DROP FUNCTION IF EXISTS pg_catalog.blob_year_ge(blob, year);
DROP FUNCTION IF EXISTS pg_catalog.year_blob_le(year, blob);
DROP FUNCTION IF EXISTS pg_catalog.blob_year_le(blob, year);

DROP OPERATOR IF EXISTS pg_catalog.=(year, longblob);
DROP OPERATOR IF EXISTS pg_catalog.=(longblob, year);
DROP OPERATOR IF EXISTS pg_catalog.<>(year, longblob);
DROP OPERATOR IF EXISTS pg_catalog.<>(longblob, year);
DROP OPERATOR IF EXISTS pg_catalog.>(year, longblob);
DROP OPERATOR IF EXISTS pg_catalog.>(longblob, year);
DROP OPERATOR IF EXISTS pg_catalog.<(year, longblob);
DROP OPERATOR IF EXISTS pg_catalog.<(longblob, year);
DROP OPERATOR IF EXISTS pg_catalog.>=(year, longblob);
DROP OPERATOR IF EXISTS pg_catalog.>=(longblob, year);
DROP OPERATOR IF EXISTS pg_catalog.<=(year, longblob);
DROP OPERATOR IF EXISTS pg_catalog.<=(longblob, year);
DROP FUNCTION IF EXISTS pg_catalog.year_longblob_eq(year, longblob);
DROP FUNCTION IF EXISTS pg_catalog.longblob_year_eq(longblob, year);
DROP FUNCTION IF EXISTS pg_catalog.year_longblob_ne(year, longblob);
DROP FUNCTION IF EXISTS pg_catalog.longblob_year_ne(longblob, year);
DROP FUNCTION IF EXISTS pg_catalog.year_longblob_gt(year, longblob);
DROP FUNCTION IF EXISTS pg_catalog.longblob_year_gt(longblob, year);
DROP FUNCTION IF EXISTS pg_catalog.year_longblob_lt(year, longblob);
DROP FUNCTION IF EXISTS pg_catalog.longblob_year_lt(longblob, year);
DROP FUNCTION IF EXISTS pg_catalog.year_longblob_ge(year, longblob);
DROP FUNCTION IF EXISTS pg_catalog.longblob_year_ge(longblob, year);
DROP FUNCTION IF EXISTS pg_catalog.year_longblob_le(year, longblob);
DROP FUNCTION IF EXISTS pg_catalog.longblob_year_le(longblob, year);

DROP OPERATOR IF EXISTS pg_catalog.=(int1, binary);
DROP FUNCTION IF EXISTS pg_catalog.int1_binary_eq(int1, binary);
DROP OPERATOR IF EXISTS pg_catalog.=(binary, int1);
DROP FUNCTION IF EXISTS pg_catalog.binary_int1_eq(binary, int1);
DROP OPERATOR IF EXISTS pg_catalog.<>(int1, binary);
DROP FUNCTION IF EXISTS pg_catalog.int1_binary_ne(int1, binary);
DROP OPERATOR IF EXISTS pg_catalog.<>(binary, int1);
DROP FUNCTION IF EXISTS pg_catalog.binary_int1_ne(binary, int1);

DROP OPERATOR IF EXISTS pg_catalog.=(text, binary);
DROP FUNCTION IF EXISTS pg_catalog.text_binary_eq(text, binary);
DROP OPERATOR IF EXISTS pg_catalog.=(binary, text);
DROP FUNCTION IF EXISTS pg_catalog.binary_text_eq(binary, text);

DROP FUNCTION IF EXISTS pg_catalog.to_days(bit);
DROP FUNCTION IF EXISTS pg_catalog.to_days(boolean);
DROP FUNCTION IF EXISTS pg_catalog.to_days(time);
DROP FUNCTION IF EXISTS pg_catalog.to_days(year);
DROP FUNCTION IF EXISTS pg_catalog.to_days(binary);
DROP FUNCTION IF EXISTS pg_catalog.to_days(blob);
DROP FUNCTION IF EXISTS pg_catalog.to_days(text);
DROP FUNCTION IF EXISTS pg_catalog.to_days(anyenum);
DROP FUNCTION IF EXISTS pg_catalog.to_days(anyset);
DROP FUNCTION IF EXISTS pg_catalog.to_days(json);

CREATE OR REPLACE FUNCTION pg_catalog.to_days(time) RETURNS int8 AS $$ SELECT pg_catalog.to_days(text_date('now') + $1)  $$ LANGUAGE SQL;

DROP FUNCTION pg_catalog.round(int1);
DROP FUNCTION pg_catalog.round(uint1);
DROP FUNCTION pg_catalog.round(int2);
DROP FUNCTION pg_catalog.round(uint2);
DROP FUNCTION pg_catalog.round(int4);
DROP FUNCTION pg_catalog.round(uint4);
DROP FUNCTION pg_catalog.round(int8);
DROP FUNCTION pg_catalog.round(uint8);
DROP FUNCTION pg_catalog.round(boolean);
DROP FUNCTION pg_catalog.round(year);

DROP FUNCTION pg_catalog.round(int1, int4);
DROP FUNCTION pg_catalog.round(uint1, int4);
DROP FUNCTION pg_catalog.round(int2, int4);
DROP FUNCTION pg_catalog.round(uint2, int4);
DROP FUNCTION pg_catalog.round(int4, int4);
DROP FUNCTION pg_catalog.round(uint4, int4);
DROP FUNCTION pg_catalog.round(int8, int4);
DROP FUNCTION pg_catalog.round(uint8, int4);
DROP FUNCTION pg_catalog.round(boolean, int4);
DROP FUNCTION pg_catalog.round(year, int4);
DROP FUNCTION pg_catalog.round(binary, int4);
DROP FUNCTION pg_catalog.round(json, int4);

DROP FUNCTION pg_catalog.round(int1, uint4);
DROP FUNCTION pg_catalog.round(uint1, uint4);
DROP FUNCTION pg_catalog.round(int2, uint4);
DROP FUNCTION pg_catalog.round(uint2, uint4);
DROP FUNCTION pg_catalog.round(int4, uint4);
DROP FUNCTION pg_catalog.round(uint4, uint4);
DROP FUNCTION pg_catalog.round(int8, uint4);
DROP FUNCTION pg_catalog.round(uint8, uint4);
DROP FUNCTION pg_catalog.round(boolean, uint4);
DROP FUNCTION pg_catalog.round(year, uint4);
DROP FUNCTION pg_catalog.round(binary, uint4);
DROP FUNCTION pg_catalog.round(json, uint4);

DROP FUNCTION pg_catalog.truncate(int1, int4);
DROP FUNCTION pg_catalog.truncate(uint1, int4);
DROP FUNCTION pg_catalog.truncate(int2, int4);
DROP FUNCTION pg_catalog.truncate(uint2, int4);
DROP FUNCTION pg_catalog.truncate(int4, int4);
DROP FUNCTION pg_catalog.truncate(uint4, int4);
DROP FUNCTION pg_catalog.truncate(int8, int4);
DROP FUNCTION pg_catalog.truncate(uint8, int4);
DROP FUNCTION pg_catalog.truncate(boolean, int4);
DROP FUNCTION pg_catalog.truncate(year, int4);
DROP FUNCTION pg_catalog.truncate(binary, int4);
DROP FUNCTION pg_catalog.truncate(json, int4);

DROP FUNCTION pg_catalog.truncate(int1, uint4);
DROP FUNCTION pg_catalog.truncate(uint1, uint4);
DROP FUNCTION pg_catalog.truncate(int2, uint4);
DROP FUNCTION pg_catalog.truncate(uint2, uint4);
DROP FUNCTION pg_catalog.truncate(int4, uint4);
DROP FUNCTION pg_catalog.truncate(uint4, uint4);
DROP FUNCTION pg_catalog.truncate(int8, uint4);
DROP FUNCTION pg_catalog.truncate(uint8, uint4);
DROP FUNCTION pg_catalog.truncate(boolean, uint4);
DROP FUNCTION pg_catalog.truncate(year, uint4);
DROP FUNCTION pg_catalog.truncate(binary, uint4);
DROP FUNCTION pg_catalog.truncate(json, uint4);

DROP FUNCTION IF EXISTS pg_catalog.lower(boolean);
DROP FUNCTION IF EXISTS pg_catalog.lower(bit);
DROP FUNCTION IF EXISTS pg_catalog.lower(tinyblob);
DROP FUNCTION IF EXISTS pg_catalog.lower(blob);
DROP FUNCTION IF EXISTS pg_catalog.lower(mediumblob);
DROP FUNCTION IF EXISTS pg_catalog.lower(longblob);
DROP FUNCTION IF EXISTS pg_catalog.lower(binary);
DROP FUNCTION IF EXISTS pg_catalog.lower(varbinary);
DROP FUNCTION IF EXISTS pg_catalog.lower(integer);
DROP FUNCTION IF EXISTS pg_catalog.lower(float);
DROP FUNCTION IF EXISTS pg_catalog.lower(char);
DROP FUNCTION IF EXISTS pg_catalog.lower(varchar);

DROP FUNCTION IF EXISTS pg_catalog.lcase(boolean);
DROP FUNCTION IF EXISTS pg_catalog.lcase(tinyblob);
DROP FUNCTION IF EXISTS pg_catalog.lcase(blob);
DROP FUNCTION IF EXISTS pg_catalog.lcase(mediumblob);
DROP FUNCTION IF EXISTS pg_catalog.lcase(longblob);
DROP FUNCTION IF EXISTS pg_catalog.lcase(bit);
DROP FUNCTION IF EXISTS pg_catalog.lcase(binary);
DROP FUNCTION IF EXISTS pg_catalog.lcase(varbinary);
DROP FUNCTION IF EXISTS pg_catalog.lcase(integer);
DROP FUNCTION IF EXISTS pg_catalog.lcase(float);
DROP FUNCTION IF EXISTS pg_catalog.lcase(char);
DROP FUNCTION IF EXISTS pg_catalog.lcase(varchar);

DROP OPERATOR IF EXISTS pg_catalog.=(int, uint2);
DROP FUNCTION IF EXISTS pg_catalog.int_uint2_eq(int, uint2);

DROP OPERATOR IF EXISTS pg_catalog.=(tinyblob, json);
DROP FUNCTION IF EXISTS pg_catalog.json_eq(tinyblob, json);
DROP OPERATOR IF EXISTS pg_catalog.=(blob, json);
DROP FUNCTION IF EXISTS pg_catalog.json_eq(blob, json);
DROP OPERATOR IF EXISTS pg_catalog.=(mediumblob, json);
DROP FUNCTION IF EXISTS pg_catalog.json_eq(mediumblob, json);
DROP OPERATOR IF EXISTS pg_catalog.=(longblob, json);
DROP FUNCTION IF EXISTS pg_catalog.json_eq(longblob, json);
DROP OPERATOR IF EXISTS pg_catalog.=(anyenum, json);
DROP FUNCTION IF EXISTS pg_catalog.json_eq(anyenum, json);

DROP OPERATOR IF EXISTS pg_catalog.=(tinyblob, numeric);
DROP OPERATOR IF EXISTS pg_catalog.=(numeric, tinyblob);
DROP OPERATOR IF EXISTS pg_catalog.<>(tinyblob, numeric);
DROP OPERATOR IF EXISTS pg_catalog.<>(numeric, tinyblob);
DROP OPERATOR IF EXISTS pg_catalog.<(tinyblob, numeric);
DROP OPERATOR IF EXISTS pg_catalog.<(numeric, tinyblob);
DROP OPERATOR IF EXISTS pg_catalog.<=(tinyblob, numeric);
DROP OPERATOR IF EXISTS pg_catalog.<=(numeric, tinyblob);
DROP OPERATOR IF EXISTS pg_catalog.>(tinyblob, numeric);
DROP OPERATOR IF EXISTS pg_catalog.>(numeric, tinyblob);
DROP OPERATOR IF EXISTS pg_catalog.>=(tinyblob, numeric);
DROP OPERATOR IF EXISTS pg_catalog.>=(numeric, tinyblob);
DROP FUNCTION IF EXISTS pg_catalog.tinyblob_numeric_eq(tinyblob, numeric);
DROP FUNCTION IF EXISTS pg_catalog.numeric_tinyblob_eq(numeric, tinyblob);
DROP FUNCTION IF EXISTS pg_catalog.tinyblob_numeric_ne(tinyblob, numeric);
DROP FUNCTION IF EXISTS pg_catalog.numeric_tinyblob_ne(numeric, tinyblob);
DROP FUNCTION IF EXISTS pg_catalog.tinyblob_numeric_lt(tinyblob, numeric);
DROP FUNCTION IF EXISTS pg_catalog.numeric_tinyblob_lt(numeric, tinyblob);
DROP FUNCTION IF EXISTS pg_catalog.tinyblob_numeric_le(tinyblob, numeric);
DROP FUNCTION IF EXISTS pg_catalog.numeric_tinyblob_le(numeric, tinyblob);
DROP FUNCTION IF EXISTS pg_catalog.tinyblob_numeric_gt(tinyblob, numeric);
DROP FUNCTION IF EXISTS pg_catalog.numeric_tinyblob_gt(numeric, tinyblob);
DROP FUNCTION IF EXISTS pg_catalog.tinyblob_numeric_ge(tinyblob, numeric);
DROP FUNCTION IF EXISTS pg_catalog.numeric_tinyblob_ge(numeric, tinyblob);
DROP FUNCTION IF EXISTS pg_catalog.tinyblob_numeric_cmp(tinyblob, numeric);
DROP FUNCTION IF EXISTS pg_catalog.numeric_tinyblob_cmp(numeric, tinyblob);
DROP OPERATOR IF EXISTS pg_catalog.=(blob, numeric);
DROP OPERATOR IF EXISTS pg_catalog.=(numeric, blob);
DROP OPERATOR IF EXISTS pg_catalog.<>(blob, numeric);
DROP OPERATOR IF EXISTS pg_catalog.<>(numeric, blob);
DROP OPERATOR IF EXISTS pg_catalog.<(blob, numeric);
DROP OPERATOR IF EXISTS pg_catalog.<(numeric, blob);
DROP OPERATOR IF EXISTS pg_catalog.<=(blob, numeric);
DROP OPERATOR IF EXISTS pg_catalog.<=(numeric, blob);
DROP OPERATOR IF EXISTS pg_catalog.>(blob, numeric);
DROP OPERATOR IF EXISTS pg_catalog.>(numeric, blob);
DROP OPERATOR IF EXISTS pg_catalog.>=(blob, numeric);
DROP OPERATOR IF EXISTS pg_catalog.>=(numeric, blob);
DROP FUNCTION IF EXISTS pg_catalog.blob_numeric_eq(blob, numeric);
DROP FUNCTION IF EXISTS pg_catalog.numeric_blob_eq(numeric, blob);
DROP FUNCTION IF EXISTS pg_catalog.blob_numeric_ne(blob, numeric);
DROP FUNCTION IF EXISTS pg_catalog.numeric_blob_ne(numeric, blob);
DROP FUNCTION IF EXISTS pg_catalog.blob_numeric_lt(blob, numeric);
DROP FUNCTION IF EXISTS pg_catalog.numeric_blob_lt(numeric, blob);
DROP FUNCTION IF EXISTS pg_catalog.blob_numeric_le(blob, numeric);
DROP FUNCTION IF EXISTS pg_catalog.numeric_blob_le(numeric, blob);
DROP FUNCTION IF EXISTS pg_catalog.blob_numeric_gt(blob, numeric);
DROP FUNCTION IF EXISTS pg_catalog.numeric_blob_gt(numeric, blob);
DROP FUNCTION IF EXISTS pg_catalog.blob_numeric_ge(blob, numeric);
DROP FUNCTION IF EXISTS pg_catalog.numeric_blob_ge(numeric, blob);
DROP FUNCTION IF EXISTS pg_catalog.blob_numeric_cmp(blob, numeric);
DROP FUNCTION IF EXISTS pg_catalog.numeric_blob_cmp(numeric, blob);
DROP OPERATOR IF EXISTS pg_catalog.=(mediumblob, numeric);
DROP OPERATOR IF EXISTS pg_catalog.=(numeric, mediumblob);
DROP OPERATOR IF EXISTS pg_catalog.<>(mediumblob, numeric);
DROP OPERATOR IF EXISTS pg_catalog.<>(numeric, mediumblob);
DROP OPERATOR IF EXISTS pg_catalog.<(mediumblob, numeric);
DROP OPERATOR IF EXISTS pg_catalog.<(numeric, mediumblob);
DROP OPERATOR IF EXISTS pg_catalog.<=(mediumblob, numeric);
DROP OPERATOR IF EXISTS pg_catalog.<=(numeric, mediumblob);
DROP OPERATOR IF EXISTS pg_catalog.>(mediumblob, numeric);
DROP OPERATOR IF EXISTS pg_catalog.>(numeric, mediumblob);
DROP OPERATOR IF EXISTS pg_catalog.>=(mediumblob, numeric);
DROP OPERATOR IF EXISTS pg_catalog.>=(numeric, mediumblob);
DROP FUNCTION IF EXISTS pg_catalog.mediumblob_numeric_eq(mediumblob, numeric);
DROP FUNCTION IF EXISTS pg_catalog.numeric_mediumblob_eq(numeric, mediumblob);
DROP FUNCTION IF EXISTS pg_catalog.mediumblob_numeric_ne(mediumblob, numeric);
DROP FUNCTION IF EXISTS pg_catalog.numeric_mediumblob_ne(numeric, mediumblob);
DROP FUNCTION IF EXISTS pg_catalog.mediumblob_numeric_lt(mediumblob, numeric);
DROP FUNCTION IF EXISTS pg_catalog.numeric_mediumblob_lt(numeric, mediumblob);
DROP FUNCTION IF EXISTS pg_catalog.mediumblob_numeric_le(mediumblob, numeric);
DROP FUNCTION IF EXISTS pg_catalog.numeric_mediumblob_le(numeric, mediumblob);
DROP FUNCTION IF EXISTS pg_catalog.mediumblob_numeric_gt(mediumblob, numeric);
DROP FUNCTION IF EXISTS pg_catalog.numeric_mediumblob_gt(numeric, mediumblob);
DROP FUNCTION IF EXISTS pg_catalog.mediumblob_numeric_ge(mediumblob, numeric);
DROP FUNCTION IF EXISTS pg_catalog.numeric_mediumblob_ge(numeric, mediumblob);
DROP FUNCTION IF EXISTS pg_catalog.mediumblob_numeric_cmp(mediumblob, numeric);
DROP FUNCTION IF EXISTS pg_catalog.numeric_mediumblob_cmp(numeric, mediumblob);
DROP OPERATOR IF EXISTS pg_catalog.=(longblob, numeric);
DROP OPERATOR IF EXISTS pg_catalog.=(numeric, longblob);
DROP OPERATOR IF EXISTS pg_catalog.<>(longblob, numeric);
DROP OPERATOR IF EXISTS pg_catalog.<>(numeric, longblob);
DROP OPERATOR IF EXISTS pg_catalog.<(longblob, numeric);
DROP OPERATOR IF EXISTS pg_catalog.<(numeric, longblob);
DROP OPERATOR IF EXISTS pg_catalog.<=(longblob, numeric);
DROP OPERATOR IF EXISTS pg_catalog.<=(numeric, longblob);
DROP OPERATOR IF EXISTS pg_catalog.>(longblob, numeric);
DROP OPERATOR IF EXISTS pg_catalog.>(numeric, longblob);
DROP OPERATOR IF EXISTS pg_catalog.>=(longblob, numeric);
DROP OPERATOR IF EXISTS pg_catalog.>=(numeric, longblob);
DROP FUNCTION IF EXISTS pg_catalog.longblob_numeric_eq(longblob, numeric);
DROP FUNCTION IF EXISTS pg_catalog.numeric_longblob_eq(numeric, longblob);
DROP FUNCTION IF EXISTS pg_catalog.longblob_numeric_ne(longblob, numeric);
DROP FUNCTION IF EXISTS pg_catalog.numeric_longblob_ne(numeric, longblob);
DROP FUNCTION IF EXISTS pg_catalog.longblob_numeric_lt(longblob, numeric);
DROP FUNCTION IF EXISTS pg_catalog.numeric_longblob_lt(numeric, longblob);
DROP FUNCTION IF EXISTS pg_catalog.longblob_numeric_le(longblob, numeric);
DROP FUNCTION IF EXISTS pg_catalog.numeric_longblob_le(numeric, longblob);
DROP FUNCTION IF EXISTS pg_catalog.longblob_numeric_gt(longblob, numeric);
DROP FUNCTION IF EXISTS pg_catalog.numeric_longblob_gt(numeric, longblob);
DROP FUNCTION IF EXISTS pg_catalog.longblob_numeric_ge(longblob, numeric);
DROP FUNCTION IF EXISTS pg_catalog.numeric_longblob_ge(numeric, longblob);
DROP FUNCTION IF EXISTS pg_catalog.longblob_numeric_cmp(longblob, numeric);
DROP FUNCTION IF EXISTS pg_catalog.numeric_longblob_cmp(numeric, longblob);
DROP OPERATOR IF EXISTS pg_catalog.=(tinyblob, int8);
DROP OPERATOR IF EXISTS pg_catalog.=(int8, tinyblob);
DROP OPERATOR IF EXISTS pg_catalog.<>(tinyblob, int8);
DROP OPERATOR IF EXISTS pg_catalog.<>(int8, tinyblob);
DROP OPERATOR IF EXISTS pg_catalog.<(tinyblob, int8);
DROP OPERATOR IF EXISTS pg_catalog.<(int8, tinyblob);
DROP OPERATOR IF EXISTS pg_catalog.<=(tinyblob, int8);
DROP OPERATOR IF EXISTS pg_catalog.<=(int8, tinyblob);
DROP OPERATOR IF EXISTS pg_catalog.>(tinyblob, int8);
DROP OPERATOR IF EXISTS pg_catalog.>(int8, tinyblob);
DROP OPERATOR IF EXISTS pg_catalog.>=(tinyblob, int8);
DROP OPERATOR IF EXISTS pg_catalog.>=(int8, tinyblob);
DROP FUNCTION IF EXISTS pg_catalog.tinyblob_int8_eq(tinyblob, int8);
DROP FUNCTION IF EXISTS pg_catalog.int8_tinyblob_eq(int8, tinyblob);
DROP FUNCTION IF EXISTS pg_catalog.tinyblob_int8_ne(tinyblob, int8);
DROP FUNCTION IF EXISTS pg_catalog.int8_tinyblob_ne(int8, tinyblob);
DROP FUNCTION IF EXISTS pg_catalog.tinyblob_int8_lt(tinyblob, int8);
DROP FUNCTION IF EXISTS pg_catalog.int8_tinyblob_lt(int8, tinyblob);
DROP FUNCTION IF EXISTS pg_catalog.tinyblob_int8_le(tinyblob, int8);
DROP FUNCTION IF EXISTS pg_catalog.int8_tinyblob_le(int8, tinyblob);
DROP FUNCTION IF EXISTS pg_catalog.tinyblob_int8_gt(tinyblob, int8);
DROP FUNCTION IF EXISTS pg_catalog.int8_tinyblob_gt(int8, tinyblob);
DROP FUNCTION IF EXISTS pg_catalog.tinyblob_int8_ge(tinyblob, int8);
DROP FUNCTION IF EXISTS pg_catalog.int8_tinyblob_ge(int8, tinyblob);
DROP FUNCTION IF EXISTS pg_catalog.tinyblob_int8_cmp(tinyblob, int8);
DROP FUNCTION IF EXISTS pg_catalog.int8_tinyblob_cmp(int8, tinyblob);
DROP OPERATOR IF EXISTS pg_catalog.=(blob, int8);
DROP OPERATOR IF EXISTS pg_catalog.=(int8, blob);
DROP OPERATOR IF EXISTS pg_catalog.<>(blob, int8);
DROP OPERATOR IF EXISTS pg_catalog.<>(int8, blob);
DROP OPERATOR IF EXISTS pg_catalog.<(blob, int8);
DROP OPERATOR IF EXISTS pg_catalog.<(int8, blob);
DROP OPERATOR IF EXISTS pg_catalog.<=(blob, int8);
DROP OPERATOR IF EXISTS pg_catalog.<=(int8, blob);
DROP OPERATOR IF EXISTS pg_catalog.>(blob, int8);
DROP OPERATOR IF EXISTS pg_catalog.>(int8, blob);
DROP OPERATOR IF EXISTS pg_catalog.>=(blob, int8);
DROP OPERATOR IF EXISTS pg_catalog.>=(int8, blob);
DROP FUNCTION IF EXISTS pg_catalog.blob_int8_eq(blob, int8);
DROP FUNCTION IF EXISTS pg_catalog.int8_blob_eq(int8, blob);
DROP FUNCTION IF EXISTS pg_catalog.blob_int8_ne(blob, int8);
DROP FUNCTION IF EXISTS pg_catalog.int8_blob_ne(int8, blob);
DROP FUNCTION IF EXISTS pg_catalog.blob_int8_lt(blob, int8);
DROP FUNCTION IF EXISTS pg_catalog.int8_blob_lt(int8, blob);
DROP FUNCTION IF EXISTS pg_catalog.blob_int8_le(blob, int8);
DROP FUNCTION IF EXISTS pg_catalog.int8_blob_le(int8, blob);
DROP FUNCTION IF EXISTS pg_catalog.blob_int8_gt(blob, int8);
DROP FUNCTION IF EXISTS pg_catalog.int8_blob_gt(int8, blob);
DROP FUNCTION IF EXISTS pg_catalog.blob_int8_ge(blob, int8);
DROP FUNCTION IF EXISTS pg_catalog.int8_blob_ge(int8, blob);
DROP FUNCTION IF EXISTS pg_catalog.blob_int8_cmp(blob, int8);
DROP FUNCTION IF EXISTS pg_catalog.int8_blob_cmp(int8, blob);
DROP OPERATOR IF EXISTS pg_catalog.=(mediumblob, int8);
DROP OPERATOR IF EXISTS pg_catalog.=(int8, mediumblob);
DROP OPERATOR IF EXISTS pg_catalog.<>(mediumblob, int8);
DROP OPERATOR IF EXISTS pg_catalog.<>(int8, mediumblob);
DROP OPERATOR IF EXISTS pg_catalog.<(mediumblob, int8);
DROP OPERATOR IF EXISTS pg_catalog.<(int8, mediumblob);
DROP OPERATOR IF EXISTS pg_catalog.<=(mediumblob, int8);
DROP OPERATOR IF EXISTS pg_catalog.<=(int8, mediumblob);
DROP OPERATOR IF EXISTS pg_catalog.>(mediumblob, int8);
DROP OPERATOR IF EXISTS pg_catalog.>(int8, mediumblob);
DROP OPERATOR IF EXISTS pg_catalog.>=(mediumblob, int8);
DROP OPERATOR IF EXISTS pg_catalog.>=(int8, mediumblob);
DROP FUNCTION IF EXISTS pg_catalog.mediumblob_int8_eq(mediumblob, int8);
DROP FUNCTION IF EXISTS pg_catalog.int8_mediumblob_eq(int8, mediumblob);
DROP FUNCTION IF EXISTS pg_catalog.mediumblob_int8_ne(mediumblob, int8);
DROP FUNCTION IF EXISTS pg_catalog.int8_mediumblob_ne(int8, mediumblob);
DROP FUNCTION IF EXISTS pg_catalog.mediumblob_int8_lt(mediumblob, int8);
DROP FUNCTION IF EXISTS pg_catalog.int8_mediumblob_lt(int8, mediumblob);
DROP FUNCTION IF EXISTS pg_catalog.mediumblob_int8_le(mediumblob, int8);
DROP FUNCTION IF EXISTS pg_catalog.int8_mediumblob_le(int8, mediumblob);
DROP FUNCTION IF EXISTS pg_catalog.mediumblob_int8_gt(mediumblob, int8);
DROP FUNCTION IF EXISTS pg_catalog.int8_mediumblob_gt(int8, mediumblob);
DROP FUNCTION IF EXISTS pg_catalog.mediumblob_int8_ge(mediumblob, int8);
DROP FUNCTION IF EXISTS pg_catalog.int8_mediumblob_ge(int8, mediumblob);
DROP FUNCTION IF EXISTS pg_catalog.mediumblob_int8_cmp(mediumblob, int8);
DROP FUNCTION IF EXISTS pg_catalog.int8_mediumblob_cmp(int8, mediumblob);
DROP OPERATOR IF EXISTS pg_catalog.=(longblob, int8);
DROP OPERATOR IF EXISTS pg_catalog.=(int8, longblob);
DROP OPERATOR IF EXISTS pg_catalog.<>(longblob, int8);
DROP OPERATOR IF EXISTS pg_catalog.<>(int8, longblob);
DROP OPERATOR IF EXISTS pg_catalog.<(longblob, int8);
DROP OPERATOR IF EXISTS pg_catalog.<(int8, longblob);
DROP OPERATOR IF EXISTS pg_catalog.<=(longblob, int8);
DROP OPERATOR IF EXISTS pg_catalog.<=(int8, longblob);
DROP OPERATOR IF EXISTS pg_catalog.>(longblob, int8);
DROP OPERATOR IF EXISTS pg_catalog.>(int8, longblob);
DROP OPERATOR IF EXISTS pg_catalog.>=(longblob, int8);
DROP OPERATOR IF EXISTS pg_catalog.>=(int8, longblob);
DROP FUNCTION IF EXISTS pg_catalog.longblob_int8_eq(longblob, int8);
DROP FUNCTION IF EXISTS pg_catalog.int8_longblob_eq(int8, longblob);
DROP FUNCTION IF EXISTS pg_catalog.longblob_int8_ne(longblob, int8);
DROP FUNCTION IF EXISTS pg_catalog.int8_longblob_ne(int8, longblob);
DROP FUNCTION IF EXISTS pg_catalog.longblob_int8_lt(longblob, int8);
DROP FUNCTION IF EXISTS pg_catalog.int8_longblob_lt(int8, longblob);
DROP FUNCTION IF EXISTS pg_catalog.longblob_int8_le(longblob, int8);
DROP FUNCTION IF EXISTS pg_catalog.int8_longblob_le(int8, longblob);
DROP FUNCTION IF EXISTS pg_catalog.longblob_int8_gt(longblob, int8);
DROP FUNCTION IF EXISTS pg_catalog.int8_longblob_gt(int8, longblob);
DROP FUNCTION IF EXISTS pg_catalog.longblob_int8_ge(longblob, int8);
DROP FUNCTION IF EXISTS pg_catalog.int8_longblob_ge(int8, longblob);
DROP FUNCTION IF EXISTS pg_catalog.longblob_int8_cmp(longblob, int8);
DROP FUNCTION IF EXISTS pg_catalog.int8_longblob_cmp(int8, longblob);
DROP OPERATOR IF EXISTS pg_catalog.=(tinyblob, uint8);
DROP OPERATOR IF EXISTS pg_catalog.=(uint8, tinyblob);
DROP OPERATOR IF EXISTS pg_catalog.<>(tinyblob, uint8);
DROP OPERATOR IF EXISTS pg_catalog.<>(uint8, tinyblob);
DROP OPERATOR IF EXISTS pg_catalog.<(tinyblob, uint8);
DROP OPERATOR IF EXISTS pg_catalog.<(uint8, tinyblob);
DROP OPERATOR IF EXISTS pg_catalog.<=(tinyblob, uint8);
DROP OPERATOR IF EXISTS pg_catalog.<=(uint8, tinyblob);
DROP OPERATOR IF EXISTS pg_catalog.>(tinyblob, uint8);
DROP OPERATOR IF EXISTS pg_catalog.>(uint8, tinyblob);
DROP OPERATOR IF EXISTS pg_catalog.>=(tinyblob, uint8);
DROP OPERATOR IF EXISTS pg_catalog.>=(uint8, tinyblob);
DROP FUNCTION IF EXISTS pg_catalog.tinyblob_uint8_eq(tinyblob, uint8);
DROP FUNCTION IF EXISTS pg_catalog.uint8_tinyblob_eq(uint8, tinyblob);
DROP FUNCTION IF EXISTS pg_catalog.tinyblob_uint8_ne(tinyblob, uint8);
DROP FUNCTION IF EXISTS pg_catalog.uint8_tinyblob_ne(uint8, tinyblob);
DROP FUNCTION IF EXISTS pg_catalog.tinyblob_uint8_lt(tinyblob, uint8);
DROP FUNCTION IF EXISTS pg_catalog.uint8_tinyblob_lt(uint8, tinyblob);
DROP FUNCTION IF EXISTS pg_catalog.tinyblob_uint8_le(tinyblob, uint8);
DROP FUNCTION IF EXISTS pg_catalog.uint8_tinyblob_le(uint8, tinyblob);
DROP FUNCTION IF EXISTS pg_catalog.tinyblob_uint8_gt(tinyblob, uint8);
DROP FUNCTION IF EXISTS pg_catalog.uint8_tinyblob_gt(uint8, tinyblob);
DROP FUNCTION IF EXISTS pg_catalog.tinyblob_uint8_ge(tinyblob, uint8);
DROP FUNCTION IF EXISTS pg_catalog.uint8_tinyblob_ge(uint8, tinyblob);
DROP FUNCTION IF EXISTS pg_catalog.tinyblob_uint8_cmp(tinyblob, uint8);
DROP FUNCTION IF EXISTS pg_catalog.uint8_tinyblob_cmp(uint8, tinyblob);
DROP OPERATOR IF EXISTS pg_catalog.=(blob, uint8);
DROP OPERATOR IF EXISTS pg_catalog.=(uint8, blob);
DROP OPERATOR IF EXISTS pg_catalog.<>(blob, uint8);
DROP OPERATOR IF EXISTS pg_catalog.<>(uint8, blob);
DROP OPERATOR IF EXISTS pg_catalog.<(blob, uint8);
DROP OPERATOR IF EXISTS pg_catalog.<(uint8, blob);
DROP OPERATOR IF EXISTS pg_catalog.<=(blob, uint8);
DROP OPERATOR IF EXISTS pg_catalog.<=(uint8, blob);
DROP OPERATOR IF EXISTS pg_catalog.>(blob, uint8);
DROP OPERATOR IF EXISTS pg_catalog.>(uint8, blob);
DROP OPERATOR IF EXISTS pg_catalog.>=(blob, uint8);
DROP OPERATOR IF EXISTS pg_catalog.>=(uint8, blob);
DROP FUNCTION IF EXISTS pg_catalog.blob_uint8_eq(blob, uint8);
DROP FUNCTION IF EXISTS pg_catalog.uint8_blob_eq(uint8, blob);
DROP FUNCTION IF EXISTS pg_catalog.blob_uint8_ne(blob, uint8);
DROP FUNCTION IF EXISTS pg_catalog.uint8_blob_ne(uint8, blob);
DROP FUNCTION IF EXISTS pg_catalog.blob_uint8_lt(blob, uint8);
DROP FUNCTION IF EXISTS pg_catalog.uint8_blob_lt(uint8, blob);
DROP FUNCTION IF EXISTS pg_catalog.blob_uint8_le(blob, uint8);
DROP FUNCTION IF EXISTS pg_catalog.uint8_blob_le(uint8, blob);
DROP FUNCTION IF EXISTS pg_catalog.blob_uint8_gt(blob, uint8);
DROP FUNCTION IF EXISTS pg_catalog.uint8_blob_gt(uint8, blob);
DROP FUNCTION IF EXISTS pg_catalog.blob_uint8_ge(blob, uint8);
DROP FUNCTION IF EXISTS pg_catalog.uint8_blob_ge(uint8, blob);
DROP FUNCTION IF EXISTS pg_catalog.blob_uint8_cmp(blob, uint8);
DROP FUNCTION IF EXISTS pg_catalog.uint8_blob_cmp(uint8, blob);
DROP OPERATOR IF EXISTS pg_catalog.=(mediumblob, uint8);
DROP OPERATOR IF EXISTS pg_catalog.=(uint8, mediumblob);
DROP OPERATOR IF EXISTS pg_catalog.<>(mediumblob, uint8);
DROP OPERATOR IF EXISTS pg_catalog.<>(uint8, mediumblob);
DROP OPERATOR IF EXISTS pg_catalog.<(mediumblob, uint8);
DROP OPERATOR IF EXISTS pg_catalog.<(uint8, mediumblob);
DROP OPERATOR IF EXISTS pg_catalog.<=(mediumblob, uint8);
DROP OPERATOR IF EXISTS pg_catalog.<=(uint8, mediumblob);
DROP OPERATOR IF EXISTS pg_catalog.>(mediumblob, uint8);
DROP OPERATOR IF EXISTS pg_catalog.>(uint8, mediumblob);
DROP OPERATOR IF EXISTS pg_catalog.>=(mediumblob, uint8);
DROP OPERATOR IF EXISTS pg_catalog.>=(uint8, mediumblob);
DROP FUNCTION IF EXISTS pg_catalog.mediumblob_uint8_eq(mediumblob, uint8);
DROP FUNCTION IF EXISTS pg_catalog.uint8_mediumblob_eq(uint8, mediumblob);
DROP FUNCTION IF EXISTS pg_catalog.mediumblob_uint8_ne(mediumblob, uint8);
DROP FUNCTION IF EXISTS pg_catalog.uint8_mediumblob_ne(uint8, mediumblob);
DROP FUNCTION IF EXISTS pg_catalog.mediumblob_uint8_lt(mediumblob, uint8);
DROP FUNCTION IF EXISTS pg_catalog.uint8_mediumblob_lt(uint8, mediumblob);
DROP FUNCTION IF EXISTS pg_catalog.mediumblob_uint8_le(mediumblob, uint8);
DROP FUNCTION IF EXISTS pg_catalog.uint8_mediumblob_le(uint8, mediumblob);
DROP FUNCTION IF EXISTS pg_catalog.mediumblob_uint8_gt(mediumblob, uint8);
DROP FUNCTION IF EXISTS pg_catalog.uint8_mediumblob_gt(uint8, mediumblob);
DROP FUNCTION IF EXISTS pg_catalog.mediumblob_uint8_ge(mediumblob, uint8);
DROP FUNCTION IF EXISTS pg_catalog.uint8_mediumblob_ge(uint8, mediumblob);
DROP FUNCTION IF EXISTS pg_catalog.mediumblob_uint8_cmp(mediumblob, uint8);
DROP FUNCTION IF EXISTS pg_catalog.uint8_mediumblob_cmp(uint8, mediumblob);
DROP OPERATOR IF EXISTS pg_catalog.=(longblob, uint8);
DROP OPERATOR IF EXISTS pg_catalog.=(uint8, longblob);
DROP OPERATOR IF EXISTS pg_catalog.<>(longblob, uint8);
DROP OPERATOR IF EXISTS pg_catalog.<>(uint8, longblob);
DROP OPERATOR IF EXISTS pg_catalog.<(longblob, uint8);
DROP OPERATOR IF EXISTS pg_catalog.<(uint8, longblob);
DROP OPERATOR IF EXISTS pg_catalog.<=(longblob, uint8);
DROP OPERATOR IF EXISTS pg_catalog.<=(uint8, longblob);
DROP OPERATOR IF EXISTS pg_catalog.>(longblob, uint8);
DROP OPERATOR IF EXISTS pg_catalog.>(uint8, longblob);
DROP OPERATOR IF EXISTS pg_catalog.>=(longblob, uint8);
DROP OPERATOR IF EXISTS pg_catalog.>=(uint8, longblob);
DROP FUNCTION IF EXISTS pg_catalog.longblob_uint8_eq(longblob, uint8);
DROP FUNCTION IF EXISTS pg_catalog.uint8_longblob_eq(uint8, longblob);
DROP FUNCTION IF EXISTS pg_catalog.longblob_uint8_ne(longblob, uint8);
DROP FUNCTION IF EXISTS pg_catalog.uint8_longblob_ne(uint8, longblob);
DROP FUNCTION IF EXISTS pg_catalog.longblob_uint8_lt(longblob, uint8);
DROP FUNCTION IF EXISTS pg_catalog.uint8_longblob_lt(uint8, longblob);
DROP FUNCTION IF EXISTS pg_catalog.longblob_uint8_le(longblob, uint8);
DROP FUNCTION IF EXISTS pg_catalog.uint8_longblob_le(uint8, longblob);
DROP FUNCTION IF EXISTS pg_catalog.longblob_uint8_gt(longblob, uint8);
DROP FUNCTION IF EXISTS pg_catalog.uint8_longblob_gt(uint8, longblob);
DROP FUNCTION IF EXISTS pg_catalog.longblob_uint8_ge(longblob, uint8);
DROP FUNCTION IF EXISTS pg_catalog.uint8_longblob_ge(uint8, longblob);
DROP FUNCTION IF EXISTS pg_catalog.longblob_uint8_cmp(longblob, uint8);
DROP FUNCTION IF EXISTS pg_catalog.uint8_longblob_cmp(uint8, longblob);
DROP OPERATOR IF EXISTS pg_catalog.=(tinyblob, float8);
DROP OPERATOR IF EXISTS pg_catalog.=(float8, tinyblob);
DROP OPERATOR IF EXISTS pg_catalog.<>(tinyblob, float8);
DROP OPERATOR IF EXISTS pg_catalog.<>(float8, tinyblob);
DROP OPERATOR IF EXISTS pg_catalog.<(tinyblob, float8);
DROP OPERATOR IF EXISTS pg_catalog.<(float8, tinyblob);
DROP OPERATOR IF EXISTS pg_catalog.<=(tinyblob, float8);
DROP OPERATOR IF EXISTS pg_catalog.<=(float8, tinyblob);
DROP OPERATOR IF EXISTS pg_catalog.>(tinyblob, float8);
DROP OPERATOR IF EXISTS pg_catalog.>(float8, tinyblob);
DROP OPERATOR IF EXISTS pg_catalog.>=(tinyblob, float8);
DROP OPERATOR IF EXISTS pg_catalog.>=(float8, tinyblob);
DROP FUNCTION IF EXISTS pg_catalog.tinyblob_float8_eq(tinyblob, float8);
DROP FUNCTION IF EXISTS pg_catalog.float8_tinyblob_eq(float8, tinyblob);
DROP FUNCTION IF EXISTS pg_catalog.tinyblob_float8_ne(tinyblob, float8);
DROP FUNCTION IF EXISTS pg_catalog.float8_tinyblob_ne(float8, tinyblob);
DROP FUNCTION IF EXISTS pg_catalog.tinyblob_float8_lt(tinyblob, float8);
DROP FUNCTION IF EXISTS pg_catalog.float8_tinyblob_lt(float8, tinyblob);
DROP FUNCTION IF EXISTS pg_catalog.tinyblob_float8_le(tinyblob, float8);
DROP FUNCTION IF EXISTS pg_catalog.float8_tinyblob_le(float8, tinyblob);
DROP FUNCTION IF EXISTS pg_catalog.tinyblob_float8_gt(tinyblob, float8);
DROP FUNCTION IF EXISTS pg_catalog.float8_tinyblob_gt(float8, tinyblob);
DROP FUNCTION IF EXISTS pg_catalog.tinyblob_float8_ge(tinyblob, float8);
DROP FUNCTION IF EXISTS pg_catalog.float8_tinyblob_ge(float8, tinyblob);
DROP FUNCTION IF EXISTS pg_catalog.tinyblob_float8_cmp(tinyblob, float8);
DROP FUNCTION IF EXISTS pg_catalog.float8_tinyblob_cmp(float8, tinyblob);
DROP OPERATOR IF EXISTS pg_catalog.=(blob, float8);
DROP OPERATOR IF EXISTS pg_catalog.=(float8, blob);
DROP OPERATOR IF EXISTS pg_catalog.<>(blob, float8);
DROP OPERATOR IF EXISTS pg_catalog.<>(float8, blob);
DROP OPERATOR IF EXISTS pg_catalog.<(blob, float8);
DROP OPERATOR IF EXISTS pg_catalog.<(float8, blob);
DROP OPERATOR IF EXISTS pg_catalog.<=(blob, float8);
DROP OPERATOR IF EXISTS pg_catalog.<=(float8, blob);
DROP OPERATOR IF EXISTS pg_catalog.>(blob, float8);
DROP OPERATOR IF EXISTS pg_catalog.>(float8, blob);
DROP OPERATOR IF EXISTS pg_catalog.>=(blob, float8);
DROP OPERATOR IF EXISTS pg_catalog.>=(float8, blob);
DROP FUNCTION IF EXISTS pg_catalog.blob_float8_eq(blob, float8);
DROP FUNCTION IF EXISTS pg_catalog.float8_blob_eq(float8, blob);
DROP FUNCTION IF EXISTS pg_catalog.blob_float8_ne(blob, float8);
DROP FUNCTION IF EXISTS pg_catalog.float8_blob_ne(float8, blob);
DROP FUNCTION IF EXISTS pg_catalog.blob_float8_lt(blob, float8);
DROP FUNCTION IF EXISTS pg_catalog.float8_blob_lt(float8, blob);
DROP FUNCTION IF EXISTS pg_catalog.blob_float8_le(blob, float8);
DROP FUNCTION IF EXISTS pg_catalog.float8_blob_le(float8, blob);
DROP FUNCTION IF EXISTS pg_catalog.blob_float8_gt(blob, float8);
DROP FUNCTION IF EXISTS pg_catalog.float8_blob_gt(float8, blob);
DROP FUNCTION IF EXISTS pg_catalog.blob_float8_ge(blob, float8);
DROP FUNCTION IF EXISTS pg_catalog.float8_blob_ge(float8, blob);
DROP FUNCTION IF EXISTS pg_catalog.blob_float8_cmp(blob, float8);
DROP FUNCTION IF EXISTS pg_catalog.float8_blob_cmp(float8, blob);
DROP OPERATOR IF EXISTS pg_catalog.=(mediumblob, float8);
DROP OPERATOR IF EXISTS pg_catalog.=(float8, mediumblob);
DROP OPERATOR IF EXISTS pg_catalog.<>(mediumblob, float8);
DROP OPERATOR IF EXISTS pg_catalog.<>(float8, mediumblob);
DROP OPERATOR IF EXISTS pg_catalog.<(mediumblob, float8);
DROP OPERATOR IF EXISTS pg_catalog.<(float8, mediumblob);
DROP OPERATOR IF EXISTS pg_catalog.<=(mediumblob, float8);
DROP OPERATOR IF EXISTS pg_catalog.<=(float8, mediumblob);
DROP OPERATOR IF EXISTS pg_catalog.>(mediumblob, float8);
DROP OPERATOR IF EXISTS pg_catalog.>(float8, mediumblob);
DROP OPERATOR IF EXISTS pg_catalog.>=(mediumblob, float8);
DROP OPERATOR IF EXISTS pg_catalog.>=(float8, mediumblob);
DROP FUNCTION IF EXISTS pg_catalog.mediumblob_float8_eq(mediumblob, float8);
DROP FUNCTION IF EXISTS pg_catalog.float8_mediumblob_eq(float8, mediumblob);
DROP FUNCTION IF EXISTS pg_catalog.mediumblob_float8_ne(mediumblob, float8);
DROP FUNCTION IF EXISTS pg_catalog.float8_mediumblob_ne(float8, mediumblob);
DROP FUNCTION IF EXISTS pg_catalog.mediumblob_float8_lt(mediumblob, float8);
DROP FUNCTION IF EXISTS pg_catalog.float8_mediumblob_lt(float8, mediumblob);
DROP FUNCTION IF EXISTS pg_catalog.mediumblob_float8_le(mediumblob, float8);
DROP FUNCTION IF EXISTS pg_catalog.float8_mediumblob_le(float8, mediumblob);
DROP FUNCTION IF EXISTS pg_catalog.mediumblob_float8_gt(mediumblob, float8);
DROP FUNCTION IF EXISTS pg_catalog.float8_mediumblob_gt(float8, mediumblob);
DROP FUNCTION IF EXISTS pg_catalog.mediumblob_float8_ge(mediumblob, float8);
DROP FUNCTION IF EXISTS pg_catalog.float8_mediumblob_ge(float8, mediumblob);
DROP FUNCTION IF EXISTS pg_catalog.mediumblob_float8_cmp(mediumblob, float8);
DROP FUNCTION IF EXISTS pg_catalog.float8_mediumblob_cmp(float8, mediumblob);
DROP OPERATOR IF EXISTS pg_catalog.=(longblob, float8);
DROP OPERATOR IF EXISTS pg_catalog.=(float8, longblob);
DROP OPERATOR IF EXISTS pg_catalog.<>(longblob, float8);
DROP OPERATOR IF EXISTS pg_catalog.<>(float8, longblob);
DROP OPERATOR IF EXISTS pg_catalog.<(longblob, float8);
DROP OPERATOR IF EXISTS pg_catalog.<(float8, longblob);
DROP OPERATOR IF EXISTS pg_catalog.<=(longblob, float8);
DROP OPERATOR IF EXISTS pg_catalog.<=(float8, longblob);
DROP OPERATOR IF EXISTS pg_catalog.>(longblob, float8);
DROP OPERATOR IF EXISTS pg_catalog.>(float8, longblob);
DROP OPERATOR IF EXISTS pg_catalog.>=(longblob, float8);
DROP OPERATOR IF EXISTS pg_catalog.>=(float8, longblob);
DROP FUNCTION IF EXISTS pg_catalog.longblob_float8_eq(longblob, float8);
DROP FUNCTION IF EXISTS pg_catalog.float8_longblob_eq(float8, longblob);
DROP FUNCTION IF EXISTS pg_catalog.longblob_float8_ne(longblob, float8);
DROP FUNCTION IF EXISTS pg_catalog.float8_longblob_ne(float8, longblob);
DROP FUNCTION IF EXISTS pg_catalog.longblob_float8_lt(longblob, float8);
DROP FUNCTION IF EXISTS pg_catalog.float8_longblob_lt(float8, longblob);
DROP FUNCTION IF EXISTS pg_catalog.longblob_float8_le(longblob, float8);
DROP FUNCTION IF EXISTS pg_catalog.float8_longblob_le(float8, longblob);
DROP FUNCTION IF EXISTS pg_catalog.longblob_float8_gt(longblob, float8);
DROP FUNCTION IF EXISTS pg_catalog.float8_longblob_gt(float8, longblob);
DROP FUNCTION IF EXISTS pg_catalog.longblob_float8_ge(longblob, float8);
DROP FUNCTION IF EXISTS pg_catalog.float8_longblob_ge(float8, longblob);
DROP FUNCTION IF EXISTS pg_catalog.longblob_float8_cmp(longblob, float8);
DROP FUNCTION IF EXISTS pg_catalog.float8_longblob_cmp(float8, longblob);

DROP OPERATOR IF EXISTS pg_catalog.=(tinyblob, timestamp without time zone);
DROP OPERATOR IF EXISTS pg_catalog.=(timestamp without time zone, tinyblob);
DROP OPERATOR IF EXISTS pg_catalog.<>(tinyblob, timestamp without time zone);
DROP OPERATOR IF EXISTS pg_catalog.<>(timestamp without time zone, tinyblob);
DROP OPERATOR IF EXISTS pg_catalog.<(tinyblob, timestamp without time zone);
DROP OPERATOR IF EXISTS pg_catalog.<(timestamp without time zone, tinyblob);
DROP OPERATOR IF EXISTS pg_catalog.<=(tinyblob, timestamp without time zone);
DROP OPERATOR IF EXISTS pg_catalog.<=(timestamp without time zone, tinyblob);
DROP OPERATOR IF EXISTS pg_catalog.>(tinyblob, timestamp without time zone);
DROP OPERATOR IF EXISTS pg_catalog.>(timestamp without time zone, tinyblob);
DROP OPERATOR IF EXISTS pg_catalog.>=(tinyblob, timestamp without time zone);
DROP OPERATOR IF EXISTS pg_catalog.>=(timestamp without time zone, tinyblob);
DROP FUNCTION IF EXISTS pg_catalog.tinyblob_datetime_eq(tinyblob, timestamp without time zone);
DROP FUNCTION IF EXISTS pg_catalog.datetime_tinyblob_eq(timestamp without time zone, tinyblob);
DROP FUNCTION IF EXISTS pg_catalog.tinyblob_datetime_ne(tinyblob, timestamp without time zone);
DROP FUNCTION IF EXISTS pg_catalog.datetime_tinyblob_ne(timestamp without time zone, tinyblob);
DROP FUNCTION IF EXISTS pg_catalog.tinyblob_datetime_lt(tinyblob, timestamp without time zone);
DROP FUNCTION IF EXISTS pg_catalog.datetime_tinyblob_lt(timestamp without time zone, tinyblob);
DROP FUNCTION IF EXISTS pg_catalog.tinyblob_datetime_le(tinyblob, timestamp without time zone);
DROP FUNCTION IF EXISTS pg_catalog.datetime_tinyblob_le(timestamp without time zone, tinyblob);
DROP FUNCTION IF EXISTS pg_catalog.tinyblob_datetime_gt(tinyblob, timestamp without time zone);
DROP FUNCTION IF EXISTS pg_catalog.datetime_tinyblob_gt(timestamp without time zone, tinyblob);
DROP FUNCTION IF EXISTS pg_catalog.tinyblob_datetime_ge(tinyblob, timestamp without time zone);
DROP FUNCTION IF EXISTS pg_catalog.datetime_tinyblob_ge(timestamp without time zone, tinyblob);
DROP FUNCTION IF EXISTS pg_catalog.tinyblob_datetime_cmp(tinyblob, timestamp without time zone);
DROP FUNCTION IF EXISTS pg_catalog.datetime_tinyblob_cmp(timestamp without time zone, tinyblob);
DROP OPERATOR IF EXISTS pg_catalog.=(blob, timestamp without time zone);
DROP OPERATOR IF EXISTS pg_catalog.=(timestamp without time zone, blob);
DROP OPERATOR IF EXISTS pg_catalog.<>(blob, timestamp without time zone);
DROP OPERATOR IF EXISTS pg_catalog.<>(timestamp without time zone, blob);
DROP OPERATOR IF EXISTS pg_catalog.<(blob, timestamp without time zone);
DROP OPERATOR IF EXISTS pg_catalog.<(timestamp without time zone, blob);
DROP OPERATOR IF EXISTS pg_catalog.<=(blob, timestamp without time zone);
DROP OPERATOR IF EXISTS pg_catalog.<=(timestamp without time zone, blob);
DROP OPERATOR IF EXISTS pg_catalog.>(blob, timestamp without time zone);
DROP OPERATOR IF EXISTS pg_catalog.>(timestamp without time zone, blob);
DROP OPERATOR IF EXISTS pg_catalog.>=(blob, timestamp without time zone);
DROP OPERATOR IF EXISTS pg_catalog.>=(timestamp without time zone, blob);
DROP FUNCTION IF EXISTS pg_catalog.blob_datetime_eq(blob, timestamp without time zone);
DROP FUNCTION IF EXISTS pg_catalog.datetime_blob_eq(timestamp without time zone, blob);
DROP FUNCTION IF EXISTS pg_catalog.blob_datetime_ne(blob, timestamp without time zone);
DROP FUNCTION IF EXISTS pg_catalog.datetime_blob_ne(timestamp without time zone, blob);
DROP FUNCTION IF EXISTS pg_catalog.blob_datetime_lt(blob, timestamp without time zone);
DROP FUNCTION IF EXISTS pg_catalog.datetime_blob_lt(timestamp without time zone, blob);
DROP FUNCTION IF EXISTS pg_catalog.blob_datetime_le(blob, timestamp without time zone);
DROP FUNCTION IF EXISTS pg_catalog.datetime_blob_le(timestamp without time zone, blob);
DROP FUNCTION IF EXISTS pg_catalog.blob_datetime_gt(blob, timestamp without time zone);
DROP FUNCTION IF EXISTS pg_catalog.datetime_blob_gt(timestamp without time zone, blob);
DROP FUNCTION IF EXISTS pg_catalog.blob_datetime_ge(blob, timestamp without time zone);
DROP FUNCTION IF EXISTS pg_catalog.datetime_blob_ge(timestamp without time zone, blob);
DROP FUNCTION IF EXISTS pg_catalog.blob_datetime_cmp(blob, timestamp without time zone);
DROP FUNCTION IF EXISTS pg_catalog.datetime_blob_cmp(timestamp without time zone, blob);
DROP OPERATOR IF EXISTS pg_catalog.=(mediumblob, timestamp without time zone);
DROP OPERATOR IF EXISTS pg_catalog.=(timestamp without time zone, mediumblob);
DROP OPERATOR IF EXISTS pg_catalog.<>(mediumblob, timestamp without time zone);
DROP OPERATOR IF EXISTS pg_catalog.<>(timestamp without time zone, mediumblob);
DROP OPERATOR IF EXISTS pg_catalog.<(mediumblob, timestamp without time zone);
DROP OPERATOR IF EXISTS pg_catalog.<(timestamp without time zone, mediumblob);
DROP OPERATOR IF EXISTS pg_catalog.<=(mediumblob, timestamp without time zone);
DROP OPERATOR IF EXISTS pg_catalog.<=(timestamp without time zone, mediumblob);
DROP OPERATOR IF EXISTS pg_catalog.>(mediumblob, timestamp without time zone);
DROP OPERATOR IF EXISTS pg_catalog.>(timestamp without time zone, mediumblob);
DROP OPERATOR IF EXISTS pg_catalog.>=(mediumblob, timestamp without time zone);
DROP OPERATOR IF EXISTS pg_catalog.>=(timestamp without time zone, mediumblob);
DROP FUNCTION IF EXISTS pg_catalog.mediumblob_datetime_eq(mediumblob, timestamp without time zone);
DROP FUNCTION IF EXISTS pg_catalog.datetime_mediumblob_eq(timestamp without time zone, mediumblob);
DROP FUNCTION IF EXISTS pg_catalog.mediumblob_datetime_ne(mediumblob, timestamp without time zone);
DROP FUNCTION IF EXISTS pg_catalog.datetime_mediumblob_ne(timestamp without time zone, mediumblob);
DROP FUNCTION IF EXISTS pg_catalog.mediumblob_datetime_lt(mediumblob, timestamp without time zone);
DROP FUNCTION IF EXISTS pg_catalog.datetime_mediumblob_lt(timestamp without time zone, mediumblob);
DROP FUNCTION IF EXISTS pg_catalog.mediumblob_datetime_le(mediumblob, timestamp without time zone);
DROP FUNCTION IF EXISTS pg_catalog.datetime_mediumblob_le(timestamp without time zone, mediumblob);
DROP FUNCTION IF EXISTS pg_catalog.mediumblob_datetime_gt(mediumblob, timestamp without time zone);
DROP FUNCTION IF EXISTS pg_catalog.datetime_mediumblob_gt(timestamp without time zone, mediumblob);
DROP FUNCTION IF EXISTS pg_catalog.mediumblob_datetime_ge(mediumblob, timestamp without time zone);
DROP FUNCTION IF EXISTS pg_catalog.datetime_mediumblob_ge(timestamp without time zone, mediumblob);
DROP FUNCTION IF EXISTS pg_catalog.mediumblob_datetime_cmp(mediumblob, timestamp without time zone);
DROP FUNCTION IF EXISTS pg_catalog.datetime_mediumblob_cmp(timestamp without time zone, mediumblob);
DROP OPERATOR IF EXISTS pg_catalog.=(longblob, timestamp without time zone);
DROP OPERATOR IF EXISTS pg_catalog.=(timestamp without time zone, longblob);
DROP OPERATOR IF EXISTS pg_catalog.<>(longblob, timestamp without time zone);
DROP OPERATOR IF EXISTS pg_catalog.<>(timestamp without time zone, longblob);
DROP OPERATOR IF EXISTS pg_catalog.<(longblob, timestamp without time zone);
DROP OPERATOR IF EXISTS pg_catalog.<(timestamp without time zone, longblob);
DROP OPERATOR IF EXISTS pg_catalog.<=(longblob, timestamp without time zone);
DROP OPERATOR IF EXISTS pg_catalog.<=(timestamp without time zone, longblob);
DROP OPERATOR IF EXISTS pg_catalog.>(longblob, timestamp without time zone);
DROP OPERATOR IF EXISTS pg_catalog.>(timestamp without time zone, longblob);
DROP OPERATOR IF EXISTS pg_catalog.>=(longblob, timestamp without time zone);
DROP OPERATOR IF EXISTS pg_catalog.>=(timestamp without time zone, longblob);
DROP FUNCTION IF EXISTS pg_catalog.longblob_datetime_eq(longblob, timestamp without time zone);
DROP FUNCTION IF EXISTS pg_catalog.datetime_longblob_eq(timestamp without time zone, longblob);
DROP FUNCTION IF EXISTS pg_catalog.longblob_datetime_ne(longblob, timestamp without time zone);
DROP FUNCTION IF EXISTS pg_catalog.datetime_longblob_ne(timestamp without time zone, longblob);
DROP FUNCTION IF EXISTS pg_catalog.longblob_datetime_lt(longblob, timestamp without time zone);
DROP FUNCTION IF EXISTS pg_catalog.datetime_longblob_lt(timestamp without time zone, longblob);
DROP FUNCTION IF EXISTS pg_catalog.longblob_datetime_le(longblob, timestamp without time zone);
DROP FUNCTION IF EXISTS pg_catalog.datetime_longblob_le(timestamp without time zone, longblob);
DROP FUNCTION IF EXISTS pg_catalog.longblob_datetime_gt(longblob, timestamp without time zone);
DROP FUNCTION IF EXISTS pg_catalog.datetime_longblob_gt(timestamp without time zone, longblob);
DROP FUNCTION IF EXISTS pg_catalog.longblob_datetime_ge(longblob, timestamp without time zone);
DROP FUNCTION IF EXISTS pg_catalog.datetime_longblob_ge(timestamp without time zone, longblob);
DROP FUNCTION IF EXISTS pg_catalog.longblob_datetime_cmp(longblob, timestamp without time zone);
DROP FUNCTION IF EXISTS pg_catalog.datetime_longblob_cmp(timestamp without time zone, longblob);

DROP OPERATOR IF EXISTS pg_catalog.=(tinyblob, timestamptz);
DROP OPERATOR IF EXISTS pg_catalog.=(timestamptz, tinyblob);
DROP OPERATOR IF EXISTS pg_catalog.<>(tinyblob, timestamptz);
DROP OPERATOR IF EXISTS pg_catalog.<>(timestamptz, tinyblob);
DROP OPERATOR IF EXISTS pg_catalog.<(tinyblob, timestamptz);
DROP OPERATOR IF EXISTS pg_catalog.<(timestamptz, tinyblob);
DROP OPERATOR IF EXISTS pg_catalog.<=(tinyblob, timestamptz);
DROP OPERATOR IF EXISTS pg_catalog.<=(timestamptz, tinyblob);
DROP OPERATOR IF EXISTS pg_catalog.>(tinyblob, timestamptz);
DROP OPERATOR IF EXISTS pg_catalog.>(timestamptz, tinyblob);
DROP OPERATOR IF EXISTS pg_catalog.>=(tinyblob, timestamptz);
DROP OPERATOR IF EXISTS pg_catalog.>=(timestamptz, tinyblob);
DROP FUNCTION IF EXISTS pg_catalog.tinyblob_timestamp_eq(tinyblob, timestamptz);
DROP FUNCTION IF EXISTS pg_catalog.timestamp_tinyblob_eq(timestamptz, tinyblob);
DROP FUNCTION IF EXISTS pg_catalog.tinyblob_timestamp_ne(tinyblob, timestamptz);
DROP FUNCTION IF EXISTS pg_catalog.timestamp_tinyblob_ne(timestamptz, tinyblob);
DROP FUNCTION IF EXISTS pg_catalog.tinyblob_timestamp_lt(tinyblob, timestamptz);
DROP FUNCTION IF EXISTS pg_catalog.timestamp_tinyblob_lt(timestamptz, tinyblob);
DROP FUNCTION IF EXISTS pg_catalog.tinyblob_timestamp_le(tinyblob, timestamptz);
DROP FUNCTION IF EXISTS pg_catalog.timestamp_tinyblob_le(timestamptz, tinyblob);
DROP FUNCTION IF EXISTS pg_catalog.tinyblob_timestamp_gt(tinyblob, timestamptz);
DROP FUNCTION IF EXISTS pg_catalog.timestamp_tinyblob_gt(timestamptz, tinyblob);
DROP FUNCTION IF EXISTS pg_catalog.tinyblob_timestamp_ge(tinyblob, timestamptz);
DROP FUNCTION IF EXISTS pg_catalog.timestamp_tinyblob_ge(timestamptz, tinyblob);
DROP FUNCTION IF EXISTS pg_catalog.tinyblob_timestamp_cmp(tinyblob, timestamptz);
DROP FUNCTION IF EXISTS pg_catalog.timestamp_tinyblob_cmp(timestamptz, tinyblob);
DROP OPERATOR IF EXISTS pg_catalog.=(blob, timestamptz);
DROP OPERATOR IF EXISTS pg_catalog.=(timestamptz, blob);
DROP OPERATOR IF EXISTS pg_catalog.<>(blob, timestamptz);
DROP OPERATOR IF EXISTS pg_catalog.<>(timestamptz, blob);
DROP OPERATOR IF EXISTS pg_catalog.<(blob, timestamptz);
DROP OPERATOR IF EXISTS pg_catalog.<(timestamptz, blob);
DROP OPERATOR IF EXISTS pg_catalog.<=(blob, timestamptz);
DROP OPERATOR IF EXISTS pg_catalog.<=(timestamptz, blob);
DROP OPERATOR IF EXISTS pg_catalog.>(blob, timestamptz);
DROP OPERATOR IF EXISTS pg_catalog.>(timestamptz, blob);
DROP OPERATOR IF EXISTS pg_catalog.>=(blob, timestamptz);
DROP OPERATOR IF EXISTS pg_catalog.>=(timestamptz, blob);
DROP FUNCTION IF EXISTS pg_catalog.blob_timestamp_eq(blob, timestamptz);
DROP FUNCTION IF EXISTS pg_catalog.timestamp_blob_eq(timestamptz, blob);
DROP FUNCTION IF EXISTS pg_catalog.blob_timestamp_ne(blob, timestamptz);
DROP FUNCTION IF EXISTS pg_catalog.timestamp_blob_ne(timestamptz, blob);
DROP FUNCTION IF EXISTS pg_catalog.blob_timestamp_lt(blob, timestamptz);
DROP FUNCTION IF EXISTS pg_catalog.timestamp_blob_lt(timestamptz, blob);
DROP FUNCTION IF EXISTS pg_catalog.blob_timestamp_le(blob, timestamptz);
DROP FUNCTION IF EXISTS pg_catalog.timestamp_blob_le(timestamptz, blob);
DROP FUNCTION IF EXISTS pg_catalog.blob_timestamp_gt(blob, timestamptz);
DROP FUNCTION IF EXISTS pg_catalog.timestamp_blob_gt(timestamptz, blob);
DROP FUNCTION IF EXISTS pg_catalog.blob_timestamp_ge(blob, timestamptz);
DROP FUNCTION IF EXISTS pg_catalog.timestamp_blob_ge(timestamptz, blob);
DROP FUNCTION IF EXISTS pg_catalog.blob_timestamp_cmp(blob, timestamptz);
DROP FUNCTION IF EXISTS pg_catalog.timestamp_blob_cmp(timestamptz, blob);
DROP OPERATOR IF EXISTS pg_catalog.=(mediumblob, timestamptz);
DROP OPERATOR IF EXISTS pg_catalog.=(timestamptz, mediumblob);
DROP OPERATOR IF EXISTS pg_catalog.<>(mediumblob, timestamptz);
DROP OPERATOR IF EXISTS pg_catalog.<>(timestamptz, mediumblob);
DROP OPERATOR IF EXISTS pg_catalog.<(mediumblob, timestamptz);
DROP OPERATOR IF EXISTS pg_catalog.<(timestamptz, mediumblob);
DROP OPERATOR IF EXISTS pg_catalog.<=(mediumblob, timestamptz);
DROP OPERATOR IF EXISTS pg_catalog.<=(timestamptz, mediumblob);
DROP OPERATOR IF EXISTS pg_catalog.>(mediumblob, timestamptz);
DROP OPERATOR IF EXISTS pg_catalog.>(timestamptz, mediumblob);
DROP OPERATOR IF EXISTS pg_catalog.>=(mediumblob, timestamptz);
DROP OPERATOR IF EXISTS pg_catalog.>=(timestamptz, mediumblob);
DROP FUNCTION IF EXISTS pg_catalog.mediumblob_timestamp_eq(mediumblob, timestamptz);
DROP FUNCTION IF EXISTS pg_catalog.timestamp_mediumblob_eq(timestamptz, mediumblob);
DROP FUNCTION IF EXISTS pg_catalog.mediumblob_timestamp_ne(mediumblob, timestamptz);
DROP FUNCTION IF EXISTS pg_catalog.timestamp_mediumblob_ne(timestamptz, mediumblob);
DROP FUNCTION IF EXISTS pg_catalog.mediumblob_timestamp_lt(mediumblob, timestamptz);
DROP FUNCTION IF EXISTS pg_catalog.timestamp_mediumblob_lt(timestamptz, mediumblob);
DROP FUNCTION IF EXISTS pg_catalog.mediumblob_timestamp_le(mediumblob, timestamptz);
DROP FUNCTION IF EXISTS pg_catalog.timestamp_mediumblob_le(timestamptz, mediumblob);
DROP FUNCTION IF EXISTS pg_catalog.mediumblob_timestamp_gt(mediumblob, timestamptz);
DROP FUNCTION IF EXISTS pg_catalog.timestamp_mediumblob_gt(timestamptz, mediumblob);
DROP FUNCTION IF EXISTS pg_catalog.mediumblob_timestamp_ge(mediumblob, timestamptz);
DROP FUNCTION IF EXISTS pg_catalog.timestamp_mediumblob_ge(timestamptz, mediumblob);
DROP FUNCTION IF EXISTS pg_catalog.mediumblob_timestamp_cmp(mediumblob, timestamptz);
DROP FUNCTION IF EXISTS pg_catalog.timestamp_mediumblob_cmp(timestamptz, mediumblob);
DROP OPERATOR IF EXISTS pg_catalog.=(longblob, timestamptz);
DROP OPERATOR IF EXISTS pg_catalog.=(timestamptz, longblob);
DROP OPERATOR IF EXISTS pg_catalog.<>(longblob, timestamptz);
DROP OPERATOR IF EXISTS pg_catalog.<>(timestamptz, longblob);
DROP OPERATOR IF EXISTS pg_catalog.<(longblob, timestamptz);
DROP OPERATOR IF EXISTS pg_catalog.<(timestamptz, longblob);
DROP OPERATOR IF EXISTS pg_catalog.<=(longblob, timestamptz);
DROP OPERATOR IF EXISTS pg_catalog.<=(timestamptz, longblob);
DROP OPERATOR IF EXISTS pg_catalog.>(longblob, timestamptz);
DROP OPERATOR IF EXISTS pg_catalog.>(timestamptz, longblob);
DROP OPERATOR IF EXISTS pg_catalog.>=(longblob, timestamptz);
DROP OPERATOR IF EXISTS pg_catalog.>=(timestamptz, longblob);
DROP FUNCTION IF EXISTS pg_catalog.longblob_timestamp_eq(longblob, timestamptz);
DROP FUNCTION IF EXISTS pg_catalog.timestamp_longblob_eq(timestamptz, longblob);
DROP FUNCTION IF EXISTS pg_catalog.longblob_timestamp_ne(longblob, timestamptz);
DROP FUNCTION IF EXISTS pg_catalog.timestamp_longblob_ne(timestamptz, longblob);
DROP FUNCTION IF EXISTS pg_catalog.longblob_timestamp_lt(longblob, timestamptz);
DROP FUNCTION IF EXISTS pg_catalog.timestamp_longblob_lt(timestamptz, longblob);
DROP FUNCTION IF EXISTS pg_catalog.longblob_timestamp_le(longblob, timestamptz);
DROP FUNCTION IF EXISTS pg_catalog.timestamp_longblob_le(timestamptz, longblob);
DROP FUNCTION IF EXISTS pg_catalog.longblob_timestamp_gt(longblob, timestamptz);
DROP FUNCTION IF EXISTS pg_catalog.timestamp_longblob_gt(timestamptz, longblob);
DROP FUNCTION IF EXISTS pg_catalog.longblob_timestamp_ge(longblob, timestamptz);
DROP FUNCTION IF EXISTS pg_catalog.timestamp_longblob_ge(timestamptz, longblob);
DROP FUNCTION IF EXISTS pg_catalog.longblob_timestamp_cmp(longblob, timestamptz);
DROP FUNCTION IF EXISTS pg_catalog.timestamp_longblob_cmp(timestamptz, longblob);

DROP AGGREGATE IF EXISTS pg_catalog.var_pop(json);

DROP FUNCTION IF EXISTS pg_catalog.upper(int8);
DROP FUNCTION IF EXISTS pg_catalog.upper(numeric);
DROP FUNCTION IF EXISTS pg_catalog.upper(date);
DROP FUNCTION IF EXISTS pg_catalog.upper(time);
DROP FUNCTION IF EXISTS pg_catalog.upper(timestamp(0) without time zone);
DROP FUNCTION IF EXISTS pg_catalog.upper(timestamp(0) with time zone);
DROP FUNCTION IF EXISTS pg_catalog.upper(bit);
DROP FUNCTION IF EXISTS pg_catalog.upper(boolean);
DROP FUNCTION IF EXISTS pg_catalog.upper(year);
DROP FUNCTION IF EXISTS pg_catalog.upper(char);
DROP FUNCTION IF EXISTS pg_catalog.upper(varchar);
DROP FUNCTION IF EXISTS pg_catalog.upper(tinyblob);
DROP FUNCTION IF EXISTS pg_catalog.upper(binary);
DROP FUNCTION IF EXISTS pg_catalog.upper(varbinary);
DROP FUNCTION IF EXISTS pg_catalog.upper(blob);
DROP FUNCTION IF EXISTS pg_catalog.upper(mediumblob);
DROP FUNCTION IF EXISTS pg_catalog.upper(longblob);
DROP FUNCTION IF EXISTS pg_catalog.upper(anyenum);
DROP FUNCTION IF EXISTS pg_catalog.upper(anyset);
DROP FUNCTION IF EXISTS pg_catalog.upper(json);
