create schema db_bin;
set current_schema to 'db_bin';
select bin(1);
select bin(0);
select bin('2');
select bin('a');
select bin('11a');
select bin(1.1);
select bin(null);
select bin(true);
select bin(false);
select bin('测试');
drop schema db_bin cascade;
reset current_schema;
