-- Tests for package GMS_RANDOM
SET behavior_compat_options='display_leading_zero';
SELECT gms_random.value()::numeric(10, 8);
SELECT gms_random.value(10, 20)::numeric(10, 8);
SELECT gms_random.normal()::numeric(10, 8);
SELECT gms_random.initialize(8);
SELECT gms_random.normal()::numeric(10, 8);
SELECT gms_random.normal()::numeric(10, 8);
SELECT gms_random.seed(8);
SELECT gms_random.random();
SELECT gms_random.seed('test');
SELECT gms_random.string('U',5);
SELECT gms_random.string('P',2);
SELECT gms_random.string('x',4);
SELECT gms_random.string('a',2);
SELECT gms_random.string('l',3);
SELECT gms_random.seed(5);
SELECT gms_random.value()::numeric(10, 8);
SELECT gms_random.value(10,15)::numeric(10, 8);
SELECT gms_random.terminate();
