\set ECHO none
SET client_min_messages = warning;
SET DATESTYLE TO ISO;
SET client_encoding = utf8;
\pset null '<NULL>'
\set ECHO all

DROP FUNCTION gms_output_test();
DROP TABLE gms_output_test;

-- GMS_OUTPUT.DISABLE [0]
CREATE TABLE gms_output_test (buff VARCHAR(20), status INTEGER);
CREATE FUNCTION gms_output_test() RETURNS VOID AS $$
DECLARE
	buff	VARCHAR(20);
	stts	INTEGER;
BEGIN
	PERFORM GMS_OUTPUT.PUT_LINE ('ORAFCE TEST 1');
	SELECT INTO buff,stts line,status FROM GMS_OUTPUT.GET_LINE();
	INSERT INTO gms_output_test VALUES (buff, stts);
END;
$$ LANGUAGE plpgsql;
SELECT gms_output_test();
SELECT * FROM gms_output_test;
DROP TABLE gms_output_test;
DROP FUNCTION gms_output_test();

-- GMS_OUTPUT.PUT_LINE [1]
CREATE FUNCTION gms_output_test() RETURNS VOID AS $$
DECLARE
	buff1	VARCHAR(20) := 'orafce';
BEGIN
	PERFORM GMS_OUTPUT.DISABLE();
	PERFORM GMS_OUTPUT.ENABLE();
	PERFORM GMS_OUTPUT.SERVEROUTPUT ('t');
	PERFORM GMS_OUTPUT.PUT_LINE ('ORAFCE');
	PERFORM GMS_OUTPUT.PUT_LINE (buff1);
	PERFORM GMS_OUTPUT.PUT ('ABC');
	PERFORM GMS_OUTPUT.PUT_LINE (' ');
END;
$$ LANGUAGE plpgsql;
SELECT gms_output_test();
DROP FUNCTION gms_output_test();

-- GMS_OUTPUT.PUT_LINE [2]
CREATE FUNCTION gms_output_test() RETURNS VOID AS $$
BEGIN
	PERFORM GMS_OUTPUT.DISABLE();
	PERFORM GMS_OUTPUT.ENABLE();
	PERFORM GMS_OUTPUT.SERVEROUTPUT ('t');
	PERFORM GMS_OUTPUT.PUT_LINE ('ORA
F
CE');
END;
$$ LANGUAGE plpgsql;
SELECT gms_output_test();
DROP FUNCTION gms_output_test();

-- GMS_OUTPUT.PUT [1]
CREATE FUNCTION gms_output_test() RETURNS VOID AS $$
DECLARE
	buff1	VARCHAR(20) := 'ora';
	buff2	VARCHAR(20) := 'f';
	buff3	VARCHAR(20) := 'ce';
BEGIN
	PERFORM GMS_OUTPUT.DISABLE();
	PERFORM GMS_OUTPUT.ENABLE();
	PERFORM GMS_OUTPUT.SERVEROUTPUT ('t');
	PERFORM GMS_OUTPUT.PUT ('ORA');
	PERFORM GMS_OUTPUT.PUT ('F');
	PERFORM GMS_OUTPUT.PUT ('CE');
	PERFORM GMS_OUTPUT.PUT_LINE (' ');
	PERFORM GMS_OUTPUT.PUT ('ABC');
	PERFORM GMS_OUTPUT.PUT_LINE (' ');
END;
$$ LANGUAGE plpgsql;
SELECT gms_output_test();
DROP FUNCTION gms_output_test();

-- GMS_OUTPUT.PUT [2]
CREATE FUNCTION gms_output_test() RETURNS VOID AS $$
BEGIN
	PERFORM GMS_OUTPUT.DISABLE();
	PERFORM GMS_OUTPUT.ENABLE();
	PERFORM GMS_OUTPUT.SERVEROUTPUT ('t');
	PERFORM GMS_OUTPUT.PUT ('ORA
F
CE');
	PERFORM GMS_OUTPUT.PUT_LINE (' ');
END;
$$ LANGUAGE plpgsql;
SELECT gms_output_test();
DROP FUNCTION gms_output_test();

-- GMS_OUTPUT.GET_LINE [1]
CREATE TABLE gms_output_test (buff VARCHAR(20), status INTEGER);
CREATE FUNCTION gms_output_test() RETURNS VOID AS $$
DECLARE
	buff	VARCHAR(20);
	stts	INTEGER;
BEGIN
	PERFORM GMS_OUTPUT.DISABLE();
	PERFORM GMS_OUTPUT.ENABLE();
	PERFORM GMS_OUTPUT.SERVEROUTPUT ('f');
	PERFORM GMS_OUTPUT.PUT_LINE ('ORAFCE TEST 1');
	PERFORM GMS_OUTPUT.PUT_LINE ('ORAFCE TEST 2');
	SELECT INTO buff,stts line,status FROM GMS_OUTPUT.GET_LINE();
	INSERT INTO gms_output_test VALUES (buff, stts);
	SELECT INTO buff,stts line,status FROM GMS_OUTPUT.GET_LINE();
	INSERT INTO gms_output_test VALUES (buff, stts);
	PERFORM GMS_OUTPUT.DISABLE();
	PERFORM GMS_OUTPUT.ENABLE();
END;
$$ LANGUAGE plpgsql;
SELECT gms_output_test();
SELECT * FROM gms_output_test;
DROP TABLE gms_output_test;
DROP FUNCTION gms_output_test();

-- GMS_OUTPUT.GET_LINE [2]
CREATE TABLE gms_output_test (buff VARCHAR(20), status INTEGER);
CREATE FUNCTION gms_output_test() RETURNS VOID AS $$
DECLARE
	buff	VARCHAR(20);
	stts	INTEGER;
BEGIN
	PERFORM GMS_OUTPUT.DISABLE();
	PERFORM GMS_OUTPUT.ENABLE();
	PERFORM GMS_OUTPUT.SERVEROUTPUT ('f');
	PERFORM GMS_OUTPUT.PUT_LINE ('ORAFCE TEST 1');
	PERFORM GMS_OUTPUT.PUT_LINE ('ORAFCE TEST 2');
	SELECT INTO buff,stts line,status FROM GMS_OUTPUT.GET_LINE();
	INSERT INTO gms_output_test VALUES (buff, stts);
	PERFORM GMS_OUTPUT.PUT_LINE ('ORAFCE TEST 3');
	SELECT INTO buff,stts line,status FROM GMS_OUTPUT.GET_LINE();
	INSERT INTO gms_output_test VALUES (buff, stts);
	SELECT INTO buff,stts line,status FROM GMS_OUTPUT.GET_LINE();
	INSERT INTO gms_output_test VALUES (buff, stts);
	SELECT INTO buff,stts line,status FROM GMS_OUTPUT.GET_LINE();
	INSERT INTO gms_output_test VALUES (buff, stts);
	PERFORM GMS_OUTPUT.DISABLE();
	PERFORM GMS_OUTPUT.ENABLE();
END;
$$ LANGUAGE plpgsql;
SELECT gms_output_test();
SELECT * FROM gms_output_test;
DROP TABLE gms_output_test;
DROP FUNCTION gms_output_test();

-- GMS_OUTPUT.GET_LINE [3]
CREATE TABLE gms_output_test (buff VARCHAR(20), status INTEGER);
CREATE FUNCTION gms_output_test() RETURNS VOID AS $$
DECLARE
	buff	VARCHAR(20);
	stts	INTEGER;
BEGIN
	PERFORM GMS_OUTPUT.DISABLE();
	PERFORM GMS_OUTPUT.ENABLE();
	PERFORM GMS_OUTPUT.SERVEROUTPUT ('f');
	PERFORM GMS_OUTPUT.PUT_LINE ('ORAFCE TEST 1');
	PERFORM GMS_OUTPUT.PUT_LINE ('ORAFCE TEST 2');
	SELECT INTO buff,stts line,status FROM GMS_OUTPUT.GET_LINE();
	INSERT INTO gms_output_test VALUES (buff, stts);
	PERFORM GMS_OUTPUT.PUT ('ORA');
	SELECT INTO buff,stts line,status FROM GMS_OUTPUT.GET_LINE();
	INSERT INTO gms_output_test VALUES (buff, stts);
	SELECT INTO buff,stts line,status FROM GMS_OUTPUT.GET_LINE();
	INSERT INTO gms_output_test VALUES (buff, stts);
	PERFORM GMS_OUTPUT.DISABLE();
	PERFORM GMS_OUTPUT.ENABLE();
END;
$$ LANGUAGE plpgsql;
SELECT gms_output_test();
SELECT * FROM gms_output_test;
DROP TABLE gms_output_test;
DROP FUNCTION gms_output_test();

-- GMS_OUTPUT.GET_LINE [4]
CREATE TABLE gms_output_test (buff VARCHAR(20), status INTEGER);
CREATE FUNCTION gms_output_test() RETURNS VOID AS $$
DECLARE
	buff	VARCHAR(20);
	stts	INTEGER;
BEGIN
	PERFORM GMS_OUTPUT.DISABLE();
	PERFORM GMS_OUTPUT.ENABLE();
	PERFORM GMS_OUTPUT.SERVEROUTPUT ('f');
	PERFORM GMS_OUTPUT.PUT_LINE ('ORAFCE TEST 1');
	PERFORM GMS_OUTPUT.PUT_LINE ('ORAFCE TEST 2');
	SELECT INTO buff,stts line,status FROM GMS_OUTPUT.GET_LINE();
	INSERT INTO gms_output_test VALUES (buff, stts);
	PERFORM GMS_OUTPUT.NEW_LINE();
	SELECT INTO buff,stts line,status FROM GMS_OUTPUT.GET_LINE();
	INSERT INTO gms_output_test VALUES (buff, stts);
	SELECT INTO buff,stts line,status FROM GMS_OUTPUT.GET_LINE();
	INSERT INTO gms_output_test VALUES (buff, stts);
	PERFORM GMS_OUTPUT.DISABLE();
	PERFORM GMS_OUTPUT.ENABLE();
END;
$$ LANGUAGE plpgsql;
SELECT gms_output_test();
SELECT * FROM gms_output_test;
DROP TABLE gms_output_test;
DROP FUNCTION gms_output_test();

-- GMS_OUTPUT.GET_LINE [5]
CREATE TABLE gms_output_test (buff VARCHAR(20), status INTEGER);
CREATE FUNCTION gms_output_test() RETURNS VOID AS $$
DECLARE
	buff	VARCHAR(20);
	stts	INTEGER;
BEGIN
	PERFORM GMS_OUTPUT.DISABLE();
	PERFORM GMS_OUTPUT.ENABLE();
	PERFORM GMS_OUTPUT.SERVEROUTPUT ('f');
	PERFORM GMS_OUTPUT.PUT_LINE ('ORAFCE TEST 1
');
	PERFORM GMS_OUTPUT.PUT_LINE ('ORAFCE TEST 2');
	SELECT INTO buff,stts line,status FROM GMS_OUTPUT.GET_LINE();
	INSERT INTO gms_output_test VALUES (buff, stts);
	SELECT INTO buff,stts line,status FROM GMS_OUTPUT.GET_LINE();
	INSERT INTO gms_output_test VALUES (buff, stts);
	PERFORM GMS_OUTPUT.DISABLE();
	PERFORM GMS_OUTPUT.ENABLE();
END;
$$ LANGUAGE plpgsql;
SELECT gms_output_test();
SELECT REPLACE(buff, '
', '<LF>') FROM gms_output_test;
DROP TABLE gms_output_test;
DROP FUNCTION gms_output_test();

-- GMS_OUTPUT.GET_LINE [6]
CREATE TABLE gms_output_test (buff VARCHAR(20), status INTEGER);
CREATE FUNCTION gms_output_test() RETURNS VOID AS $$
DECLARE
	buff	VARCHAR(20);
	stts	INTEGER;
BEGIN
	PERFORM GMS_OUTPUT.DISABLE();
	PERFORM GMS_OUTPUT.ENABLE();
	PERFORM GMS_OUTPUT.SERVEROUTPUT ('f');
	PERFORM GMS_OUTPUT.PUT_LINE ('ORA
F
CE');
	SELECT INTO buff,stts line,status FROM GMS_OUTPUT.GET_LINE();
	INSERT INTO gms_output_test VALUES (buff, stts);
	PERFORM GMS_OUTPUT.DISABLE();
	PERFORM GMS_OUTPUT.ENABLE();
END;
$$ LANGUAGE plpgsql;
SELECT gms_output_test();
SELECT regexp_replace(buff, E'\n', '<LF>', 'g') FROM gms_output_test limit 1;
DROP TABLE gms_output_test;
DROP FUNCTION gms_output_test();

-- GMS_OUTPUT.GET_LINES [1]
CREATE TABLE gms_output_test (buff VARCHAR(20), status INTEGER);
CREATE FUNCTION gms_output_test() RETURNS VOID AS $$
DECLARE
	buff	VARCHAR(20);
	buff1	VARCHAR(20);
	buff2	VARCHAR(20);
	buff3	VARCHAR(20);
	stts	INTEGER := 10;
BEGIN
	PERFORM GMS_OUTPUT.DISABLE();
	PERFORM GMS_OUTPUT.ENABLE();
	PERFORM GMS_OUTPUT.SERVEROUTPUT ('f');
	PERFORM GMS_OUTPUT.PUT_LINE ('ORAFCE TEST 1');
	PERFORM GMS_OUTPUT.PUT_LINE ('ORAFCE TEST 2');
	PERFORM GMS_OUTPUT.PUT_LINE ('ORAFCE TEST 3');
	SELECT INTO buff1,buff2,buff3,stts lines[1],lines[2],lines[3],numlines FROM GMS_OUTPUT.GET_LINES(stts);
	INSERT INTO gms_output_test VALUES (buff1, stts);
	INSERT INTO gms_output_test VALUES (buff2, stts);
	INSERT INTO gms_output_test VALUES (buff3, stts);
	SELECT INTO buff,stts lines[1],numlines FROM GMS_OUTPUT.GET_LINES(stts);
	INSERT INTO gms_output_test VALUES (buff, stts);
	PERFORM GMS_OUTPUT.DISABLE();
	PERFORM GMS_OUTPUT.ENABLE();
END;
$$ LANGUAGE plpgsql;
SELECT gms_output_test();
SELECT * FROM gms_output_test;
DROP TABLE gms_output_test;
DROP FUNCTION gms_output_test();

-- GMS_OUTPUT.GET_LINES [2]
CREATE TABLE gms_output_test (buff VARCHAR(20), status INTEGER);
CREATE FUNCTION gms_output_test() RETURNS VOID AS $$
DECLARE
	buff	VARCHAR(20);
	buff1	VARCHAR(20);
	buff2	VARCHAR(20);
	stts	INTEGER := 2;
BEGIN
	PERFORM GMS_OUTPUT.DISABLE();
	PERFORM GMS_OUTPUT.ENABLE();
	PERFORM GMS_OUTPUT.SERVEROUTPUT ('f');
	PERFORM GMS_OUTPUT.PUT_LINE ('ORAFCE TEST 1');
	PERFORM GMS_OUTPUT.PUT_LINE ('ORAFCE TEST 2');
	PERFORM GMS_OUTPUT.PUT_LINE ('ORAFCE TEST 3');
	SELECT INTO buff1,buff2,stts lines[1],lines[2],numlines FROM GMS_OUTPUT.GET_LINES(stts);
	INSERT INTO gms_output_test VALUES (buff1, stts);
	INSERT INTO gms_output_test VALUES (buff2, stts);
	SELECT INTO buff,stts lines[1],numlines FROM GMS_OUTPUT.GET_LINES(stts);
	INSERT INTO gms_output_test VALUES (buff, stts);
	PERFORM GMS_OUTPUT.DISABLE();
	PERFORM GMS_OUTPUT.ENABLE();
END;
$$ LANGUAGE plpgsql;
SELECT gms_output_test();
SELECT * FROM gms_output_test;
DROP TABLE gms_output_test;
DROP FUNCTION gms_output_test();

-- GMS_OUTPUT.GET_LINES [3]
CREATE TABLE gms_output_test (buff VARCHAR(20), status INTEGER);
CREATE FUNCTION gms_output_test() RETURNS VOID AS $$
DECLARE
	buff	VARCHAR(20);
	stts	INTEGER := 1;
BEGIN
	PERFORM GMS_OUTPUT.DISABLE();
	PERFORM GMS_OUTPUT.ENABLE();
	PERFORM GMS_OUTPUT.SERVEROUTPUT ('f');
	PERFORM GMS_OUTPUT.PUT_LINE ('ORAFCE TEST 1');
	PERFORM GMS_OUTPUT.PUT_LINE ('ORAFCE TEST 2');
	SELECT INTO buff,stts lines[1],numlines FROM GMS_OUTPUT.GET_LINES(stts);
	INSERT INTO gms_output_test VALUES (buff, stts);
	PERFORM GMS_OUTPUT.PUT_LINE ('ORAFCE TEST 3');
	SELECT INTO buff,stts lines[1],numlines FROM GMS_OUTPUT.GET_LINES(stts);
	INSERT INTO gms_output_test VALUES (buff, stts);
	SELECT INTO buff,stts lines[1],numlines FROM GMS_OUTPUT.GET_LINES(stts);
	INSERT INTO gms_output_test VALUES (buff, stts);
	PERFORM GMS_OUTPUT.DISABLE();
	PERFORM GMS_OUTPUT.ENABLE();
END;
$$ LANGUAGE plpgsql;
SELECT gms_output_test();
SELECT * FROM gms_output_test;
DROP TABLE gms_output_test;
DROP FUNCTION gms_output_test();

-- GMS_OUTPUT.GET_LINES [4]
CREATE TABLE gms_output_test (buff VARCHAR(20), status INTEGER);
CREATE FUNCTION gms_output_test() RETURNS VOID AS $$
DECLARE
	buff	VARCHAR(20);
	stts	INTEGER := 1;
BEGIN
	PERFORM GMS_OUTPUT.DISABLE();
	PERFORM GMS_OUTPUT.ENABLE();
	PERFORM GMS_OUTPUT.SERVEROUTPUT ('f');
	PERFORM GMS_OUTPUT.PUT_LINE ('ORAFCE TEST 1');
	PERFORM GMS_OUTPUT.PUT_LINE ('ORAFCE TEST 2');
	SELECT INTO buff,stts lines[1],numlines FROM GMS_OUTPUT.GET_LINES(stts);
	INSERT INTO gms_output_test VALUES (buff, stts);
	PERFORM GMS_OUTPUT.PUT ('ORA');
	SELECT INTO buff,stts lines[1],numlines FROM GMS_OUTPUT.GET_LINES(stts);
	INSERT INTO gms_output_test VALUES (buff, stts);
	SELECT INTO buff,stts lines[1],numlines FROM GMS_OUTPUT.GET_LINES(stts);
	INSERT INTO gms_output_test VALUES (buff, stts);
	PERFORM GMS_OUTPUT.DISABLE();
	PERFORM GMS_OUTPUT.ENABLE();
END;
$$ LANGUAGE plpgsql;
SELECT gms_output_test();
SELECT * FROM gms_output_test;
DROP TABLE gms_output_test;
DROP FUNCTION gms_output_test();

-- GMS_OUTPUT.GET_LINES [5]
CREATE TABLE gms_output_test (buff VARCHAR(20), status INTEGER);
CREATE FUNCTION gms_output_test() RETURNS VOID AS $$
DECLARE
	buff	VARCHAR(20);
	stts	INTEGER := 1;
BEGIN
	PERFORM GMS_OUTPUT.DISABLE();
	PERFORM GMS_OUTPUT.ENABLE();
	PERFORM GMS_OUTPUT.SERVEROUTPUT ('f');
	PERFORM GMS_OUTPUT.PUT_LINE ('ORAFCE TEST 1');
	PERFORM GMS_OUTPUT.PUT_LINE ('ORAFCE TEST 2');
	SELECT INTO buff,stts lines[1],numlines FROM GMS_OUTPUT.GET_LINES(stts);
	INSERT INTO gms_output_test VALUES (buff, stts);
	PERFORM GMS_OUTPUT.NEW_LINE();
	SELECT INTO buff,stts lines[1],numlines FROM GMS_OUTPUT.GET_LINES(stts);
	INSERT INTO gms_output_test VALUES (buff, stts);
	SELECT INTO buff,stts lines[1],numlines FROM GMS_OUTPUT.GET_LINES(stts);
	INSERT INTO gms_output_test VALUES (buff, stts);
	PERFORM GMS_OUTPUT.DISABLE();
	PERFORM GMS_OUTPUT.ENABLE();
END;
$$ LANGUAGE plpgsql;
SELECT gms_output_test();
SELECT * FROM gms_output_test;
DROP TABLE gms_output_test;
DROP FUNCTION gms_output_test();

-- GMS_OUTPUT.GET_LINES [6]
CREATE TABLE gms_output_test (buff VARCHAR(20), status INTEGER);
CREATE FUNCTION gms_output_test() RETURNS VOID AS $$
DECLARE
	buff	VARCHAR(20);
	stts	INTEGER := 1;
BEGIN
	PERFORM GMS_OUTPUT.DISABLE();
	PERFORM GMS_OUTPUT.ENABLE();
	PERFORM GMS_OUTPUT.SERVEROUTPUT ('f');
	PERFORM GMS_OUTPUT.PUT_LINE ('ORA
F
CE');
	SELECT INTO buff,stts lines[1],numlines FROM GMS_OUTPUT.GET_LINES(stts);
	INSERT INTO gms_output_test VALUES (buff, stts);
	PERFORM GMS_OUTPUT.DISABLE();
	PERFORM GMS_OUTPUT.ENABLE();
END;
$$ LANGUAGE plpgsql;
SELECT gms_output_test();
SELECT regexp_replace(buff, E'\n', '<LF>', 'g') FROM gms_output_test limit 1;
DROP TABLE gms_output_test;
DROP FUNCTION gms_output_test();

-- GMS_OUTPUT.NEW_LINE [1]
CREATE TABLE gms_output_test (buff VARCHAR(20), status INTEGER);
CREATE FUNCTION gms_output_test() RETURNS VOID AS $$
DECLARE
	buff1	VARCHAR(20);
	buff2	VARCHAR(20);
	stts	INTEGER := 10;
BEGIN
	PERFORM GMS_OUTPUT.DISABLE();
	PERFORM GMS_OUTPUT.ENABLE();
	PERFORM GMS_OUTPUT.SERVEROUTPUT ('f');
	PERFORM GMS_OUTPUT.PUT ('ORA');
	PERFORM GMS_OUTPUT.NEW_LINE();
	PERFORM GMS_OUTPUT.PUT ('FCE');
	PERFORM GMS_OUTPUT.NEW_LINE();
	SELECT INTO buff1,buff2,stts lines[1],lines[2],numlines FROM GMS_OUTPUT.GET_LINES(stts);
	INSERT INTO gms_output_test VALUES (buff1, stts);
	INSERT INTO gms_output_test VALUES (buff2, stts);
	PERFORM GMS_OUTPUT.DISABLE();
	PERFORM GMS_OUTPUT.ENABLE();
END;
$$ LANGUAGE plpgsql;
SELECT gms_output_test();
SELECT * FROM gms_output_test;
DROP TABLE gms_output_test;
DROP FUNCTION gms_output_test();

-- GMS_OUTPUT.NEW_LINE [2]
CREATE TABLE gms_output_test (buff VARCHAR(3000), status INTEGER);
CREATE FUNCTION gms_output_test() RETURNS VOID AS $$
DECLARE
	buff1	VARCHAR(3000);
	stts	INTEGER := 10;
BEGIN
	PERFORM GMS_OUTPUT.DISABLE();
	PERFORM GMS_OUTPUT.ENABLE();
	PERFORM GMS_OUTPUT.SERVEROUTPUT ('f');
	PERFORM GMS_OUTPUT.ENABLE(2000);
	FOR j IN 1..1999 LOOP
		PERFORM GMS_OUTPUT.PUT ('A');
	END LOOP;
	PERFORM GMS_OUTPUT.NEW_LINE();
	SELECT INTO buff1,stts lines[1],numlines FROM GMS_OUTPUT.GET_LINES(stts);
	INSERT INTO gms_output_test VALUES (buff1, stts);
	PERFORM GMS_OUTPUT.DISABLE();
	PERFORM GMS_OUTPUT.ENABLE();
END;
$$ LANGUAGE plpgsql;
SELECT gms_output_test();
SELECT buff FROM gms_output_test;
DROP TABLE gms_output_test;
DROP FUNCTION gms_output_test();

-- GMS_OUTPUT.DISABLE [1]
CREATE TABLE gms_output_test (buff VARCHAR(20), status INTEGER);
CREATE FUNCTION gms_output_test() RETURNS VOID AS $$
DECLARE
	buff	VARCHAR(20);
	stts	INTEGER;
BEGIN
	PERFORM GMS_OUTPUT.DISABLE();
	PERFORM GMS_OUTPUT.ENABLE();
	PERFORM GMS_OUTPUT.SERVEROUTPUT ('f');
	PERFORM GMS_OUTPUT.PUT_LINE ('ORAFCE TEST 1');
	PERFORM GMS_OUTPUT.DISABLE();
	PERFORM GMS_OUTPUT.ENABLE();
	SELECT INTO buff,stts line,status FROM GMS_OUTPUT.GET_LINE();
	INSERT INTO gms_output_test VALUES (buff, stts);

	PERFORM GMS_OUTPUT.DISABLE();
	PERFORM GMS_OUTPUT.ENABLE();
	PERFORM GMS_OUTPUT.DISABLE();
	PERFORM GMS_OUTPUT.PUT_LINE ('ORAFCE TEST 2');
	PERFORM GMS_OUTPUT.ENABLE();
	SELECT INTO buff,stts line,status FROM GMS_OUTPUT.GET_LINE();
	INSERT INTO gms_output_test VALUES (buff, stts);
	
	PERFORM GMS_OUTPUT.DISABLE();
	PERFORM GMS_OUTPUT.ENABLE();
	PERFORM GMS_OUTPUT.PUT_LINE ('ORAFCE TEST 3');
	PERFORM GMS_OUTPUT.DISABLE();
	SELECT INTO buff,stts line,status FROM GMS_OUTPUT.GET_LINE();
	INSERT INTO gms_output_test VALUES (buff, stts);
	PERFORM GMS_OUTPUT.ENABLE();

	PERFORM GMS_OUTPUT.DISABLE();
	PERFORM GMS_OUTPUT.ENABLE();
	PERFORM GMS_OUTPUT.DISABLE();
	PERFORM GMS_OUTPUT.PUT ('ORAFCE TEST 4');
	PERFORM GMS_OUTPUT.ENABLE();
	PERFORM GMS_OUTPUT.NEW_LINE();
	SELECT INTO buff,stts line,status FROM GMS_OUTPUT.GET_LINE();
	INSERT INTO gms_output_test VALUES (buff, stts);

	PERFORM GMS_OUTPUT.DISABLE();
	PERFORM GMS_OUTPUT.ENABLE();
	PERFORM GMS_OUTPUT.PUT ('ORAFCE TEST 5');
	PERFORM GMS_OUTPUT.DISABLE();
	PERFORM GMS_OUTPUT.NEW_LINE();
	PERFORM GMS_OUTPUT.ENABLE();
	SELECT INTO buff,stts line,status FROM GMS_OUTPUT.GET_LINE();
	INSERT INTO gms_output_test VALUES (buff, stts);

	PERFORM GMS_OUTPUT.DISABLE();
	PERFORM GMS_OUTPUT.ENABLE();
END;
$$ LANGUAGE plpgsql;
SELECT gms_output_test();
SELECT * FROM gms_output_test;
DROP TABLE gms_output_test;
DROP FUNCTION gms_output_test();

-- GMS_OUTPUT.DISABLE [2]
CREATE TABLE gms_output_test (buff VARCHAR(20), status INTEGER);
CREATE FUNCTION gms_output_test() RETURNS VOID AS $$
DECLARE
	buff	VARCHAR(20);
	stts	INTEGER := 10;
BEGIN
	PERFORM GMS_OUTPUT.DISABLE();
	PERFORM GMS_OUTPUT.ENABLE();
	PERFORM GMS_OUTPUT.SERVEROUTPUT ('f');
	PERFORM GMS_OUTPUT.DISABLE();
	PERFORM GMS_OUTPUT.PUT_LINE ('ORAFCE TEST 1');
	SELECT INTO buff,stts lines[1],numlines FROM GMS_OUTPUT.GET_LINES(stts);
	INSERT INTO gms_output_test VALUES (buff, stts);
	PERFORM GMS_OUTPUT.ENABLE();
END;
$$ LANGUAGE plpgsql;
SELECT gms_output_test();
SELECT * FROM gms_output_test;
DROP TABLE gms_output_test;
DROP FUNCTION gms_output_test();

-- GMS_OUTPUT.ENABLE [1]
CREATE TABLE gms_output_test (buff VARCHAR(20), status INTEGER);
CREATE FUNCTION gms_output_test() RETURNS VOID AS $$
DECLARE
	buff	VARCHAR(20);
	status	INTEGER;
	num		INTEGER := 2000;
BEGIN
	PERFORM GMS_OUTPUT.DISABLE();
	PERFORM GMS_OUTPUT.ENABLE();
	PERFORM GMS_OUTPUT.SERVEROUTPUT ('t');
	PERFORM GMS_OUTPUT.ENABLE(2000);
	PERFORM GMS_OUTPUT.PUT ('ORAFCE TEST 1');
	PERFORM GMS_OUTPUT.NEW_LINE();
	PERFORM GMS_OUTPUT.ENABLE();
END;
$$ LANGUAGE plpgsql;
SELECT gms_output_test();
SELECT * FROM gms_output_test;
DROP TABLE gms_output_test;
DROP FUNCTION gms_output_test();

-- GMS_OUTPUT.ENABLE [2]
CREATE TABLE gms_output_test (buff VARCHAR(20), status INTEGER);
CREATE FUNCTION gms_output_test() RETURNS VOID AS $$
DECLARE
	buff	VARCHAR(20);
	stts	INTEGER;
BEGIN
	PERFORM GMS_OUTPUT.DISABLE();
	PERFORM GMS_OUTPUT.ENABLE();
	PERFORM GMS_OUTPUT.SERVEROUTPUT ('f');
	PERFORM GMS_OUTPUT.DISABLE();
	PERFORM GMS_OUTPUT.ENABLE();
	PERFORM GMS_OUTPUT.PUT_LINE ('ORAFCE TEST 1');
	SELECT INTO buff,stts line,status FROM GMS_OUTPUT.GET_LINE();
	INSERT INTO gms_output_test VALUES (buff, stts);
	PERFORM GMS_OUTPUT.PUT ('ORAFCE TEST 2');
	PERFORM GMS_OUTPUT.NEW_LINE();
	SELECT INTO buff,stts line,status FROM GMS_OUTPUT.GET_LINE();
	INSERT INTO gms_output_test VALUES (buff, stts);
	PERFORM GMS_OUTPUT.ENABLE();
END;
$$ LANGUAGE plpgsql;
SELECT gms_output_test();
SELECT * FROM gms_output_test;
DROP TABLE gms_output_test;
DROP FUNCTION gms_output_test();

-- GMS_OUTPUT.ENABLE [3]
CREATE TABLE gms_output_test (buff VARCHAR(20), status INTEGER);
CREATE FUNCTION gms_output_test() RETURNS VOID AS $$
DECLARE
	buff	VARCHAR(20);
	stts	INTEGER := 10;
BEGIN
	PERFORM GMS_OUTPUT.DISABLE();
	PERFORM GMS_OUTPUT.ENABLE();
	PERFORM GMS_OUTPUT.SERVEROUTPUT ('f');
	PERFORM GMS_OUTPUT.DISABLE();
	PERFORM GMS_OUTPUT.ENABLE();
	PERFORM GMS_OUTPUT.PUT_LINE ('ORAFCE TEST 1');
	SELECT INTO buff,stts lines[1],numlines FROM GMS_OUTPUT.GET_LINES(stts);
	INSERT INTO gms_output_test VALUES (buff, stts);

END;
$$ LANGUAGE plpgsql;
SELECT gms_output_test();
SELECT * FROM gms_output_test;
DROP TABLE gms_output_test;
DROP FUNCTION gms_output_test();

-- GMS_OUTPUT.ENABLE [4]
CREATE FUNCTION gms_output_test() RETURNS VOID AS $$
BEGIN
	PERFORM GMS_OUTPUT.DISABLE();
	PERFORM GMS_OUTPUT.ENABLE();
	PERFORM GMS_OUTPUT.SERVEROUTPUT ('t');
	PERFORM GMS_OUTPUT.DISABLE();
	PERFORM GMS_OUTPUT.ENABLE();
	FOR j IN 1..2000 LOOP
		PERFORM GMS_OUTPUT.PUT ('A');
	END LOOP;
	PERFORM GMS_OUTPUT.NEW_LINE();
END;
$$ LANGUAGE plpgsql;
SELECT gms_output_test();
DROP FUNCTION gms_output_test();

-- GMS_OUTPUT.ENABLE [5]
CREATE TABLE gms_output_test (buff VARCHAR(20), status INTEGER);
CREATE FUNCTION gms_output_test() RETURNS VOID AS $$
DECLARE
	buff	VARCHAR(20);
	stts	INTEGER;
BEGIN
	PERFORM GMS_OUTPUT.DISABLE();
	PERFORM GMS_OUTPUT.ENABLE();
	PERFORM GMS_OUTPUT.SERVEROUTPUT ('f');
	PERFORM GMS_OUTPUT.DISABLE();
	PERFORM GMS_OUTPUT.ENABLE(NULL);
	PERFORM GMS_OUTPUT.PUT_LINE ('ORAFCE TEST 1');
	SELECT INTO buff,stts line,status FROM GMS_OUTPUT.GET_LINE();
	INSERT INTO gms_output_test VALUES (buff, stts);
	PERFORM GMS_OUTPUT.DISABLE();
	PERFORM GMS_OUTPUT.ENABLE();
END;
$$ LANGUAGE plpgsql;
SELECT gms_output_test();
SELECT * FROM gms_output_test;
DROP TABLE gms_output_test;
DROP FUNCTION gms_output_test();

-- GMS_OUTPUT.ENABLE [6]
CREATE TABLE gms_output_test (buff VARCHAR(20), status INTEGER);
CREATE FUNCTION gms_output_test() RETURNS VOID AS $$
DECLARE
	buff	VARCHAR(20);
	stts	INTEGER;
BEGIN
	PERFORM GMS_OUTPUT.DISABLE();
	PERFORM GMS_OUTPUT.ENABLE();
	PERFORM GMS_OUTPUT.SERVEROUTPUT ('f');
	PERFORM GMS_OUTPUT.PUT_LINE ('ORAFCE TEST 1');
	PERFORM GMS_OUTPUT.ENABLE();
	SELECT INTO buff,stts line,status FROM GMS_OUTPUT.GET_LINE();
	INSERT INTO gms_output_test VALUES (buff, stts);
	PERFORM GMS_OUTPUT.DISABLE();
	PERFORM GMS_OUTPUT.ENABLE();
END;
$$ LANGUAGE plpgsql;
SELECT gms_output_test();
SELECT * FROM gms_output_test;
DROP TABLE gms_output_test;
DROP FUNCTION gms_output_test();

-- SERVEROUTPUT [1]
CREATE FUNCTION gms_output_test() RETURNS VOID AS $$
BEGIN
	PERFORM GMS_OUTPUT.DISABLE();
	PERFORM GMS_OUTPUT.ENABLE();
	PERFORM GMS_OUTPUT.SERVEROUTPUT ('f');
	PERFORM GMS_OUTPUT.PUT_LINE ('ORAFCE TEST 1');
END;
$$ LANGUAGE plpgsql;
SELECT gms_output_test();
DROP FUNCTION gms_output_test();

CREATE FUNCTION gms_output_test() RETURNS VOID AS $$
BEGIn
	PERFORM GMS_OUTPUT.DISABLE();
	PERFORM GMS_OUTPUT.ENABLE();
	PERFORM GMS_OUTPUT.SERVEROUTPUT ('t');
	PERFORM GMS_OUTPUT.PUT_LINE ('ORAFCE TEST 2');
END;
$$ LANGUAGE plpgsql;
SELECT gms_output_test();
DROP FUNCTION gms_output_test();

-- SERVEROUTPUT [2]
CREATE FUNCTION gms_output_test() RETURNS VOID AS $$
BEGIN
	PERFORM GMS_OUTPUT.DISABLE();
	PERFORM GMS_OUTPUT.ENABLE();
	PERFORM GMS_OUTPUT.SERVEROUTPUT ('f');
	PERFORM GMS_OUTPUT.PUT ('ORAFCE TEST 1');
	PERFORM GMS_OUTPUT.NEW_LINE();
END;
$$ LANGUAGE plpgsql;
SELECT gms_output_test();
DROP FUNCTION gms_output_test();

CREATE FUNCTION gms_output_test() RETURNS VOID AS $$
BEGIN
	PERFORM GMS_OUTPUT.DISABLE();
	PERFORM GMS_OUTPUT.ENABLE();
	PERFORM GMS_OUTPUT.SERVEROUTPUT ('t');
	PERFORM GMS_OUTPUT.PUT ('ORAFCE TEST 2');
	PERFORM GMS_OUTPUT.NEW_LINE();
END;
$$ LANGUAGE plpgsql;
SELECT gms_output_test();
DROP FUNCTION gms_output_test();

-- SERVEROUTPUT [3]
CREATE FUNCTION gms_output_test() RETURNS VOID AS $$
BEGIN
	PERFORM GMS_OUTPUT.DISABLE();
	PERFORM GMS_OUTPUT.ENABLE();
	PERFORM GMS_OUTPUT.SERVEROUTPUT ('f');
	PERFORM GMS_OUTPUT.DISABLE();
END;
$$ LANGUAGE plpgsql;
SELECT gms_output_test();
DROP FUNCTION gms_output_test();

CREATE FUNCTION gms_output_test() RETURNS VOID AS $$
BEGIN
	PERFORM GMS_OUTPUT.DISABLE();
	PERFORM GMS_OUTPUT.ENABLE();
	PERFORM GMS_OUTPUT.SERVEROUTPUT ('t');
	PERFORM GMS_OUTPUT.PUT_LINE ('ORAFCE TEST 1');
END;
$$ LANGUAGE plpgsql;
SELECT gms_output_test();
DROP FUNCTION gms_output_test();
