#
# Makefile for optimizer
#
# src/spq_optimizer/libnaucrates/src/xml/Makefile
#
subdir = src/spq_optimizer/libnaucrates/src/xml
top_builddir = ../../../../../../..
include $(top_builddir)/src/Makefile.global
include ../../../spqorca.mk

OBJS = CDXLMemoryManager.o \
       CDXLSections.o \
       CXMLSerializer.o \
       dxltokens.o

include $(top_srcdir)/src/gausskernel/common.mk