#
# Makefile for optimizer
#
# src/spq_optimizer/libspqopt/src/metadata/Makefile
#
subdir = src/spq_optimizer/libspqopt/src/metadata
top_builddir = ../../../../../../..
include $(top_builddir)/src/Makefile.global
include ../../../spqorca.mk

OBJS = CColumnDescriptor.o \
       CIndexDescriptor.o \
       CName.o \
       CPartConstraint.o \
       CTableDescriptor.o

include $(top_srcdir)/src/gausskernel/common.mk