#
# Makefile for optimizer
#
# src/spq_optimizer/libspqos/src/common/Makefile
#
subdir = src/spq_optimizer/libspqos/src/common
top_builddir = ../../../../../../..
include $(top_builddir)/src/Makefile.global
include ../../../spqorca.mk

OBJS = CAutoTimer.o \
       CBitSet.o \
       CBitSetIter.o \
       CBitVector.o \
       CDebugCounter.o \
       CHeapObject.o \
       CMainArgs.o \
       CRandom.o \
       CRefCount.o \
       CStackDescriptor.o \
       CStackObject.o \
       CTimerUser.o \
       CWallClock.o \
       clibwrapper.o \
       syslibwrapper.o

include $(top_srcdir)/src/gausskernel/common.mk