#
# Makefile for optimizer
#
# src/spq_optimizer/libspqos/src/task/Makefile
#
subdir = src/spq_optimizer/libspqos/src/task
top_builddir = ../../../../../../..
include $(top_builddir)/src/Makefile.global
include ../../../spqorca.mk

OBJS = CAutoSuspendAbort.o \
                     CAutoTaskProxy.o \
                     CAutoTraceFlag.o \
                     CTask.o \
                     CTaskContext.o \
                     CTaskLocalStorage.o \
                     CTaskSchedulerFifo.o \
                     CWorker.o \
                     CWorkerPoolManager.o \
                     ITask.o \
                     IWorker.o

include $(top_srcdir)/src/gausskernel/common.mk