#
# Makefile for optimizer
#
# src/spq_optimizer/libnaucrates/src/base/Makefile
#
subdir = src/spq_optimizer/libnaucrates/src/base
top_builddir = ../../../../../../..
include $(top_builddir)/src/Makefile.global
include ../../../spqorca.mk

OBJS = CDatumBoolSPQDB.o \
       CDatumGenericSPQDB.o \
       CDatumInt2SPQDB.o \
       CDatumInt4SPQDB.o \
       CDatumInt8SPQDB.o \
       CDatumOidSPQDB.o \
       CQueryToDXLResult.o \
       IDatum.o

include $(top_srcdir)/src/gausskernel/common.mk